### ISSUE TITLE
Node auto-scaling on a kubeadm cluster

### ISSUE THREAD

**Issue by dilipk8** [kubernetes/kubeadm#2757] opened 2022-09-21 11:47 UTC
## Is this a BUG REPORT or FEATURE REQUEST?
 FEATURE REQUEST

If this is a FEATURE REQUEST, please:
  - A method or a way to automatically scale up and scale down worker nodes in a kubeadm kubernetes cluster.

## Versions

All version of kubeadm

**Environment**:
- **Kubernetes version** (use `kubectl version`):  All versions of Kubernetes
- **Cloud provider or hardware configuration**:   AWS
- **OS** (e.g. from /etc/os-release):  Ubuntu 20.04.3 LTS
- **Kernel** (e.g. `uname -a`):  Linux - 5.15.0-1019-aws #23~20.04.1-Ubuntu
- **Container runtime (CRI)** (e.g. containerd, cri-o):  Container-d
- **Container networking plugin (CNI)** (e.g. Calico, Cilium):  Weave-net

## What happened?
Cluster autoscaler can be used in kubeadm clusters, however, the joining of the worker node is something that separately needs to handled or taken care of. There is not direct way to auto-scale nodes.
And Karpenter, as of now, apparently just works on EKS and kOps. 

## What you expected to happen?
Node auto-scaling of  kubeadm clusters.

**Comment by neolit123** [comment] 2022-09-21 13:37
hi. this is out of scope for kubeadm as it just runs on the nodes as cli. it can be managed by high level tools like kubespray or capi. capi already has some autoscaler integration.

**Closed by neolit123** 2022-09-21 13:37 UTC

**Comment by KetulRadadiya** [comment] 2023-10-18 05:16
Hi, I have installed Cluster autoscaler using helm chart in kubeadm cluster, I am able to manage automatically join of worker node to cluster using init script and autoscale up feature works fine. A worker node is created on-demand through an autoscaling group and automatically joins the cluster when it is ready. A heavy k8s workload also deployed on the new worker node.
The problem is 12 to 15 minutes after the node joining event, Cluster autoscaler somehow triggers the scale down event.
Here I have used different flags to not scale down the node.

```
- ./cluster-autoscaler
- --cloud-provider=aws
- --namespace=kube-system
- --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/kubernetes-admin@kubernetes
- --cordon-node-before-terminating=true
- --cores-total=0:40
- --logtostderr=true
- --scale-down-enabled=false                                 # Not working 
- --memory-total=0:160
- --scale-down-unneeded-time=60m                     # Not working
- --scale-down-utilization-threshold=0                  # Not able to see any logs related to utilization
- --skip-nodes-with-local-storage=false
- --stderrthreshold=info
- --v=6
```

Cluster autoscaler version: [v1.23.0](https://github.com/kubernetes/autoscaler/tree/cluster-autoscaler-1.23.0)
Kubeadm cluster: 1.27.6

Logs of cluster autoscaler pod during scale down trigger events.
```
I1017 14:26:51.628346       1 static_autoscaler.go:230] Starting main loop
W1017 14:26:51.628686       1 aws_cloud_provider.go:103] Node ip-172-20-10-162 has no providerId
I1017 14:26:51.628724       1 aws_manager.go:313] Found multiple availability zones for ASG "k8s-managed-job-autoscaling"; using ap-south-1c for failure-domain.beta.kubernetes.io/zone label
I1017 14:26:51.629307       1 csi.go:97] "Could not get a CSINode object for the node" node="k8s-managed-job-autoscaling-asg-6710715718024909786" err="csinode.storage.k8s.io \"k8s-managed-job-autoscaling-asg-6710715718024909786\" not found"
I1017 14:26:51.629360       1 csi.go:97] "Could not get a CSINode object for the node" node="k8s-managed-job-autoscaling-asg-6710715718024909786" err="csinode.storage.k8s.io \"k8s-managed-job-autoscaling-asg-6710715718024909786\" not found"
I1017 14:26:51.629396       1 csi.go:97] "Could not get a CSINode object for the node" node="k8s-managed-job-autoscaling-asg-6710715718024909786" err="csinode.storage.k8s.io \"k8s-managed-job-autoscaling-asg-6710715718024909786\" not found"
I1017 14:26:51.629518       1 node_instances_cache.go:132] Get cached cloud provider node instances for k8s-managed-job-autoscaling
W1017 14:26:51.629555       1 aws_cloud_provider.go:103] Node ip-172-20-10-162 has no providerId
I1017 14:26:51.629591       1 static_autoscaler.go:334] 1 unregistered nodes present
I1017 14:26:51.629694       1 filter_out_schedulable.go:65] Filtering out schedulables
I1017 14:26:51.629710       1 filter_out_schedulable.go:132] Filtered out 0 pods using hints
I1017 14:26:51.629718       1 filter_out_schedulable.go:170] 0 pods were kept as unschedulable based on caching
I1017 14:26:51.629723       1 filter_out_schedulable.go:171] 0 pods marked as unschedulable can be scheduled.
I1017 14:26:51.629733       1 filter_out_schedulable.go:82] No schedulable pods
I1017 14:26:51.629746       1 static_autoscaler.go:419] No unschedulable pods
I1017 14:26:51.633535       1 round_trippers.go:553] GET https://10.97.0.1:443/api/v1/namespaces/kube-system/configmaps/cluster-autoscaler-status 200 OK in 3 milliseconds
I1017 14:26:51.640115       1 round_trippers.go:553] PUT https://10.97.0.1:443/api/v1/namespaces/kube-system/configmaps/cluster-autoscaler-status 200 OK in 6 milliseconds
I1017 14:26:52.030699       1 reflector.go:536] k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:188: Watch close - *v1.Pod total 6 items received
I1017 14:26:52.032619       1 round_trippers.go:553] GET https://10.97.0.1:443/api/v1/pods?allowWatchBookmarks=true&fieldSelector=spec.nodeName%3D%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&resourceVersion=1920616&timeoutSeconds=593&watch=true 200 OK in 1 milliseconds
I1017 14:26:52.612927       1 round_trippers.go:553] GET https://10.97.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cluster-autoscaler 200 OK in 2 milliseconds
I1017 14:26:52.617765       1 round_trippers.go:553] PUT https://10.97.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cluster-autoscaler 200 OK in 4 milliseconds
I1017 14:26:52.618027       1 leaderelection.go:278] successfully renewed lease kube-system/cluster-autoscaler
I1017 14:26:54.621002       1 round_trippers.go:553] GET https://10.97.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cluster-autoscaler 200 OK in 2 milliseconds
I1017 14:26:54.625716       1 round_trippers.go:553] PUT https://10.97.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cluster-autoscaler 200 OK in 4 milliseconds
I1017 14:26:54.625976       1 leaderelection.go:278] successfully renewed lease kube-system/cluster-autoscaler
I1017 14:26:55.231590       1 pathrecorder.go:240] cluster-autoscaler: "/health-check" satisfied by exact match
I1017 14:26:56.628849       1 round_trippers.go:553] GET https://10.97.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cluster-autoscaler 200 OK in 2 milliseconds
I1017 14:26:56.633454       1 round_trippers.go:553] PUT https://10.97.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cluster-autoscaler 200 OK in 4 milliseconds
I1017 14:26:56.634890       1 leaderelection.go:278] successfully renewed lease kube-system/cluster-autoscaler
I1017 14:26:58.638582       1 round_trippers.go:553] GET https://10.97.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cluster-autoscaler 200 OK in 3 milliseconds
I1017 14:26:58.645228       1 round_trippers.go:553] PUT https://10.97.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cluster-autoscaler 200 OK in 6 milliseconds
I1017 14:26:58.645612       1 leaderelection.go:278] successfully renewed lease kube-system/cluster-autoscaler
I1017 14:26:59.987031       1 reflector.go:255] Listing and watching *v1beta1.PodDisruptionBudget from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:309
I1017 14:26:59.988702       1 round_trippers.go:553] GET https://10.97.0.1:443/apis/policy/v1beta1/poddisruptionbudgets?limit=500&resourceVersion=0 404 Not Found in 1 milliseconds
W1017 14:26:59.988871       1 reflector.go:324] k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:309: failed to list *v1beta1.PodDisruptionBudget: the server could not find the requested resource
E1017 14:26:59.988906       1 reflector.go:138] k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:309: Failed to watch *v1beta1.PodDisruptionBudget: failed to list *v1beta1.PodDisruptionBudget: the server could not find the requested resource
I1017 14:27:00.648565       1 round_trippers.go:553] GET https://10.97.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cluster-autoscaler 200 OK in 2 milliseconds
I1017 14:27:00.653098       1 round_trippers.go:553] PUT https://10.97.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cluster-autoscaler 200 OK in 4 milliseconds
I1017 14:27:00.653442       1 leaderelection.go:278] successfully renewed lease kube-system/cluster-autoscaler
I1017 14:27:01.641386       1 static_autoscaler.go:230] Starting main loop
W1017 14:27:01.641692       1 aws_cloud_provider.go:103] Node ip-172-20-10-162 has no providerId
I1017 14:27:01.641906       1 aws_manager.go:313] Found multiple availability zones for ASG "k8s-managed-job-autoscaling"; using ap-south-1c for failure-domain.beta.kubernetes.io/zone label
I1017 14:27:01.642394       1 csi.go:97] "Could not get a CSINode object for the node" node="k8s-managed-job-autoscaling-asg-7675671191860293954" err="csinode.storage.k8s.io \"k8s-managed-job-autoscaling-asg-7675671191860293954\" not found"
I1017 14:27:01.642526       1 csi.go:97] "Could not get a CSINode object for the node" node="k8s-managed-job-autoscaling-asg-7675671191860293954" err="csinode.storage.k8s.io \"k8s-managed-job-autoscaling-asg-7675671191860293954\" not found"
I1017 14:27:01.642593       1 csi.go:97] "Could not get a CSINode object for the node" node="k8s-managed-job-autoscaling-asg-7675671191860293954" err="csinode.storage.k8s.io \"k8s-managed-job-autoscaling-asg-7675671191860293954\" not found"
I1017 14:27:01.642913       1 node_instances_cache.go:132] Get cached cloud provider node instances for k8s-managed-job-autoscaling
W1017 14:27:01.642992       1 aws_cloud_provider.go:103] Node ip-172-20-10-162 has no providerId
I1017 14:27:01.643070       1 static_autoscaler.go:334] 1 unregistered nodes present
I1017 14:27:01.643211       1 filter_out_schedulable.go:65] Filtering out schedulables
I1017 14:27:01.643230       1 filter_out_schedulable.go:132] Filtered out 0 pods using hints
I1017 14:27:01.643237       1 filter_out_schedulable.go:170] 0 pods were kept as unschedulable based on caching
I1017 14:27:01.643244       1 filter_out_schedulable.go:171] 0 pods marked as unschedulable can be scheduled.
I1017 14:27:01.643266       1 filter_out_schedulable.go:82] No schedulable pods
I1017 14:27:01.643282       1 static_autoscaler.go:419] No unschedulable pods
I1017 14:27:01.646695       1 round_trippers.go:553] GET https://10.97.0.1:443/api/v1/namespaces/kube-system/configmaps/cluster-autoscaler-status 200 OK in 2 milliseconds
I1017 14:27:01.652027       1 round_trippers.go:553] PUT https://10.97.0.1:443/api/v1/namespaces/kube-system/configmaps/cluster-autoscaler-status 200 OK in 5 milliseconds
I1017 14:27:02.657414       1 round_trippers.go:553] GET https://10.97.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cluster-autoscaler 200 OK in 2 milliseconds
I1017 14:27:02.662044       1 round_trippers.go:553] PUT https://10.97.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cluster-autoscaler 200 OK in 3 milliseconds
I1017 14:27:02.662339       1 leaderelection.go:278] successfully renewed lease kube-system/cluster-autoscaler
I1017 14:27:04.665012       1 round_trippers.go:553] GET https://10.97.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cluster-autoscaler 200 OK in 2 milliseconds
I1017 14:27:04.672007       1 round_trippers.go:553] PUT https://10.97.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cluster-autoscaler 200 OK in 6 milliseconds
I1017 14:27:04.672238       1 leaderelection.go:278] successfully renewed lease kube-system/cluster-autoscaler
I1017 14:27:05.230947       1 pathrecorder.go:240] cluster-autoscaler: "/health-check" satisfied by exact match
I1017 14:27:06.675061       1 round_trippers.go:553] GET https://10.97.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cluster-autoscaler 200 OK in 2 milliseconds
I1017 14:27:06.679657       1 round_trippers.go:553] PUT https://10.97.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cluster-autoscaler 200 OK in 4 milliseconds
I1017 14:27:06.679962       1 leaderelection.go:278] successfully renewed lease kube-system/cluster-autoscaler
I1017 14:27:07.386455       1 reflector.go:255] Listing and watching *v1beta1.CSIStorageCapacity from k8s.io/client-go/informers/factory.go:134
I1017 14:27:07.387832       1 round_trippers.go:553] GET https://10.97.0.1:443/apis/storage.k8s.io/v1beta1/csistoragecapacities?limit=500&resourceVersion=0 404 Not Found in 1 milliseconds
W1017 14:27:07.388046       1 reflector.go:324] k8s.io/client-go/informers/factory.go:134: failed to list *v1beta1.CSIStorageCapacity: the server could not find the requested resource
E1017 14:27:07.388147       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1beta1.CSIStorageCapacity: failed to list *v1beta1.CSIStorageCapacity: the server could not find the requested resource
I1017 14:27:08.683845       1 round_trippers.go:553] GET https://10.97.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cluster-autoscaler 200 OK in 2 milliseconds
I1017 14:27:08.687698       1 round_trippers.go:553] PUT https://10.97.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cluster-autoscaler 200 OK in 3 milliseconds
I1017 14:27:08.687893       1 leaderelection.go:278] successfully renewed lease kube-system/cluster-autoscaler
I1017 14:27:10.691224       1 round_trippers.go:553] GET https://10.97.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cluster-autoscaler 200 OK in 2 milliseconds
I1017 14:27:10.698821       1 round_trippers.go:553] PUT https://10.97.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cluster-autoscaler 200 OK in 7 milliseconds
I1017 14:27:10.699032       1 leaderelection.go:278] successfully renewed lease kube-system/cluster-autoscaler
```

**Comment by neolit123** [comment] 2023-10-18 05:28
> Cluster autoscaler somehow triggers the scale down event.
Here I have used different flags to not scale down the node.

that seems like an autoscaller question. i know projects like Cluster API by default uses kubeadm for adding nodes and Cluster API also has experimental support for the autoscaller - i.e. they do use it, and it works.

it could be a misconfiguration, so try asking the autoscaller maintainers:
https://github.com/kubernetes/autoscaler
