### ISSUE TITLE
kubeadm 1.6->1.7 upgrade documentation: add --pod-network-cidr flag

### ISSUE THREAD

**Issue by praseodym** [kubernetes/kubeadm#331] opened 2017-07-02 14:30 UTC
## Versions

**kubeadm version** (use `kubeadm version`): 1.7.0

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.7.0
- **Cloud provider or hardware configuration**: VMware
- **OS** (e.g. from /etc/os-release): Debian Stretch
- **Kernel** (e.g. `uname -a`): Linux 4.9.0-3-amd64

## What happened?
I upgraded my cluster from 1.6.5 to 1.7.0 using the [kubeadm upgrade instructions](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm-upgrade-1-7/). Unfortunately, I forgot to pass the `--pod-network-cidr=` flag to kubeadm even though I'm running Flannel. This caused the cidr settings to be removed from the kube-controller-manager and kube-proxy components.

## What you expected to happen?
Either kubeadm should detect the previous cidr value, or the documentation should mention to add the cidr flag for upgrades.

**Comment by luxas** [comment] 2017-07-02 14:43
Indeed a docs issue. We'll fix that ASAP. Any flags you passed into v1.6 must be passed again when upgrading to v1.7.

**Comment by luxas** [comment] 2017-07-05 09:45
Closing as a dupe of #333

**Closed by luxas** 2017-07-05 09:45 UTC
