### ISSUE TITLE
Kubeadm DNS setup isn't compatible with stock ubuntu 18.04

### ISSUE THREAD

**Issue by farcaller** [kubernetes/kubeadm#787] opened 2018-05-03 10:08 UTC
## What keywords did you search in kubeadm issues before filing this one?

dns

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** 1.10.2

**Environment**:
- **Kubernetes version** 1.10.2
- **Cloud provider or hardware configuration**: hetzner cloud running ubuntu 18.04
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04 LTS (Bionic Beaver)

## What happened?

Following the kubeadm guide creates a cluster that doesn't have a functional DNS.

## What you expected to happen?

Following the kubeadm guide creates a cluster that works.

## How to reproduce it (as minimally and precisely as possible)?

Follow the kubeadm setup doc.

## Anything else we need to know?

It seems that 18.04 had switched to systemd-resolved by default, which generates a managed `/etc/resolv.conf` on the host:

```
nameserver 127.0.0.53
```

it's not a problem for docker at it will override the DNS with google dns, but kubeadm spins up coredns pods (or kubedns) with dns policy set to "default", meaning that the dns pod will have itself as a resolver. For coredns that means it will crashloop on any external name resolution as it's OOMing on the query recursion.

I'd think the best way to move forward with this is to allow kubeadm to manage `dnsConfig` of the resolver pod, but given it's an alpha feature, kubeadm should at least do a sanity check and not allow a cluster to be created if the host resolv.conf is pointing at localhost.

**Comment by steven-sheehy** [comment] 2018-05-04 04:41
Happens to me on Ubuntu 18.04 as well. I tried with both coredns and kube-dns and they both fail. Are there any known workarounds either in Kubernetes or the OS?

**Comment by steven-sheehy** [comment] 2018-05-04 05:56
Answering my own question. Workaround is to use the legacy format resolv.conf that [systemd-resolved](https://www.freedesktop.org/software/systemd/man/systemd-resolved.html#/etc/resolv.conf) provides:

```shell
sudo rm /etc/resolv.conf
sudo ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf
```

**Comment by luxas** [comment] 2018-05-11 17:38
Closing as a duplicate of https://github.com/kubernetes/kubeadm/issues/273.
Thanks for filing this issue though, it made us re-prioritize this bug :+1:

**Closed by luxas** 2018-05-11 17:38 UTC
Labels: priority/important-soon

**Comment by bhardwahnitish19** [comment] 2020-05-10 08:59
I am still facing this issue with minikube 1.9.2, k8s v1.15.12 and ubuntu 18.04.4. Tried the mentioned work around but it didn't work. Could you please suggest something?

I am trying to access a service exposed as NodePort. Things used to work perfectly until my system crashed and I had to re-install Ubuntu and minikube. Facing this issue since 2 days. 

I would really appreciate any help.

Thanks
