### ISSUE TITLE
kubeadm RPMs for v1.9.1 are not signed

### ISSUE THREAD

**Issue by rmohr** [kubernetes/kubeadm#643] opened 2018-01-05 08:23 UTC
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):

```
kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

- **OS** (e.g. from /etc/os-release): CentOS Linux release 7.2.1511 (Core) 

## What happened?

When installing the rpms on centos, it fails on the signature check. Like in #205 

The exact version of the RPM is: 

```
Package 94c663be41ebfdd6543df07847c9bee9c98513130088d22b8068ecfa5a146714-kubeadm-1.9.1-0.x86_64.rpm is not signed
```
## What you expected to happen?

That the rpms are signed.

## How to reproduce it (as minimally and precisely as possible)?

Same steps like in #205

**Comment by luxas** [comment] 2018-01-08 06:43
cc @mbohlool @jdumars @enisoc @ixdy @pipejakob ^^

**Comment by enisoc** [comment] 2018-01-08 20:09
This should be fixed now as part of fixing https://github.com/kubernetes/release/issues/495.

**Comment by luxas** [comment] 2018-01-08 22:21
Thanks @enisoc, closing as a dupe of https://github.com/kubernetes/release/issues/495

**Closed by luxas** 2018-01-08 22:21 UTC
