### ISSUE TITLE
kubeadm join should support kubelet component config

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubeadm#2008] opened 2020-01-22 21:32 UTC
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: ~BUG REPORT or~ FEATURE REQUEST

As far as I can tell `KubeletConfiguration` while advertised in the kubeadm config docs is not respected during `kubeadm join --config`, which means we must instead configure kubelet via flags in kubeadm's JoinConfiguration.NodeRegistration.KubeletExtraArgs. This is less than ideal because kubelet flags are often deprecated in favor of the component config fields and we have no way to configure these for nodes via kubeadm.

Ideally specifying a `KubeletConfiguration` object would work in `kubeadm init` _and_ `kubeadm join` via `--config`, but I'm not sure what happens there yet or what exactly is involved to change this.

https://github.com/kubernetes-sigs/kind/issues/1270

---

## Versions

**kubeadm version** (use `kubeadm version`):  `kubeadm version: &version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:08:27Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Kubernetes version** (use `kubectl version`): `$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
`
- **Cloud provider or hardware configuration**: [kind](https://sigs.k8s.io/kind)
- **OS** (e.g. from /etc/os-release): ~ubuntu
- **Kernel** (e.g. `uname -a`): 5.2.17
- **Others**:

**Comment by neolit123** [comment] 2020-01-22 22:46
duplicate of https://github.com/kubernetes/kubeadm/issues/1682

**Closed by neolit123** 2020-01-22 22:46 UTC

**Comment by BenTheElder** [comment] 2020-01-22 22:57
thanks! I didn't find that one searching, sorry about that!
