### ISSUE TITLE
kubeadm not respecting kubernetesVersion in 1.8.4

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kubeadm#612] opened 2017-12-22 16:48 UTC
When using `kubeadm` *1.8.4* to deploy a control plane we are defining a `kubeadm` config as follows:

```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
cloudProvider: aws
token: 24f587.a7ae829b3e618f81
kubernetesVersion: 1.8.4
nodeName: ip-10-0-0-35.us-west-2.compute.internal
api:
  advertiseAddress: 34.213.176.254
  bindPort: 443
apiServerCertSANs:
- 34.213.176.254
- ip-10-0-0-35.us-west-2.compute.internal
- 10.0.0.35
authorizationModes:
- Node
- RBAC
```

The control plane boots successfully, but we are running kubernetes *1.9.0*

Also important to note we are installing `kubeadm-1.8.4-00` from the `apt-get` repositories

Logs:

```
[preflight] Running pre-flight checks
[reset] Stopping the kubelet service
[reset] Unmounting mounted directories in "/var/lib/kubelet"
[reset] Removing kubernetes-managed containers
[reset] No etcd manifest found in "/etc/kubernetes/manifests/etcd.yaml", assuming external etcd.
[reset] Deleting contents of stateful directories: [/var/lib/kubelet /etc/cni/net.d /var/lib/dockershim /var/run/kubernetes]
[reset] Deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
[reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[init] Using Kubernetes version: v1.8.4
[init] Using Authorization modes: [Node RBAC]
[init] WARNING: For cloudprovider integrations to work --cloud-provider must be set for all kubelets in the cluster.
	(/etc/systemd/system/kubelet.service.d/10-kubeadm.conf should be edited for this purpose)
[preflight] Running pre-flight checks
[preflight] Starting the kubelet service
[kubeadm] WARNING: starting in 1.8, tokens expire after 24 hours by default (if you require a non-expiring token use --token-ttl 0)
[certificates] Generated ca certificate and key.
[certificates] Generated apiserver certificate and key.
[certificates] apiserver serving cert is signed for DNS names [ip-10-0-0-35.us-west-2.compute.internal kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local ip-10-0-0-35.us-west-2.compute.internal] and IPs [10.96.0.1 34.213.176.254 34.213.176.254 10.0.0.35]
[certificates] Generated apiserver-kubelet-client certificate and key.
[certificates] Generated sa key and public key.
[certificates] Generated front-proxy-ca certificate and key.
[certificates] Generated front-proxy-client certificate and key.
[certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
[kubeconfig] Wrote KubeConfig file to disk: "admin.conf"
[kubeconfig] Wrote KubeConfig file to disk: "kubelet.conf"
[kubeconfig] Wrote KubeConfig file to disk: "controller-manager.conf"
[kubeconfig] Wrote KubeConfig file to disk: "scheduler.conf"
[controlplane] Wrote Static Pod manifest for component kube-apiserver to "/etc/kubernetes/manifests/kube-apiserver.yaml"
[controlplane] Wrote Static Pod manifest for component kube-controller-manager to "/etc/kubernetes/manifests/kube-controller-manager.yaml"
[controlplane] Wrote Static Pod manifest for component kube-scheduler to "/etc/kubernetes/manifests/kube-scheduler.yaml"
[etcd] Wrote Static Pod manifest for a local etcd instance to "/etc/kubernetes/manifests/etcd.yaml"
[init] Waiting for the kubelet to boot up the control plane as Static Pods from directory "/etc/kubernetes/manifests"
[init] This often takes around a minute; or longer if the control plane images have to be pulled.
[apiclient] All control plane components are healthy after 44.522192 seconds
[uploadconfig] Storing the configuration used in ConfigMap "kubeadm-config" in the "kube-system" Namespace
[markmaster] Will mark node ip-10-0-0-35.us-west-2.compute.internal as master by adding a label and a taint
[markmaster] Master ip-10-0-0-35.us-west-2.compute.internal tainted and labelled with key/value: node-role.kubernetes.io/master=""
[bootstraptoken] Using token: 24f587.a7ae829b3e618f81
[bootstraptoken] Configured RBAC rules to allow Node Bootstrap tokens to post CSRs in order for nodes to get long term certificate credentials
[bootstraptoken] Configured RBAC rules to allow the csrapprover controller automatically approve CSRs from a Node Bootstrap Token
[bootstraptoken] Configured RBAC rules to allow certificate rotation for all node client certificates in the cluster
[bootstraptoken] Creating the "cluster-info" ConfigMap in the "kube-public" namespace
[addons] Applied essential addon: kube-dns
[addons] Applied essential addon: kube-proxy

Your Kubernetes master has initialized successfully!

To start using your cluster, you need to run (as a regular user):

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  http://kubernetes.io/docs/admin/addons/

You can now join any number of machines by running the following on each node
as root:

  kubeadm join --token 24f587.a7ae829b3e618f81 34.213.176.254:443 --discovery-token-ca-cert-hash sha256:ba353ea0cdf278287fa516b3af7ca59e5d35a5fe23a14935187e5a6e0227a06d

configmap "calico-config" created
daemonset "calico-etcd" created
service "calico-etcd" created
daemonset "calico-node" created
deployment "calico-policy-controller" created
clusterrolebinding "calico-cni-plugin" created
clusterrole "calico-cni-plugin" created
serviceaccount "calico-cni-plugin" created
clusterrolebinding "calico-policy-controller" created
clusterrole "calico-policy-controller" created
serviceaccount "calico-policy-controller" created
storageclass "gp2" created
Cloud-init v. 0.7.9 running 'modules:final' at Fri, 22 Dec 2017 16:42:35 +0000. Up 8.32 seconds.
Cloud-init v. 0.7.9 finished at Fri, 22 Dec 2017 16:43:50 +0000. Datasource DataSourceEc2.  Up 83.52 seconds
```

CC @nrb

**Comment by xmudrii** [comment] 2017-12-22 19:47
`kubectl version` reports Kubernetes version while `kubectl get no` will reports `kubelet` version. I tested this with version `1.8.6` and this is what `version` reports:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
Server version reports `v1.8.6`.
Your logs also reports version `1.8.4`: `[init] Using Kubernetes version: v1.8.4`

The problem is that `kubelet` version is `v1.9.0` and that's what you see when you run `kubectl get nodes`:
```
NAME      STATUS     ROLES     AGE       VERSION
some-hostname   NotReady   master    14m       v1.9.0
```

If you describe node:
```
Kubelet Version:            v1.9.0
Kube-Proxy Version:         v1.9.0
```

The solution is to install `kubelet` version `v1.8.4` in your case. If you're using `apt-get` to install it, command would be:
```
apt-get install -y socat ebtables docker.io apt-transport-https kubelet=1.8.6-00 kubeadm=1.8.6-00 cloud-utils jq kubernetes-cni=0.5.1-00
```
You have to manually specify `kubernetes-cni` version as well, or `apt-get` will report version mismatch and fail.

`get nodes` will report correct version this time:
```
NAME        STATUS     ROLES     AGE       VERSION
k8sworker   NotReady   master    22s       v1.8.6
```
Same for describe:
```
 Kubelet Version:            v1.8.6
 Kube-Proxy Version:         v1.8.6
```

**Comment by luxas** [comment] 2017-12-25 17:10
Hmm, that's really strange... Do you have any more details to give me, like `kubeadm version` before running `kubeadm init`?

I can't reproduce this locally with either kubeadm v1.8.4 or v1.9.0...

**Comment by timothysc** [comment] 2018-01-30 15:44
I'm also surprised by this... are there repro instructions?  

cc @chuckha

**Comment by xmudrii** [comment] 2018-01-30 18:25
@luxas @timothysc You can take a look at [the script](https://github.com/kris-nova/kubicorn/blob/master/bootstrap/amazon_k8s_ubuntu_16.04_master.sh) we're using for Kubicorn. We're installing the `kubeadm` version `1.8.4`, but still, we always end up with the latest version.

**Comment by mattkelly** [comment] 2018-02-20 01:58
@luxas @timothysc I'm confused by the ongoing discussion here. As @xmudrii correctly pointed out, `kubeadm` does not install `kubelet` for you and so the version must be pinned separately with whatever mechanism `kubelet` is installed using. In the kubicorn script referenced here, [the version is not being pinned](https://github.com/kris-nova/kubicorn/blob/master/bootstrap/amazon_k8s_ubuntu_16.04_master.sh#L30) when installed via `apt-get`.

This can be closed as there's nothing to do, right? Should be an easy change on the `kubicorn` side.

**Closed** 2018-03-13 20:00 UTC
Labels: kind/bug, priority/important-soon, triaged
