### ISSUE TITLE
Improvements for etcd liveness probes

### ISSUE THREAD

**Issue by randomvariable** [kubernetes/kubeadm#2567] opened 2021-09-10 14:56 UTC
## What keywords did you search in kubeadm issues before filing this one?

This is related to https://github.com/kubernetes/kubernetes/issues/96886 
and https://github.com/etcd-io/etcd/issues/13340 

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`): v1.22, etcd v3.5.0

## What happened?

Under certain cluster conditions, such as an entire cluster being powered off and on, then you may not want etcd pods restarted if no raft leader is present since leader election is taking place. There are more details in the https://github.com/etcd-io/etcd/issues/13340, in which we have requested that there is either a lightweight `/ready` endpoint added to etcd or to allow `/health` to take additional query parameters that would allow us to relax the constraints.

Once that's in place, downstream consumers can use the JSON patch method to patch the etcd static pod (e.g. https://github.com/kubernetes-sigs/cluster-api/issues/4874).

However, we may also want to change the defaults for kubeadm but we should do some modelling about what state transitions and cluster conditions we care about. 

Additionally, I think we will also want to relax the consistency constraints as part of learner mode adoption.

This is mostly a tracking issue for possible changes to etcd that we can consume.

## What you expected to happen?

Turned off clusters can be restarted

## How to reproduce it (as minimally and precisely as possible)?

I have a feeling this is also related to https://github.com/kubernetes-sigs/kind/issues/1689 , so improvements may be testable 

----------

TODOs

1.25:
- add the new health check endpoint for kubeadm probes
[x] https://github.com/kubernetes/kubernetes/pull/110072
- backport the 1.25 change to kubeadm releases that have etcd 3.5.3
TODO
can be done for 1.24 (that has 3.5.3+) but we need 3.5.3 backports to happen for the older releases:
https://github.com/kubernetes/kubernetes/pull/109532
https://github.com/kubernetes/kubernetes/pull/109533

**Comment by pacoxu** [comment] 2021-09-13 10:29
Adding `/health?exclude=NORAFTLEADER&consistency=s` seems to be current workaround solution in kubeadm.

**Comment by neolit123** [comment] 2021-09-13 10:49
I was under the impression that it does not work.

**Comment by pacoxu** [comment] 2021-09-13 11:29
How to easily reproduce it with a simple script?

**Comment by randomvariable** [comment] 2021-09-15 17:23
I think starting a HA kind cluster, and then shutting down the containers and restarting them might be sufficient. I have a feeling it's related to https://github.com/kubernetes-sigs/kind/issues/1689

**Comment by neolit123** [comment] 2021-11-22 18:05
looks like etcd 3.6 will have the missing feature that we wanted.
https://github.com/etcd-io/etcd/issues/13340

we are in code freeze for 1.23, but this seems like something that can be added once 1.24 starts and backported to older releases (assuming it's not a big diff in kubeadm).

**Comment by palnabarun** [comment] 2021-11-23 13:19
It also depends on when etcd 3.6 would be released. Does etcd follow a defined timeline? Unless I am missing something, I couldn't find much with my searching the web skills.

PS: If etcd 3.6 gets released before Code Freeze for Kubernetes 1.24, I would like to work on this.

**Comment by neolit123** [comment] 2021-11-23 13:57
Etcd does not have a fixed cadence for minors AFAIK.
It took two years between .4 and .5 appatently.
But prior releases were only one year appart.

Judging from that i don't think this will align with 1.24 k8s.

**Comment by palnabarun** [comment] 2021-11-23 14:35
Can we ask the etcd team if they would like to cut a patch release with the said feature?

**Comment by neolit123** [comment] 2021-11-23 15:28
i don't think they will agree to that, but worth a try if someone wants to do it.

**Comment by ahrtr** [comment] 2022-02-17 07:06
FYI. Back porting the PR to etcd 3.5, https://github.com/etcd-io/etcd/pull/13706

**Comment by ahrtr** [comment] 2022-02-17 07:56
cc @serathius

**Comment by neolit123** [comment] 2022-02-17 12:45
@ahrtr great. If the etcd backport is accepted we can try backporting a kubeadm etcd bump.

**Comment by pacoxu** [comment] 2022-02-22 01:40
The backport PR to v3.5 https://github.com/etcd-io/etcd/pull/13706 was merged and we may wait for etcd v3.5.3.

**Comment by ahrtr** [comment] 2022-02-22 01:54
Yes, the PR was merged, and I just submitted another PR [pull/13725](https://github.com/etcd-io/etcd/pull/13725) to update the 3.5 changelog.

**Comment by neolit123** [comment] 2022-04-18 18:57
etcd bump to 3.5.3 merged in 1.24 /master.
https://github.com/kubernetes/kubernetes/pull/109471

here are backports for 1.23 and 1.22:
https://github.com/kubernetes/kubernetes/pull/109533
https://github.com/kubernetes/kubernetes/pull/109532

after / if these merge we would want to backport and enable the new probes conditionally for kubeadm versions that use 3.5.3.

**Comment by neolit123** [comment] 2022-04-18 19:10
i think what we have to do to enable the new check is the following in the etcd manifest:

```
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
-        path: /health
+        path: /health/serializable=true
        port: 2381
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
```

but it must be done only for k8s control plane version >= 1.22 if the above cherry picks merege.

**Comment by neolit123** [comment] 2022-05-11 16:44
once we add etcd 3.5.3 to the support skew, would anyone like to work on this?

xref https://github.com/kubernetes/kubernetes/pull/109471

**Comment by neolit123** [comment] 2022-05-16 14:43
1.25 PR is here:
https://github.com/kubernetes/kubernetes/pull/110072

**Comment by neolit123** [comment] 2022-05-16 15:01
@ahrtr

i've tested the new HTTP endpoint with etcd 3.5.3 and it seems to be failing:
```
    Liveness:     http-get http://127.0.0.1:2381/health/serializable=true delay=10s timeout=15s period=10s #success=1 #failure=8
    Startup:      http-get http://127.0.0.1:2381/health/serializable=true delay=10s timeout=15s period=10s #success=1 #failure=24
```

```
Events:
  Type     Reason     Age   From     Message
  ----     ------     ----  ----     -------
  Normal   Pulled     27s   kubelet  Container image "k8s.gcr.io/etcd:3.5.3-0" already present on machine
  Normal   Created    27s   kubelet  Created container etcd
  Normal   Started    27s   kubelet  Started container etcd
  Warning  Unhealthy  2s    kubelet  Liveness probe failed: HTTP probe failed with statuscode: 404
```

```
$ sudo cat /etc/kubernetes/manifests/etcd.yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/etcd.advertise-client-urls: https://10.0.2.15:2379
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - command:
    - etcd
    - --advertise-client-urls=https://10.0.2.15:2379
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --client-cert-auth=true
    - --data-dir=/var/lib/etcd
    - --experimental-initial-corrupt-check=true
    - --initial-advertise-peer-urls=https://10.0.2.15:2380
    - --initial-cluster=lubo-it=https://10.0.2.15:2380
    - --key-file=/etc/kubernetes/pki/etcd/server.key
    - --listen-client-urls=https://127.0.0.1:2379,https://10.0.2.15:2379
    - --listen-metrics-urls=http://127.0.0.1:2381
    - --listen-peer-urls=https://10.0.2.15:2380
    - --name=lubo-it
    - --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt
    - --peer-client-cert-auth=true
    - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
    - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --snapshot-count=10000
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    image: k8s.gcr.io/etcd:3.5.3-0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /health/serializable=true
        port: 2381
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    name: etcd
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: 127.0.0.1
        path: /health/serializable=true
        port: 2381
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: etcd-data
    - mountPath: /etc/kubernetes/pki/etcd
      name: etcd-certs
  hostNetwork: true
  priorityClassName: system-node-critical
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  volumes:
  - hostPath:
      path: /etc/kubernetes/pki/etcd
      type: DirectoryOrCreate
    name: etcd-certs
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd-data
status: {}
```

any idea what's going on?

**Comment by ahrtr** [comment] 2022-05-16 21:54
The reason is that the PR [etcd/pull/13525](https://github.com/etcd-io/etcd/pull/13525) isn't backported to 3.5.

It's a little subtle. Let's work with an example, assuming there are an etcd cluster with 3 members. There are two cases here:

   1. In the beginning, all 3 members ( or at least 2 members) are working well. Somehow 1 or 2 members are gone/down for whatever reason. Then the left member(s) can still serve serializable requests;
   2. In the beginning, all 3 members ( or at least 2 members) are working well. If you stop all the 3 members, and only restart 1 of them afterwards. Since the quorum isn't satisfied, so the member will not serve client requests, even serializable requests, until the quorum is satisfied. I believe this should be your case. Please double confirm.

Probably we need to backport the PR to 3.5 as well. But it's an enhancement, I need to discuss with other etcd maintainers. Please also let me know whether you really need it, or probably you adjust/update K8s test to adapt to case 1?

**Comment by neolit123** [comment] 2022-05-16 22:30
@ahrtr 

> The reason is that the PR https://github.com/etcd-io/etcd/pull/13525 isn't backported to 3.5.

the issue that i saw earlier was due to a mistake on my end - using `/health/serializable=true` instead of `health?serializable=true`. after switching to `health?serializable=true` startup / liveness probes work as expected, at least for a new cluster with healthy members.

> In the beginning, all 3 members ( or at least 2 members) are working well. If you stop all the 3 members, and only restart 1 of them afterwards. Since the quorum isn't satisfied, so the member will not serve client requests, even serializable requests, until the quorum is satisfied. I believe this should be your case. Please double confirm.

that sounds like the scenario the OP describes here.

> Probably we need to backport the PR to 3.5 as well. But it's an enhancement, I need to discuss with other etcd maintainers. Please also let me know whether you really need it, or probably you adjust/update K8s test to adapt to case 1?

it's unclear to me if these additional changes are needed or not.

**Comment by ahrtr** [comment] 2022-05-16 22:40
The key point is etcd can't finish the bootstrap/startup process if the quorum isn't satisfied. So it can't serve any client requests, even serializable requests.  It is exactly what the PR [13525](https://github.com/etcd-io/etcd/pull/13525) fixed.

But once etcd finishes the bootstrap/startup process, it can continue to serve serializable requests if the quorum isn't satisfied.

**Comment by neolit123** [comment] 2022-05-16 22:42
> The key point is etcd can't finish the bootstrap/startup process if the quorum isn't satisfied. So it can't serve any client requests, even serializable requests. It is exactly what the PR https://github.com/etcd-io/etcd/pull/13525 fixed.

these sounds like a good argument for the backport of https://github.com/etcd-io/etcd/pull/13525

**Comment by ahrtr** [comment] 2022-05-16 22:44
Let me submit a PR for the backport and get feedback from other maintainer.

**Comment by neolit123** [comment] 2022-06-23 15:14
@ahrtr 
PTAL at for LGTM:
https://github.com/kubernetes/kubernetes/pull/110744

it's following your recommendation here:
https://github.com/etcd-io/etcd/issues/14048#issuecomment-1158439700

**Closed** 2022-07-01 04:53 UTC
Labels: kind/bug, priority/important-longterm, kind/feature, lifecycle/active, area/etcd
