### ISSUE TITLE
kubeadm init exists before the cluster is fully functional

### ISSUE THREAD

**Issue by ensonic** [kubernetes/kubeadm#1401] opened 2019-02-11 16:47 UTC
## Is this a request for help?
no

## What keywords did you search in kubeadm issues before filing this one?
init/wait/coredns

## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:51:33Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
- **Kernel** (e.g. `uname -a`):
Linux robco-92eb9a 4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## What happened?

```
kubeadm init --config path/to/config && kubectl --context=kubernetes-admin@kubernetes run setup-cluster --restart=Never -i --rm --image=...

dial tcp: lookup www.example.com on 10.96.0.10:53: read udp 192.168.9.4:38844->10.96.0.10:53: read: connection refused
```

## What you expected to happen?
The 'setup-cluster' pod execute. That is `kubeadm init`command configure these addons:
```
[addons] Applied essential addon: CoreDNS
[addons] Applied essential addon: kube-proxy
```
but does not wait for them to come up successfully. It would be also good if it would offer a separate command that can be used to wait (or a --wait flag).

## Anything else we need to know?

If I wait for *a bit*, then dns is ready and the second step works. I don't want to add a `sleep 5` though.

I've tried the following few things:

1. waiting for coredns to be deployed after kubeadm init
```
kubectl wait deployment/coredns --timeout=60s --for condition=available --namespace=kube-system
deployment.extensions/coredns condition met
```
this works, but coredns does not yet work

2. run commands from https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/
```
kubectl create -f https://k8s.io/examples/admin/dns/busybox.yaml
kubectl wait pod/busybox --timeout=60s --for condition=ready
kubectl exec -ti busybox -- nslookup kubernetes.default


deployment.extensions/coredns condition met
pod/busybox created
pod/busybox condition met
Server:    10.96.0.10
Address 1: 10.96.0.10

nslookup: can't resolve 'kubernetes.default'
command terminated with exit code 1
```

**Comment by fabriziopandini** [comment] 2019-02-11 17:08
@ensonic 
I'm not sure I understand your request considering that the DNS addon gets ready only after installing a CNI plugin, and this is by design not a kubeadm responsibility. Am I missing something?

**Comment by ensonic** [comment] 2019-02-11 17:15
Thanks for the quick reply. The DNS work after a while, but not yet after `kubeadm init` finishes. Also FYI, this is a single node cluster and the config uses 'network-plugin: ""' (same setup like minikube uses).

**Comment by neolit123** [comment] 2019-02-11 22:17
you still need to install a pod network plugin for the DNS addon to come up even in a single node setup.
i don't see how the pods of the DNS addon would ready up without that.

**Comment by ensonic** [comment] 2019-02-14 13:40
Like I said, we're using the 'noop' plugin and it does work. We're now just implementing the synchronization ourself.
In any case the point of the report is that it would be awesome if there is a way to check with kubeadm when things are ready (`kubeadm status`?).

**Comment by gertvdijk** [comment] 2019-04-10 11:31
I'd also really like to have a way to figure out if `kubeadm init` has finished. It currently exits before things are actually ready. :disappointed:

**Comment by neolit123** [comment] 2019-04-11 09:28
this is a common design pattern in kubernetes - you can roll your own way of monitor pods by using e.g. `kubectl get po --all-namespaces -o json`

also keep in mind that installing a CNI plugin is essential for kubeadm init, but at the same time it's a step outside of kubeadm, so there is no way to tell when the pod network will be deployed.

i'm going to close this ticket as it's not a bug.

**Closed by neolit123** 2019-04-11 09:28 UTC
Labels: triage/needs-information

**Comment by ensonic** [comment] 2019-04-14 09:45
`kubectl get po --all-namespaces -o json` won't wait, I'll try `kubectl wait --for=condition=ready --all`. It would be awesome if you can at least recommend a good solution in the docs if you don't feel like adding a `kubeadm wait` command or something like that. 
That said I understand how kubernetes is fully async and components need to deal with unavailability all the time. We now modifies our components to rerun until the dns resolutions worked for dealing with the core-dns startup.
