### ISSUE TITLE
kubeadm: keep dns resourceRequirements on upgrade

### ISSUE THREAD

**Issue by maxl99** [kubernetes/kubeadm#3033] opened 2024-02-29 12:25 UTC
### What happened?

After an upgrade with kubeadm the resourceRequirements will be reset.
Currently the memory limit is hardcoded to 170M in the template.

In our big prod cluster (1000 nodes,5k services, 20k pods) coreDNS needs more than 170M. 
So we increased the mem limit in the deployment after an outage (all coredns pods got OOM killed)
After kubeadm upgrade the deployment gets updated to 170M 
-> Due to that all coredns pods rotate(during startup the probes are sucessful) and will get oomkilled after loading/caching all dns entries

### What did you expect to happen?

keep resourceRequests after kubeadm upgrade

### How can we reproduce it (as minimally and precisely as possible)?

1. change deployment (increase resourceRequests)
2. run kubeadm upgrade

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment] 2024-02-29 18:23
@maxl99 the unwritten kubeadm policy about coredns is the following, roughly - if you'd like customizations you can deploy your own coredns and manage it. that said we did add the feature to preserve the deployment replica count, so maybe we can also preserve other aspects of the existing deployment. but not such that would block the coredns migrator code (like "image" IIRC).

cc @pacoxu @SataQiu WDYT?

your PR comes 6 days before code freeze for 1.30 so i think it's a problem merging it without discussion:
https://github.com/kubernetes/kubernetes/pull/123586

**Comment by neolit123** [comment] 2024-02-29 18:24
/remove-kind bug
/kind feature
(not a bug)

**Comment by maxl99** [comment] 2024-03-04 15:55
@neolit123 In my opinion it would be nice to preserve some specs in the deployment/read them from the existing k8s deplyoment. It is really bad to hardcode mem limits like in coredns (170M) without an option to change it.
This caused an outage in our main prod cluster...DNS always has a big impact :D
This would happen again and again with every "kubeadm upgrade"

**Comment by neolit123** [comment] 2024-03-04 17:09
can we understand better what else can be preserved from the deployment and handle it all in a single pr?

**Comment by SataQiu** [comment] 2024-03-05 04:29
> that said we did add the feature to preserve the deployment replica count, so maybe we can also preserve other aspects of the existing deployment. but not such that would block the coredns migrator code (like "image" IIRC).

IMO, if we supported every feature(replica、resource、label、annotation ...) this way, it would make the code difficult to maintain. 
Perhaps we should support applying custom patches on addons in the v1beta4 API, even during the upgrade process.

**Comment by pacoxu** [comment] 2024-03-05 06:10
Can we support kube-proxy and coredns patches like control plane components patches in https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/#kubeadm-k8s-io-v1beta3-Patches?

**Comment by neolit123** [comment] 2024-03-05 07:36
> Can we support kube-proxy and coredns patches like control plane components patches in https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/#kubeadm-k8s-io-v1beta3-Patches?
> BTW, can we skip dns upgrade like etcd?

kube-proxy is a DS so it's controlled by a single config (which we create on init), arguably doesn't need patches.
the addons are skipped during upgrade if they are not found, we also have e2e for that. so users can use addons with different names today.

> IMO, if we supported every feature(replica、resource、label、annotation ...) this way, it would make the code difficult to maintain.
> Perhaps we should support applying custom patches on addons in the v1beta4 API, even during the upgrade process.

sadly our dns code is already a mess because of the coredns migration integration.
i was thinking that maybe a DeepCopy of the active Deployment + some edits will not be a lot of code.
generally agree that a patch might be cleaner and less code for us to own.

is "coredns" as a patch target OK, or should it be something like "corednsdeployment"?

@maxl99 
we are discussing allowing users to patch coredns instead of auto preserving options
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#patches

**Comment by neolit123** [comment] 2024-04-18 06:09
@SataQiu @pacoxu 

1.31 will open soon and i think i can try finding time for it.

> is "coredns" as a patch target OK, or should it be something like "corednsdeployment"?

best to be explicit about the object type `corednsdeployment`, because patches target a single object target and this leaves room if later we want to add e.g. `corednsservice`.

any concerns about adding this patch target?

**Comment by SataQiu** [comment] 2024-05-11 10:40
With https://github.com/kubernetes/kubernetes/pull/124820, you can configure coredns resource requirements in the following way:
```bash
$ mkdir patches
$ vim ./patches/corednsdeployment+strategic.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: coredns
        resources:
          limits:
            memory: 2Gi
            cpu: 2
          requests:
             memory: 1Gi
             cpu: 1
$ kubeadm upgrade apply <version> --patches ./patches
```

**Comment by neolit123** [comment] 2024-06-04 06:52
closing as completed. 1.31 has the new feature to patch corednsdeployment

**Closed by neolit123** 2024-06-04 06:52 UTC
Labels: priority/backlog, kind/feature, area/coredns
