### ISSUE TITLE
CoreDNS couldn't behave as expected until a restart of the pods

### ISSUE THREAD

**Issue by brightzheng100** [kubernetes/kubeadm#1731] opened 2019-08-18 14:11 UTC
# BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):

```
$ kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:20:51Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

- **Kubernetes version** (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

- **Cloud provider or hardware configuration**: 

GCP

- **OS** (e.g. from /etc/os-release): 

```
$ cat /proc/version
Linux version 4.15.0-1040-gcp (buildd@lgw01-amd64-044) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #42-Ubuntu SMP Wed Aug 7 15:17:54 UTC 2019
```

- **Kernel** (e.g. `uname -a`):

```
$ uname -a
Linux k8s-controller-0 4.15.0-1040-gcp #42-Ubuntu SMP Wed Aug 7 15:17:54 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

- **Others**:

I spun up my env by following my self-compiled doc [Kubernetes the Kubeadm Way](https://github.com/brightzheng100/kubernetes-the-kubeadm-way).
I didn't realize this issue before but this time I spun it up slightly differently with:
- 1 x controller: k8s-controller-0
- 3 workers: k8s-worker-0, k8s-worker-1, k8s-worker-2

## What happened?

**1. In PODs, I couldn't resolve any domains, including internal or external ones**

```
$ kubectl run --generator=run-pod/v1 tmp-shell --rm -i --tty --image nicolaka/netshoot -- /bin/bash
If you don't see a command prompt, try pressing enter.
bash-5.0# nc -vz 10.96.0.10 53
nc: connect to 10.96.0.10 port 53 (tcp) failed: Operation timed out
bash-5.0# dig kubernetes.default.svc.cluster.local

; <<>> DiG 9.14.1 <<>> kubernetes.default.svc.cluster.local
;; global options: +cmd
;; connection timed out; no servers could be reached
```

> So actually it's because in the POD it couldn't even reach out to CoreDNS' svc IP

**2. In any of worker nodes, I couldn't connect to CoreDNS but I could in controller node**

In any of my worker nodes:

```
$ nc -vz 10.96.0.10 53
nc: connect to 10.96.0.10 port 53 (tcp) failed: Connection timed out
```

But in controller node:

```
$ nc -vz 10.96.0.10 53
Connection to 10.96.0.10 53 port [tcp/domain] succeeded!
```

## What you expected to happen?

I expected things like: In any POD, I should be able to resolve internal and external domains (as there is upstream resolver set)

And I digged hard around for potential issues around CNI networking (as I'm using `Canal`), systemd service `systemd-resoved`, and of course `CoreDNS`, and this #1657 did give me some hints so I restarted my CoreDNS pods by:

```
kubectl -n kube-system rollout restart deployment coredns
```

Any interestingly, everything just worked like a charm!

Not sure what caused this and there might be a potential issue/bug/reason that I/we should take note of.

**Comment by neolit123** [comment] 2019-08-18 19:01
hello,

https://github.com/kubernetes/kubeadm/issues/1657 is not really a kubeadm bug.
the issue that the ticket talks about is that the coredns pods may schedule on the same node and if that node is gone the pods need to wait for the full eviction period, which is by design in k8s.

a solution is posted here, but we cannot add this to kubeadm:
https://github.com/kubernetes/kubeadm/issues/1657#issuecomment-517956048

the alternative is to always restart the coredns pods and make sure the land on multiple nodes.

> In PODs, I couldn't resolve any domains, including internal or external ones

i cannot reproduce this problem in the Katacoda k8s playground:
https://www.katacoda.com/courses/kubernetes/playground
where both the coredns pods landed on the worker node.

i also couldn't reproduce this on my setup where both the coredns pods landed on the control-plane node.

have you experimented with different CNI plugins, weavenet seems to work fine here..?

> kubectl -n kube-system rollout restart deployment coredns

if this command is fixing it for you i'd like to know if the coredns pods were failing and if there are error logs from them.

**Comment by neolit123** [comment] 2019-08-18 19:59
seems coredns/cni related.

i was able to reproduce your steps under (What happened?) with calico, but not using weavenet as the CNI plugin! i.e. `nc -vz 10.96.0.10 53` works fine from all nodes using weavenet!

given canal is using calico for routing i'd say this is probably a calico problem, yet the current version of coredns in kubeadm is a bit old (soon to be updated to 1.5.x, in 1.16 hopefully), so not sure if a coredns problem.

but again, this is not a kubeadm bug, please try investigating with the coredns or calico maintainers.
also see this:
https://github.com/kubernetes/kubernetes/issues/63900

if you have any suggestions for your TS guide, please send a PR for k/website and ping me:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/

thanks!

**Closed by neolit123** 2019-08-18 19:59 UTC
Labels: area/ecosystem, priority/awaiting-more-evidence

**Comment by brightzheng100** [comment] 2019-08-19 04:07
Thanks @neolit123 for such a prompt investigation!
I really appreciate that you have also pointed out that it was reproducible in `Canal`/`Calico`, which is super helpful for me!

Let me follow up accordingly with `Calico` team to see whether there is any defect that we can further fix.

But you gave an interesting hint here, which I also like, that `weavenet`'s solution might be more mature/stable/better in some way:)

**Comment by neolit123** [comment] 2019-08-19 10:32
> But you gave an interesting hint here, which I also like, that weavenet's solution might be more mature/stable/better in some way:)

all CNI plugins tend to have strengths and weaknesses.
