### ISSUE TITLE
apiServerCertSANs does not allow fqdn

### ISSUE THREAD

**Issue by usernkey** [kubernetes/kubeadm#827] opened 2018-05-17 09:17 UTC
BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):

kubeadm version: &version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

## What happened?

Trying to put the fqdn of the ELB in apiServerCertSANs I get

api-server-cert-altnames: Invalid value: "internal-marco-dev-MS-KmELB-1ULVNX18P9RW1-230864381.eu-west-1.elb.amazonaws.com": altname is not a valid dns label or ip address

## What you expected to happen?
Should be possible to use a fqdn.

## How to reproduce it (as minimally and precisely as possible)?

root@ip-10-1-16-19:~# cat /etc/kubernetes/k8sm.yaml
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: 10.1.16.19
etcd:
  endpoints:
  - https://10.1.17.10:2379
  - https://10.1.18.10:2379
  - https://10.1.16.10:2379
  caFile: /etc/kubernetes/pki/etcd/ca.pem
  certFile: /etc/kubernetes/pki/etcd/client.pem
  keyFile: /etc/kubernetes/pki/etcd/client-key.pem
networking:
  podSubnet: 10.244.0.0/16
apiServerCertSANs:
- internal-marco-dev-MS-KmELB-1ULVNX18P9RW1-230864381.eu-west-1.elb.amazonaws.com
apiServerExtraArgs:
  endpoint-reconciler-type: lease

root@ip-10-1-16-19:~# kubeadm init --config=/etc/kubernetes/k8sm.yaml
[init] Using Kubernetes version: v1.10.2
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks.
	[WARNING SystemVerification]: docker version is greater than the most recently validated version. Docker version: 18.03.1-ce. Max validated version: 17.03
	[WARNING FileExisting-crictl]: crictl not found in system path
Suggestion: go get github.com/kubernetes-incubator/cri-tools/cmd/crictl
api-server-cert-altnames: Invalid value: "internal-marco-dev-MS-KmELB-1ULVNX18P9RW1-230864381.eu-west-1.elb.amazonaws.com": altname is not a valid dns label or ip address

**Comment by luxas** [comment] 2018-05-17 09:51
Hmm, the problem is that your FQDN is using upper-case characters, which isn't a valid dns label by k8s validation. We _could_ always relax this constraint in kubeadm, but can you just set your FQDN to lowercase and try again?

**Comment by usernkey** [comment] 2018-05-17 09:52
Problem it is I can not. That name is generated by AWS.

**Comment by usernkey** [comment] 2018-05-17 10:06
I can use it in lower case as dns resolution doesn't care but I guess you will get this question more often as AWS generate ELB names with uppercase. Maybe be a more specific error message can be created.

**Comment by luxas** [comment] 2018-05-17 11:07
...or we could just lowercase the value before validation I guess.

**Comment by usernkey** [comment] 2018-05-17 14:54
Yes I confirm then writing the fqdn all in lowercase solve the issue.

I think then convert to lowercase before validation is the best solution.

**Comment by timothysc** [comment] 2018-06-01 21:11
/assign @liztio  

FYI , bugs can be fixed beyond code-freeze.

**Comment by chuckha** [comment] 2018-06-01 21:20
I think this could get kubeadm into a weird space, I'd be more inclined to surface a validation error that informs the user the apiServerCertSAN must be a valid DNS name and not try to guess what the user meant.

Lowercasing unicode points isn't strictly easy, but maybe go takes care of it for us?

**Comment by liztio** [comment] 2018-06-04 18:35
Lowercasing Unicode isn't easy, but we probably want punycode for non-ascii characters anyway. That makes this more straightforward.

**Comment by luxas** [comment] 2018-06-12 17:44
Fixed by https://github.com/kubernetes/kubernetes/pull/64718

**Closed by luxas** 2018-06-12 17:44 UTC
Labels: active, kind/bug, priority/important-soon
