### ISSUE TITLE
cni & k8s upgrade

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/kubeadm#1347] opened 2019-01-10 04:47 UTC
I upgraded my cluster and networking broke. I finally figured out kubelet no longer had the flag --network-plugin=cni. I added it to /etc/sysconfig/kubelet and everything started working again. I am thinking it probably belongs in /var/lib/kubelet/config.yaml  but it is unclear what the option should be.

**Comment by neolit123** [comment] 2019-01-10 07:55
please follow the issue template and specify your OS and upgrade versions.

`--network-plugin` is still available as a kubelet flag:
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

**Comment by kfox1111** [comment] 2019-01-10 16:47
My apologies. It was late at the end of a long outage.

I'm using centos7. I there were multiple upgrades involved so I don't remember all the details. there was a 1.9 to 1.10 upgrade as well as a 1.10 to 1.11.1 and then a 1.11.1 to 1.12.2.

I did temporarily fix it with the flag. that feels like it should belong in /var/lib/kubelet/config.yaml though, but I can't find any documentation on what that flag should be in the yaml, hence my question about it here. Can network plugin be specified in the kubelet config file?

**Comment by neolit123** [comment] 2019-01-11 10:45
> I did temporarily fix it with the flag

if you are using Docker, kubeadm will detect that and automatically write the flag `--network-plugin=cni` in a file: `/var/lib/kubelet/kubeadm-flags.env`
the flags in this file will then be used to invoke the kubelet as can be read here:
https://kubernetes.io/docs/setup/independent/kubelet-integration/#the-kubelet-drop-in-file-for-systemd

is this flag present for your -flags.env file?
i don't see how it can be removed by an upgrade.

> I can't find any documentation on what that flag should be in the yaml

i don't think this flag is supported in the KubeletConfiguration.

**Comment by kfox1111** [comment] 2019-01-11 16:59
hmm.... that file contains: KUBELET_KUBEADM_ARGS=--cgroup-driver=systemd --cni-bin-dir=/opt/cni/bin --cni-conf-dir=/etc/cni/net.d --network-plugin=cni

not sure why it wasn't used.

**Comment by neolit123** [comment] 2019-01-11 17:05
this file is should always used as long it's present in the unit file. so it's hard determine what the problem was.

i'm going to close this, but feel free to re-open once you have the exact steps for reproduction or more details.

thanks.

**Closed by neolit123** 2019-01-11 17:05 UTC
Labels: priority/awaiting-more-evidence

**Comment by adoerler** [comment] 2019-01-23 09:55
Hi kfox1111,

I've had the very same problem after upgrading Kubernetes 1.10.12 to 1.11.6 and than to 1.12.5 last weekend.

We are running on Ubuntu 16.04.

Until1.12.x the kubernetes upgrade documentation told us not using packagemanager like `apt` to update `kubeadm`, but rather do it with curl and replacing the file `/usr/bin/kubeadm`.

After I figured out, that the pod communication failed due to the lack of the CNI, I've researched the following:

Before 1.11 the file `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` (i.e. Systemd Unit for Kubelet, shipped by kubeadm package) looked like:
```
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"
Environment="KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true"
Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
Environment="KUBELET_DNS_ARGS=--cluster-dns=10.96.0.10 --cluster-domain=cluster.local"
Environment="KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt"
Environment="KUBELET_CADVISOR_ARGS=--cadvisor-port=0"
Environment="KUBELET_CERTIFICATE_ARGS=--rotate-certificates=true --cert-dir=/var/lib/kubelet/pki"
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_CADVISOR_ARGS $KUBELET_CERTIFICATE_ARGS $KUBELET_EXTRA_ARGS
```

here you can find the `cni` plugin within `KUBELET_NETWORK_ARGS`.

The new version of this file (i guess from 1.11, but definitily in 1.12) looks like:
```
# Note: This dropin only works with kubeadm and kubelet v1.11+
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"
Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml"
# This is a file that "kubeadm init" and "kubeadm join" generates at runtime, populating the KUBELET_KUBEADM_ARGS variable dynamically
EnvironmentFile=-/var/lib/kubelet/kubeadm-flags.env
# This is a file that the user can use for overrides of the kubelet args as a last resort. Preferably, the user should use
# the .NodeRegistration.KubeletExtraArgs object in the configuration files instead. KUBELET_EXTRA_ARGS should be sourced from this file.
EnvironmentFile=-/etc/default/kubelet
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS
```

Here is the `env` file included with `EnvironmentFile`.

So even if `kubeadm ` would update the `env` file, it will not be used for launching `kubelet` until one installs `kubeadm ` via package manager.

The next thing is, I do not know when exactly `kubeadm ` writes the env-file, as in my case it was never written, I had to update it manually on my clusters.

The commands used were:
* on master:
    ```bash
    sudo kubeadm upgrade plan v1.11.6
    sudo kubeadm upgrade apply v1.11.6
    ```

    and

    ```bash
    sudo kubeadm upgrade plan v1.12.5
    sudo kubeadm upgrade apply v1.12.5
    ```

* on nodes:

    ```bash
    sudo kubeadm upgrade node config --kubelet-version $(kubelet --version | cut -d ' ' -f 2)
    ```

It was(n't) fun finding the problem :-)

Best regards
Andreas

**Comment by kfox1111** [comment] 2019-01-23 16:37
Ah. interesting. thanks for the info.
