### ISSUE TITLE
Extract the kubeadm source code from the k8s as a separate repo?

### ISSUE THREAD

**Issue by JoshuaAndrew** [kubernetes/kubeadm#295] opened 2017-06-12 06:10 UTC
Hi All:
Extract the kubeadm source code from the k8s as a separate repository ?
any ideas?

**Comment by luxas** [comment] 2017-06-12 11:30
We've thought a lot about this and are planning to do it, however there's _a lot_ of very hard problems to solve (releasing, CI, API machinery, automation, godeps, ...)

So the plan is to let kubectl move to its own repo first, because that is an even bigger binary in terms of deps, complexity, support level (GA since v1.0.1), etc. and then kubeadm will follow in its footsteps.

We have an issue to track this in the main repo: https://github.com/kubernetes/kubernetes/issues/35314

@pipejakob is also a good person to talk to, please subscribe to the linked issue and attend our SIG meetings, soon-ish there should be an announcement with a link to a GDOC that describes how we're planning to do that migration.

Thank you for your issue!
If you are interested in helping to contribute to this effort, talk to me or @pipejakob on Slack and we'll might be able to coordinate it with you.

I'm closing this as a duplicate of https://github.com/kubernetes/kubernetes/issues/35314 to limit thread sprawl

**Closed by luxas** 2017-06-12 11:30 UTC
