### ISSUE TITLE
"kubeadm" does not support full chain in ca.crt

### ISSUE THREAD

**Issue by alwaysastudent** [kubernetes/kubeadm#2628] opened 2021-12-18 00:32 UTC
## What keywords did you search in kubeadm issues before filing this one?

"wanted exactly one certificate, got"

## Is this a BUG REPORT or FEATURE REQUEST?

**BUG REPORT**

## Versions

**kubeadm version** (use `kubeadm version`):

```
# kubeadm version
# ./kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.14", GitCommit:"57a3aa3f13699cf3db9c52d228c18db94fa81876", GitTreeState:"clean", BuildDate:"2021-12-15T14:51:22Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.18", GitCommit:"6f6ce59dc8fefde25a3ba0ef0047f4ec6662ef24", GitTreeState:"clean", BuildDate:"2021-04-15T03:31:30Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.18", GitCommit:"6f6ce59dc8fefde25a3ba0ef0047f4ec6662ef24", GitTreeState:"clean", BuildDate:"2021-04-15T03:23:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**: 
Not relying on any cloud providers. 

- **OS** (e.g. from /etc/os-release):
```
# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

- **Kernel** (e.g. `uname -a`):
```
Linux kernel 5.4.56
```

- **Others**:

## What happened?

This issue is a follow-up issue from https://github.com/kubernetes/kubeadm/issues/2618

We are in the middle of migrating existing kubeadm provisioned k8s PKI, on our cluster, to an external CA (pki).  And as a part of that we lay an intermediate CA on the filesystem, which has the full chain.

But one of the things that we noticed is when we perform kubeadm commands related to handling kubernetes certificates, it fails with this error which indicates that it doesn't like full chain

https://github.com/kubernetes/kubernetes/blob/v1.20.14/cmd/kubeadm/app/phases/certs/renewal/readwriter.go#L149

```
# kubeadm certs check-expiration  --v=7

I1217 21:31:25.171210 1318693 loader.go:379] Config loaded from file:  /etc/kubernetes/admin.conf
I1217 21:31:25.172054 1318693 cert_rotation.go:137] Starting client certificate rotation controller
[check-expiration] Reading configuration from the cluster...
[check-expiration] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
I1217 21:31:25.174964 1318693 round_trippers.go:422] GET https://k8s-master.mycompany.org:6443/api/v1/namespaces/kube-system/configmaps/kubeadm-config?timeout=10s
I1217 21:31:25.174984 1318693 round_trippers.go:429] Request Headers:
I1217 21:31:25.174995 1318693 round_trippers.go:433]     Accept: application/json, */*
I1217 21:31:25.175004 1318693 round_trippers.go:433]     User-Agent: kubeadm/v1.20.14 (linux/amd64) kubernetes/57a3aa3
I1217 21:31:25.187338 1318693 round_trippers.go:448] Response Status: 200 OK in 12 milliseconds
I1217 21:31:25.188554 1318693 round_trippers.go:422] GET https://k8s-master.mycompany.org:6443/api/v1/namespaces/kube-system/configmaps/kube-proxy?timeout=10s
I1217 21:31:25.188583 1318693 round_trippers.go:429] Request Headers:
I1217 21:31:25.188589 1318693 round_trippers.go:433]     Accept: application/json, */*
I1217 21:31:25.188594 1318693 round_trippers.go:433]     User-Agent: kubeadm/v1.20.14 (linux/amd64) kubernetes/57a3aa3
I1217 21:31:25.190974 1318693 round_trippers.go:448] Response Status: 200 OK in 2 milliseconds
I1217 21:31:25.192035 1318693 round_trippers.go:422] GET https://k8s-master.mycompany.org:6443/api/v1/namespaces/kube-system/configmaps/kubelet-config-1.18?timeout=10s
I1217 21:31:25.192050 1318693 round_trippers.go:429] Request Headers:
I1217 21:31:25.192056 1318693 round_trippers.go:433]     Accept: application/json, */*
I1217 21:31:25.192061 1318693 round_trippers.go:433]     User-Agent: kubeadm/v1.20.14 (linux/amd64) kubernetes/57a3aa3
I1217 21:31:25.194239 1318693 round_trippers.go:448] Response Status: 200 OK in 2 milliseconds
I1217 21:31:25.195557 1318693 loader.go:379] Config loaded from file:  /etc/kubernetes/kubelet.conf
I1217 21:31:25.195799 1318693 round_trippers.go:422] GET https://k8s-master.mycompany.org:6443/api/v1/nodes/n231-029-107?timeout=10s
I1217 21:31:25.195814 1318693 round_trippers.go:429] Request Headers:
I1217 21:31:25.195822 1318693 round_trippers.go:433]     User-Agent: kubeadm/v1.20.14 (linux/amd64) kubernetes/57a3aa3
I1217 21:31:25.195829 1318693 round_trippers.go:433]     Accept: application/json, */*
I1217 21:31:25.198132 1318693 round_trippers.go:448] Response Status: 200 OK in 2 milliseconds
I1217 21:31:25.199490 1318693 round_trippers.go:422] GET https://k8s-master.mycompany.org:6443/api/v1/namespaces/kube-system/pods?fieldSelector=spec.nodeName%3Dn231-029-107&labelSelector=component%3Dkube-apiserver%2Ctier%3Dcontrol-plane
I1217 21:31:25.199510 1318693 round_trippers.go:429] Request Headers:
I1217 21:31:25.199515 1318693 round_trippers.go:433]     Accept: application/json, */*
I1217 21:31:25.199520 1318693 round_trippers.go:433]     User-Agent: kubeadm/v1.20.14 (linux/amd64) kubernetes/57a3aa3
I1217 21:31:25.203507 1318693 round_trippers.go:448] Response Status: 200 OK in 3 milliseconds
[check-expiration] Error reading configuration from the Cluster. Falling back to default configuration

I1217 21:31:25.305491 1318693 interface.go:400] Looking for default routes with IPv4 addresses
I1217 21:31:25.305503 1318693 interface.go:405] Default route transits interface "eth0"
I1217 21:31:25.305657 1318693 interface.go:208] Interface eth0 is up
I1217 21:31:25.305709 1318693 interface.go:256] Interface "eth0" has 3 addresses :[10.231.29.107/21 fdbd:dc61:ff::231:29:107/128 fe80::f816:3eff:fe94:fc2b/64].
I1217 21:31:25.305726 1318693 interface.go:223] Checking addr  10.231.29.107/21.
I1217 21:31:25.305734 1318693 interface.go:230] IP found 10.231.29.107
I1217 21:31:25.305740 1318693 interface.go:262] Found valid IPv4 address 10.231.29.107 for interface "eth0".
I1217 21:31:25.305746 1318693 interface.go:411] Found active IP 10.231.29.107
I1217 21:31:25.309910 1318693 certs.go:506] validating certificate period for CA certificate
I1217 21:31:25.310233 1318693 certs.go:506] validating certificate period for API server certificate
I1217 21:31:25.310815 1318693 certs.go:506] validating certificate period for API server kubelet client certificate
I1217 21:31:25.311314 1318693 loader.go:379] Config loaded from file:  /etc/kubernetes/admin.conf
wanted exactly one certificate, got 4
k8s.io/kubernetes/cmd/kubeadm/app/phases/certs/renewal.(*kubeConfigReadWriter).Read
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/certs/renewal/readwriter.go:149
k8s.io/kubernetes/cmd/kubeadm/app/phases/certs/renewal.(*Manager).GetCertificateExpirationInfo
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/certs/renewal/manager.go:318
k8s.io/kubernetes/cmd/kubeadm/app/cmd/alpha.newCmdCertsExpiration.func1
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/alpha/certs.go:404
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:850
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
k8s.io/kubernetes/cmd/kubeadm/app.Run
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
        /usr/local/go/src/runtime/proc.go:204
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374
```

 
The full chain of certificates in the intermediate CA

```
# openssl crl2pkcs7 -nocrl -certfile /etc/kubernetes/pki/ca.crt | openssl pkcs7 -print_certs  -noout | grep "subject=" | wc -l

4

```

## What you expected to happen?

`kubeadm certs check-expiration` should emit output as expected with EXTERNALLY MANAGED, as yes 

It should honor full chain in the intermediate CA.crt

## How to reproduce it (as minimally and precisely as possible)?

Create a cluster with using kubeadm generated PKI and rotate the CA manually without the `apiserver.key`, `ca.key` and `etcd/ca.key` and issue all the required certs. Restart all the components gracefully to complete the migration. 

Execute the  `kubeadm certs check-expiration` to see the error.

## Anything else we need to know?

This is follow-up of issues related to https://github.com/kubernetes/kubeadm/issues/2618

**Comment by neolit123** [comment] 2021-12-18 00:57
kubeadm uses the same ca.crt for a number of things including flags in the kube-controller manager that only support a single certificate in the passed file. and this is by design.

see this note:
> Note: The files specified by the kube-controller-manager flags --client-ca-file and --cluster-signing-cert-file cannot be CA bundles. If these flags and --root-ca-file point to the same ca.crt file which is now a bundle (includes both old and new CA) you will face an error. To workaround this problem you can copy the new CA to a separate file and make the flags --client-ca-file and --cluster-signing-cert-file point to the copy. Once ca.crt is no longer a bundle you can restore the problem flags to point to ca.crt and delete the copy.

here:
https://kubernetes.io/docs/tasks/tls/manual-rotation-of-ca-certificates/

so to keep the UX simple for most users we have a single ca.crt with a single certificate, but in an ideal world there would be multiple files, where some can be full chains and some only include e.g. a single client CA.

we could remove the != 1 check in the expiration / renew code, but this becomes tricky in terms of:
- picking which certificate from a bundle to rotate / check the expiration of - is it the first one, we assume yes, but there is no standard for that AFAIK...
- passing a chain to components like the KCM, which will result in failures that will further confuse users.

i think your best option is to have scripts around the kubeadm commands to extract the relevant single certificate and keep the chain in a separate file.

**Comment by alwaysastudent** [comment] 2021-12-18 01:41
I think this is a poor experience, since if we have to make K8s CA an intermediate, we would anyway want to chain up to root to form the Chain of Trust. And the expiration check should be similar to how openssl way of getting the enddate

```
openssl x509 -enddate -noout -in ca.crt
```

**Comment by neolit123** [comment] 2021-12-18 05:15
> And the expiration check should be similar to how openssl way of getting the enddate

does it pick the enddate of the 0 index certificate if the .crt file is a bundle/chain?

> Also I don't think there is a restriction for full chain in kube-controller manager; I am able to successfully run the cluster with full chain of trust in the ca.crt and kube-controller manager is working correctly with the following options

this might have changed in a recent release and i did not know that it finally works...
as you can see the "rotate CA" docs are out of date.

the logic for "kubeadm certs" commands checking the certificate numbers and picking the 0 index cert in a bundle are here (for .crt files on disk):
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/certs/renewal/readwriter.go#L85-L89
and here (for certs in kubeconfig files):
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/certs/renewal/readwriter.go#L148-L151

we could remove the `!=1` checks in both places, but leave the [0] index pick.

**Comment by neolit123** [comment] 2021-12-18 05:21
did you check both flags?

> Note: The files specified by the kube-controller-manager flags --client-ca-file and --cluster-signing-cert-file cannot be CA bundles

> kube-controller-manager --allocate-node-cidrs=true --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf --bind-address=127.0.0.1 --client-ca-file=/etc/kubernetes/pki/ca.crt --cluster-cidr=192.168.0.0/16 --cluster-name=kubernetes --controllers=*,bootstrapsigner,tokencleaner --kubeconfig=/etc/kubernetes/controller-manager.conf --leader-elect=true --node-cidr-mask-size=24 --port=0 --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt --root-ca-file=/etc/kubernetes/pki/ca.crt --service-account-private-key-file=/etc/kubernetes/pki/sa.key --service-cluster-ip-range=10.96.0.0/12 --use-service-account-credentials=true

^ i don't see the `--cluster-signing-cert-file` flag above presumably because you are not letting the the KCM sign CSRs.
i think it would fail, because there is no spec / determinism when picking a signing certificate in a bundle.

it might have been fixed only for `--client-ca-file`.

**Comment by SataQiu** [comment] 2021-12-19 04:08
It looks like `--cluster-signing-cert-file` (kube-controller-manager CSRSigningController) cannot use CA bundles now:
https://github.com/kubernetes/kubernetes/blob/489fb9bee3f626b3eeb120a5af89ad8c2b2f1c20/pkg/controller/certificates/signer/ca_provider.go#L60-L62
```go
if len(certs) != 1 {
	return fmt.Errorf("error reading CA cert file %q: expected 1 certificate, found %d", p.caLoader.Name(), len(certs))
}
```

**Comment by neolit123** [comment] 2021-12-21 00:54
yet, as mentioned above the `cluster-signing*` flags are not included for the KCM if the ca.key is missing (external CA). i think we can allow the certificates files to have more than one certificate for `kubeadm certs ...renew/check-expiration` but if we are going to follow `openssl .. -enddate` we need to understand how it does that.

@alwaysastudent did you see my question above?

>> And the expiration check should be similar to how openssl way of getting the enddate

> does it pick the enddate of the 0 index certificate if the .crt file is a bundle/chain?

...or perhaps it does something like reporting the closes expiration date to "now".

**Comment by alwaysastudent** [comment] 2021-12-21 03:53
@neolit123 I am sorry, I was not able to reply earlier. 

Personally, we don't care about the KCM's signer or the k8s certificates API, since we use `jetstack/cert-manager`; But IMO, it should also support a full chain of trust as it can very well be an intermediate CA. 


And for your concern around which certificate to pick, I did some research and there indeed is a standard and you can safely pick the first certificate in the list.

> picking which certificate from a bundle to rotate/check the expiration of - is it the first one, we assume yes, but there is no standard for that AFAIK...
> does it pick the enddate of the 0 index certificate if the .crt file is a bundle/chain?



```
   certificate_list
      This is a sequence (chain) of X.509v3 certificates.  The sender's
      certificate must come first in the list.  Each following
      certificate must directly certify the one preceding it.  Because
      certificate validation requires that root keys be distributed
      independently, the self-signed certificate that specifies the root
      certificate authority may optionally be omitted from the chain,
      under the assumption that the remote end must already possess it
      in order to validate it in any case.

```


refer: https://www.rfc-editor.org/rfc/rfc4346#section-7.4.2

**Comment by neolit123** [comment] 2021-12-21 20:03
> And for your concern around which certificate to pick, I did some research and there indeed is a standard available, and based on that you can safely pick the first certificate in the list.

ok, thanks for the info and spec link.

**Comment by alwaysastudent** [comment] 2021-12-21 20:45
> > And for your concern around which certificate to pick, I did some research and there indeed is a standard available, and based on that you can safely pick the first certificate in the list.
> 
> ok, thanks for the info and spec link.

would it be a simple fix to be backported as well? like https://github.com/kubernetes/kubeadm/issues/2618

**Comment by neolit123** [comment] 2021-12-21 23:09
i would not object to the backport because it's command blocking for this use case.

**Comment by neolit123** [comment] 2022-01-04 20:43
PRs welcome for review in 1.24.

instructions:
> the logic for "kubeadm certs" commands checking the certificate numbers and picking the 0 index cert in a bundle are here (for .crt files on disk):
> https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/certs/renewal/readwriter.go#L85-L89
> and here (for certs in kubeconfig files):
> https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/certs/renewal/readwriter.go#L148-L151
> we could remove the !=1 checks in both places, but leave the [0] index pick.

/help

**Closed** 2022-01-06 03:08 UTC
Labels: help wanted, priority/backlog, area/pki
