### ISSUE TITLE
after join: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")

### ISSUE THREAD

**Issue by Dentrax** [kubernetes/kubeadm#2526] opened 2021-07-13 14:46 UTC
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT?

Unsure. Feel free to move this issue to discussions if neither a `bug` nor  kubeadm-related.

## Versions

**kubeadm version** (use `kubeadm version`):
```
kubeadm version: &version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:38:16Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment**:
- **Kubernetes version** (use `kubectl version`): `v1.21.2`
- **Cloud provider or hardware configuration**:  Self hosted VMs
- **OS** (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- **Kernel** (e.g. `uname -a`):
```
Linux k8s-foo-worker-4 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
- **Others**: `kubespray 2.16`

## What happened?

We couldn't communicate with kube-apiserver over HTTPS after `kubeadm join` process complete.

## What you expected to happen?

```
$ curl https://10.233.0.1:443/healthz --cacert /etc/kubernetes/pki/ca.crt
```

Since this already works `foo` worker nodes, this should also return `ok` in the newly joined `bar` worker node? 

## How to reproduce it (as minimally and precisely as possible)?

1. I provisioned two same Ubuntu 20 (5.8.0-50-generic) VMs, then created two different clusters using kubespray: `foo` and `baz`, for example.
2. `$ ssh root@foo  # SSH into master server of foo-master-1`
3. `$ kubeadm token create --print-join-command`
4. `ssh root@bar  # SSH into a worker node of bar: bar-worker-1`
5. `$ kubeadm reset  # reset first`
7. `$ kubeadm join $IP:6443 --token $TOKEN     --discovery-token-ca-cert-hash $CA_CERT_HASH`
8. `$ systemctl daemon-reload; systemctl restart kubelet`
9. `$ curl https://10.233.0.1:443/healthz --cacert /etc/kubernetes/pki/ca.crt`
See the SSL error:
```
curl: (60) SSL certificate problem: unable to get local issuer certificate
```

`$ curl https://10.233.0.1:443/healthz --insecure  $ OK`

But this request returns `ok` in the any of `foo` worker nodes.

Please note that the `ca.crt` located in the `bar-worker-1` is exactly the same  with `foo-worker-1`

10. Deploy a CNI, i.e. Flannel
11. `$ crictl logs 733e974b2bfa6  # kube-flannel container ID`
See the related error:

```
E0713 12:58:38.111224       1 main.go:243] Failed to create SubnetManager: error retrieving pod spec for 'kube-system/kube-flannel-d2b67': Get "https://10.233.0.1:443/api/v1/namespaces/kube-system/pods/kube-flannel-d2b67": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
```

Any ideas?

cc: @developer-guy @f9n

**Comment by neolit123** [comment] 2021-07-13 20:03
hello,

> Unsure. Feel free to move this issue to discussions if neither a bug nor kubeadm-related.

this seems like a request for support i cannot reproduce at e.g. Katacoda:
https://www.katacoda.com/courses/kubernetes/playground
...or locally with a new version cluster.

calling:
```
curl https://IP:PORT/healthz --cacert /etc/kubernetes/pki/ca.crt
```
from a worker returns `ok` as expected.

> curl: (60) SSL certificate problem: unable to get local issuer certificate

i have no explanation of the problem if you claim that the `ca.crt` is identical.
do you have multiple CAs in the kube-public/cluster-info config map?

> Deploy a CNI, i.e. Flannel

note that, the kubeadm team does not recommend flannel due to a number of user bug reports in the past, which may or many not have been resolved. we recommend Calico, WeaveNet, Cilium and consider them better maintained CNI.

i'm going to close this as we don't keep support tickets around, but feel free to continue the discussion here or ask on #kubeadm on k8s slack.

/kind support
/close

**Closed** 2021-07-13 20:03 UTC
Labels: kind/support

**Comment by Dentrax** [comment] 2021-07-14 08:32
Thanks for clarification @neolit123!

> side question: do you have multiple CAs in the kube-public/cluster-info config map?

Yes, I have multiple CAs in the `kube-public` namespace as the following:

```bash
$ kubectl get configmaps

NAME                 DATA   AGE
cluster-info         1      15d
istio-ca-root-cert   1      14d
kube-root-ca.crt     1      15d
```

**Comment by neolit123** [comment] 2021-07-14 13:32
kubeadm only uses those in cluster-info.

**Comment by Dentrax** [comment] 2021-07-14 13:38
I decoded the `cluster-info` _ConfigMap_ using `base64 -d -` and the output exactly same with`$ cat /etc/kubernetes/pki/ca.crt`.

**Comment by neolit123** [comment] 2021-07-14 14:08
Ok. I do not really know why this error is  happening. Normally it should
happen if the apiserver is not configured correctly. But only some of the
workers getting the status is odd.

**Comment by jamesdboone** [comment] 2021-08-12 16:57
For me this issue was a problem with my new k8s node not being able to pull down core k8s images.
A quick 'kubectl get po --all-namespaces' showed my calico and kube node pods getting stuck in imagepullbackoff.
Resolving these enabled things to start working as-expected, I was able to deploy pods to the new node.
