### ISSUE TITLE
Not showing Allocated Resources for Node

### ISSUE THREAD

**Issue by naisanza** [kubernetes/kubeadm#161] opened 2017-02-11 09:44 UTC
Referencing https://github.com/kubernetes/dashboard/issues/1628

The Pod Allocated resources are not updated in kubectl describe nodes, or in the Dashboard UI. It was speculated this could be related to the install process of kubernetes using kubeadm 

I'm running this installer here: https://github.com/TheShellLand/krazy88s/blob/master/scripts/kube-install.sh

![kubernetes dashboard](https://cloud.githubusercontent.com/assets/1614425/22826452/81fa7846-ef60-11e6-95df-617b4cd5d1d6.png)
![kubernetes dashboard2](https://cloud.githubusercontent.com/assets/1614425/22826457/850d7d30-ef60-11e6-8ff0-5bcb38526ebd.png)

**Comment by luxas** [comment] 2017-05-29 14:36
@naisanza Did you ever figure out the root cause of this?
Did it get fixed with v1.6?

**Comment by naisanza** [comment] 2017-05-29 19:03
@luxas : @maciaszczykm closed https://github.com/kubernetes/dashboard/issues/1628 and said it was a "cluster-related issue"

Is there a way to check where in the cluster code this was happening in?

**Comment by maciaszczykm** [comment] 2017-05-29 20:22
@naisanza Yes, I marked it as cluster-related issue, because zeros are displayed not only in the Dashboard but also in `kubectl describe node ...` output, that you have provided in https://github.com/kubernetes/dashboard/issues/1628.

In Dashboard we display info coming from cluster. Well, sometimes we calculate something, but always we are basing on data coming from the cluster. In this case Dashboard works as intended (same way as kubectl). Unfortunately I didn't found what causes the issue, as I am not able to reproduce it quickly.

**Closed** 2017-10-13 17:19 UTC
Labels: kind/support, priority/backlog, state/needs-more-information
