### ISSUE TITLE
1.7.0-beta.1 kubeadm master node setup fails because of non-existing "Initializers" admission-control

### ISSUE THREAD

**Issue by asac** [kubernetes/kubeadm#293] opened 2017-06-10 20:31 UTC
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT 

## Versions

# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-beta.1", GitCommit:"dfaba882698e26a47fb769be45fe5c048a9fe4ad", GitTreeState:"clean", BuildDate:"2017-06-08T01:43:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/arm"}

**Environment**:
- **Kubernetes version**:
```
# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-beta.1", GitCommit:"dfaba882698e26a47fb769be45fe5c048a9fe4ad", GitTreeState:"clean", BuildDate:"2017-06-08T01:43:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/arm"}
```
- **Cloud provider or hardware configuration**:
armhf C1 baremetal instances on scaleway.com

- **OS** (e.g. from /etc/os-release):
```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- **Kernel** (e.g. `uname -a`):
```
# uname -a
Linux 8bc81f5a-d92a-428f-b71c-0f31b3ce958f.pub.cloud.scaleway.com 4.9.20-std-1 #1 SMP Wed Apr 5 15:38:34 UTC 2017 armv7l armv7l armv7l GNU/Linux
```

## What happened?

kubeadm install fails because it doenst have the Initializers admission-control... once I remove just that entry the install finishes just fine... on nodes I dont have a problem.

I run kubeadm like:

```
/opt/kubernetes/server/bin/kubeadm init --token=$token --apiserver-advertise-address=$hostip --kubernetes-version=v1.7.0-alpha.2
```
note: alpha.2 because the beta containers where not available in gcr.io..

Maybe Initilaizers shoudl not be added for this setup? Let me know if you need more info or if i can test something for you.

Thanks for the great work!

**Comment by luxas** [comment] 2017-06-11 14:44
Many thanks for this bug report! Awesome catch!

I filed https://github.com/kubernetes/kubernetes/issues/47307 for that images for arm just exist up to alpha.2

This was a regression indeed, but I fixed it in https://github.com/kubernetes/kubernetes/pull/46879

So beta.2 will publish arm control plane images (by fixing https://github.com/kubernetes/kubernetes/issues/47307) and since https://github.com/kubernetes/kubernetes/pull/46879 is already included, things should work then... :smile:

**Comment by pipejakob** [comment] 2017-06-21 17:58
@asac Were you able to test using 1.7.0-beta.2 to see if this issue was resolved?

**Comment by asac** [comment] 2017-06-21 21:17
Hi,

unfortunately, I can't reset my cluster to scratch right now, but a quick try running kubeadm (to create master node) for arm on a test node shows that it now successfully finishes installs and kublet service can be started. Also, control panel components are available for the beta.2 version.

So, very nice and thanks for making kube!

**Comment by pipejakob** [comment] 2017-06-21 21:19
Fantastic. I'm going to close this for now, but feel free to reopen if future testing reveals this wasn't actually fixed.

**Closed by pipejakob** 2017-06-21 21:19 UTC
