### ISSUE TITLE
failed to pull image k8s.gcr.io/kube-apiserver:v1.22.4 failed to convert whiteout file \"usr/local/.wh..wh..opq\": operation not supported: unknown"

### ISSUE THREAD

**Issue by Trackhe** [kubernetes/kubeadm#2608] opened 2021-11-21 17:10 UTC
BUG REPORT

v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:47:19Z", GoVersion:"go1.16.10

**Environment**:
- **Kubernetes version** is not installed. because it fails while i pull the container.
- **Cloud provider or hardware configuration**: pxe bootet x86 and arm64 ubuntu server.
- **OS** Ubuntu 21.10 & Ubuntu 20.04.3 LTS
- **Kernel** 5.4.0-90-generic & 5.13.0-1010-raspi

## What happened?

i cant init my kubernetes with `sudo kubeadm init --config kubeadm.yaml` and i cant run `kubeadm config images pull`

```
failed to pull image "k8s.gcr.io/kube-apiserver:v1.22.4": output: time="2021-11-21T17:42:35+01:00" level=fatal msg="pulling image: rpc error: code = Unknown desc = failed to pull and unpack image \"k8s.gcr.io/kube-apiserver:v1.22.4\": failed to extract layer sha256:73ac8c719e66cdb24825a3c9b3e3e23a069a7a8e0067864d221362bb77f9aba6: failed to convert whiteout file \"usr/local/.wh..wh..opq\": operation not supported: unknown"
, error: exit status 1
To see the stack trace of this error execute with --v=5 or higher
```

## What you expected to happen?
No error.

#update 
probably related i m using nfs
https://github.com/containerd/containerd/issues/3762#issuecomment-922464270

**Comment by neolit123** [comment] 2021-11-22 14:07
This seems like a problem with the container runtime and not kubeadm.
Please provide CR version and crictl version details.

/kind support

**Comment by Trackhe** [comment] 2021-11-22 14:10
`containerd --version` = `github.com/containerd/containerd 1.5.5-0ubuntu3` on all machines.

`crictl version`=
```WARN[0000] runtime connect using default endpoints: [unix:///var/run/dockershim.sock unix:///run/containerd/containerd.sock unix:///run/crio/crio.sock]. As the default settings are now deprecated, you should set the endpoint instead. 
ERRO[0002] connect endpoint 'unix:///var/run/dockershim.sock', make sure you are running as root and the endpoint has been started: context deadline exceeded 
Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  1.5.5-0ubuntu3
RuntimeApiVersion:  v1alpha2```

**Comment by neolit123** [comment] 2021-11-22 14:20
Might be related to an outdated crictl version:
https://github.com/kubernetes/website/pull/30373

So you can try downloading the latest and trying again. If it still fails
you should report this to the containerd team.

**Comment by Trackhe** [comment] 2021-11-22 14:32
Done. I test it with version crictl 1.22 but exact same error. Thank you for your work and support. I going to create a ticket on containerd and close this ticket with the solution if i get.

**Comment by neolit123** [comment] 2021-11-22 17:02
closing this as it seems confirmed as a containerd issue here:
https://github.com/containerd/containerd/issues/6273

**Closed by neolit123** 2021-11-22 17:02 UTC
Labels: kind/support, area/external

**Comment by Trackhe** [comment] 2021-11-23 12:46
there is no solution. don't usw nfs with containerd is the answer from containerd 👌

**Comment by neolit123** [comment] 2021-11-23 13:13
You can check if cri-o supports it better.

**Comment by Trackhe** [comment] 2021-11-23 13:18
i do i had the same idea ^^

**Comment by Trackhe** [comment] 2021-12-21 21:11
My solution for now is to make an img, mount it, and configure the config root path to the mounted path.
That helped me:
https://www.redhat.com/sysadmin/rootless-podman-nfs

**Comment by netikras** [comment] 2022-08-17 11:44
This error is to be seen when containerd/CRI is using overlays, nfs and possibly other more limited filesystems, not supporting overlays extended attributes.

This is what I've captured in the container strace while trying to run a container on overlayfs:

```
setxattr("/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/16/fs/usr/local", "trusted.overlay.opaque", "y", 1, 0) = -1 EOPNOTSUPP (Not supported)
```

manpage for xattr: https://man7.org/linux/man-pages/man7/xattr.7.html

The fix is easy: don't use filesystems not supporting those attributes. 
Either create a ext2-filesystem-file (dd, mkfs) and loop-mount (mount -o loop) it right where you are, or mount an xattr-rich(er) filesystem from somewhere else for the CRI/containerd to use.

**Comment by wdsun1008** [comment] 2022-12-09 09:56
@netikras [overlayfs user-xattr](https://docs.kernel.org/filesystems/overlayfs.html#user-xattr) 
The "userxattr" mount option seems useful, but further testing and source code analysis is needed.

**Comment by trinitronx** [comment] 2026-02-07 00:30
> i really would love to see it running some day, because it makes a PXE cluster running better i think. Without the "mount -o loop" route.

Yes, it would be nice.  At least the path towards this is now known:

- `overlayfs` would need to use `user.*` NFSv4 extended attributes rather than `trusted.*` ones

For now, I've moved on to using iSCSI LUNs instead of NFS shares for `/var/lib/containerd` mounts.  So far, I have gotten it working with `btrfs` snapshotter and formatting the iSCSI block device as `btrfs` with subvolumes for `/var/lib/docker` and `/var/lib/containerd`.

Unfortunately there seems to be some performance drop when compared to my NFSv4.2 testing.  Maybe there are further optimizations and tuning options for iSCSI that could be done.

**Comment by Trackhe** [comment] 2026-02-07 08:58
is NVMe over TCP (NVMe/TCP) an option? @trinitronx

**Comment by trinitronx** [comment] 2026-02-07 09:36
> is NVMe over TCP (NVMe/TCP) an option? [@trinitronx](https://github.com/trinitronx)

It's a QNAP, so unfortunately it doesn't yet support NVMe-oF.  When asked about this recently, QNAP staff said:

> This feature is currently on our roadmap, but it is indeed not available yet. We plan to implement this functionality in the future.

I did a bit more testing with the `btrfs` performance tuning options.  It turns out that mounting with `nodatacow` greatly increased the speeds, as well as using an iSCSI LUN backed by the NVMe SSD storage pool.

I also found out that there is another mount option, `userxattr`, for `overlayfs` that could allow mounting over NFS. However, `containerd` would have to detect NFSv4 properly and use the `userxattr` option when mounting the layers.  It has [a function, `NeedsUserXAttr` here][1] that seems related to adding this mount option, but perhaps it's not being triggered properly on NFSv4 🤷 

>     Mount options for overlay
>     ...
> 
>       userxattr
>           Use the "user.overlay." xattr namespace instead of "trusted.overlay.". This is useful for unprivileged mounting of overlayfs.


[1]: https://github.com/containerd/containerd/blob/0fa51f54dfee239c606b837aaa8c8ae6b28a9c4a/snapshots/overlay/overlayutils/check.go#L91
