### ISSUE TITLE
kubeadm version 1.6.1 pull control plane version 1.6.0

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubeadm#233] opened 2017-04-10 14:02 UTC
```
> kubeadm version
kubeadm version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:33:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
> kubeadm init
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[init] Using Kubernetes version: v1.6.0
...
```

**Comment by buccella** [comment] 2017-04-21 23:06
Looks like a duplicate of #224

**Closed** 2017-05-29 14:00 UTC
