### ISSUE TITLE
kubeadm should not assume that hostname == nodename

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubeadm#64] opened 2016-11-22 23:14 UTC
_From @errordeveloper on September 28, 2016 9:20_

As pointed out by @justinsb, this is often the case on EC2.

_Copied from original issue: kubernetes/kubernetes#33641_

**Comment by mikedanese** [comment] 2016-11-22 23:14
_From @errordeveloper on September 29, 2016 8:4_

Just to illustrate this, the problem is about instance IDs vs hostnames.

**Comment by mikedanese** [comment] 2016-11-22 23:14
_From @pires on October 5, 2016 10:27_

Since #34031 is biting us here as well, we should have join flags for advertising a specific IP and/or hostname.

**Comment by mikedanese** [comment] 2016-11-22 23:14
_From @errordeveloper on October 5, 2016 20:32_

Yes, but we should also get better at determining the default.

**Comment by mikedanese** [comment] 2016-11-22 23:14
_From @pires on October 5, 2016 22:20_

I'm always cautious about adding magic stuff but I'm open to review it if anyone adds it.

**Comment by mikedanese** [comment] 2016-11-22 23:14
_From @zreigz on October 13, 2016 8:56_

@errordeveloper I've noticed when you want to create cluster using kubeadm and you have VMs with the same hostname then node is invisible when you type `kubectl get nodes` It is related to kubelet and requires to use `--hostname-override` flag to get rid off the problem. 
Anyone work on this ? I can take a look in `kubernetes/release` and try to fix it. What is your opinion?

**Comment by mikedanese** [comment] 2016-11-22 23:14
_From @zreigz on October 13, 2016 9:37_

I've prepared some proposal for it:
https://github.com/zreigz/release/commit/12a8c950117674498b84097002e9f99877027cf2

**Comment by mikedanese** [comment] 2016-11-22 23:14
_From @pires on October 13, 2016 10:13_

@zreigz I too have relied on the IP address, in the past. This seems to be a tricky one.

**Comment by mikedanese** [comment] 2016-11-22 23:14
_From @zreigz on October 13, 2016 10:38_

I've just made debian binaries and tested it. It seems to work

**Comment by mikedanese** [comment] 2016-11-22 23:14
_From @zreigz on October 13, 2016 11:16_

cc @luxas

**Comment by mikedanese** [comment] 2016-11-22 23:14
_From @luxas on October 15, 2016 7:50_

@justinsb @errordeveloper @pires What's the status of this issue?
Anything we can do easily and who should I assign it to?

**Comment by mikedanese** [comment] 2016-11-22 23:14
_From @pires on October 15, 2016 9:5_

@luxas you can assign it to me. Here's how my fix would look like:
* Add `--hostname-override <hostname_or_ip>` flag to `kubeadm join`
* When the flag above is set, run `kubelet`  with `--hostname-override <hostname_or_ip>`.

**Comment by pires** [comment] 2016-11-23 10:35
@luxas @errordeveloper changing `kubelet` flags means changing the `kubelet` systemd unit, right?
I was hoping for `kubelet` dynamic settings to land but I lost track of it. Thoughts?

**Comment by luxas** [comment] 2017-05-29 15:03
@justinsb could you explain a little more why this is the case in AWS?

**Comment by luxas** [comment] 2017-05-29 15:04
...and what we need to do more concretely for it to work

**Comment by justinsb** [comment] 2017-05-29 17:24
Absolutely: there is no reason to think that `hostname` should have anything to do with the Node metadata.name field :-)  There is now the option to put the hostname into the addresses if you want to.

For kubeadm: You need to take a parameter like `--node-name` to specify the node name, if you need it and can't derive it by other means (e.g. by comparing the node system ids or ip addresses).  We've used `--hostname-override` in the past, though that only adds to the confusion.

The root cause of the problem was that we _also_ assumed that node name was dns-resolvable from the master.  That's now fixed, but for the duration of the debate we _had_ to use a node name that was different from the host name, and now we're stuck with it.

It's nice though - on most clouds you are assigned a hostname, and the node name could be more useful.  On AWS it corresponds to the internal IP, so it isn't useless.

**Comment by justinsb** [comment] 2017-05-29 17:26
Oh - and we created a NodeName type, so whenever you're casting a string to NodeName or vice-versa, a little flag of alarm should go off.  Sadly there's no choice when first reading the Name from a Node, because of go's lack of generics, but that _should_ be the only place (?)

**Comment by luxas** [comment] 2017-07-05 10:10
The lack of this flag caused #330 which significantly bumps priority on this now that there's a very specific scenario (kubeadm on AWS nodes).

The solution here is as @justinsb just said, replace all `os.Hostname()` instaces in the code with a CLI flag parameter `--node-name`

**Comment by luxas** [comment] 2017-07-06 08:04
@GheRivero volunteered to work on this :tada:
I can't assign him, so therefore commenting instead...

**Comment by trung** [comment] 2017-07-07 17:27
In my EC2 Ubuntu instance, `hostname -f` reflects the same value as the AWS API returns.
```bash
$ hostname -f
ip-10-15-38-69.us-west-1.compute.internal
```
So i did
```bash
sudo hostname $(hostname -f) 
```
And it works.

**Closed** 2017-07-13 11:22 UTC
Labels: kind/enhancement, priority/important-soon

**Comment by ilponyy** [comment] 2017-07-16 04:03
The kubeadm join side is broken. The hostname preflight check fails always.
