### ISSUE TITLE
`kubeadm/kubernetes-xenial,now 1.8.15-00 amd64` depends on different kubernetes-cni verison than kubelet

### ISSUE THREAD

**Issue by mrIncompetent** [kubernetes/kubeadm#1039] opened 2018-08-07 11:19 UTC
## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.15", GitCommit:"c2bd642c70b3629223ea3b7db566a267a1e2d0df", GitTreeState:"clean", BuildDate:"2018-07-11T17:52:15Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- **Kernel** (e.g. `uname -a`):
```
Linux kubermatic-59mr6ghk9k-696ft 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- **Others**:

## What happened?
Installed kubeadm via the official apt repository: `deb http://apt.kubernetes.io/ kubernetes-xenial main`
```
apt-get install kubeadm=1.8.15-00
```

installed kubelet:
```
apt-get install kubelet=1.8.15-00
```
Fails with:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kubelet : Depends: kubernetes-cni (= 0.5.1) but 0.6.0-00 is to be installed
E: Unable to correct problems, you have held broken packages.
```
## What you expected to happen?
`kubeadm=1.8.15-00` depends on `kubernetes-cni (= 0.5.1)` and not `kubernetes-cni (>= 0.6.0)`

## How to reproduce it (as minimally and precisely as possible)?
Follow https://kubernetes.io/docs/setup/independent/install-kubeadm/
Specify kubeadm & kubelet version: `kubeadm=1.8.15-00 kubelet=1.8.15-00`

**Comment by neolit123** [comment] 2018-08-07 13:47
hi, @mrIncompetent 
the k8s version skew / support policy has the following:
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#supported-releases-and-component-skew

> Furthermore, we expect to "support" three minor releases at a time. "Support" means we expect users to be running that version in production, though we may not port fixes back before the latest minor version. 

1.8.x is no longer supported, while support for 1.9.x will soon drop once 1.12 is release.
any reason to be still using 1.8.x?

**Comment by mrIncompetent** [comment] 2018-08-07 14:01
@neolit123
I would be fine if dropping support means no updates for minor releases.

But using https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#supported-releases-and-component-skew as an excuse to release broken apt-packages is IMO not the right thing to do.

**Comment by neolit123** [comment] 2018-08-07 15:13
duplicate of:
https://github.com/kubernetes/kubernetes/issues/57334
possible workaround here:
https://github.com/kubernetes/kubernetes/issues/57334#issuecomment-356176515

> an excuse to release broken apt-packages is IMO not the right thing to do.

partially true and no idea why this bug exists, but from the maintainer's perspective you have to understand that this saves us time, time that we do not have because we are working on 1.12 and fixing issues in the support skew as well.

/close

**Closed by neolit123** 2018-08-07 15:13 UTC

**Comment by mrIncompetent** [comment] 2018-08-08 06:57
> duplicate of:
kubernetes/kubernetes#57334
possible workaround here:
kubernetes/kubernetes#57334 (comment)

No, it is not a duplicate. This issue here is about the conflicting dependencies; thus the mentioned workaround does not work.

**Kubeadm package**:
```
Package: kubeadm
Version: 1.8.14-00
Installed-Size: 133649
Maintainer: Kubernetes Authors <kubernetes-dev+release@googlegroups.com>
Architecture: amd64
Depends: kubelet (>= 1.6.0), kubectl (>= 1.6.0)
Description: Kubernetes Cluster Bootstrapping Tool
 The Kubernetes command line tool for bootstrapping a Kubernetes cluster.
Homepage: https://kubernetes.io
Filename: pool/kubeadm_1.8.14-00_amd64_8d7826f7c47edd4e1b2b535aa839ff9294ddbdbbc26aaae6439d3ebe1fcd7de5.deb
Priority: optional
SHA256: 8d7826f7c47edd4e1b2b535aa839ff9294ddbdbbc26aaae6439d3ebe1fcd7de5
Section: misc
Size: 18179342

Package: kubeadm
Version: 1.8.15-00
Installed-Size: 134427
Maintainer: Kubernetes Authors <kubernetes-dev+release@googlegroups.com>
Architecture: amd64
Depends: kubelet (>= 1.6.0), kubectl (>= 1.6.0), kubernetes-cni (>= 0.6.0), cri-tools (>= 1.11.0)
Description: Kubernetes Cluster Bootstrapping Tool
 The Kubernetes command line tool for bootstrapping a Kubernetes cluster.
Homepage: https://kubernetes.io
Filename: pool/kubeadm_1.8.15-00_amd64_9e4387b817f841a0a5ce067484e8464482336c43c14d673883791d2b73dd1401.deb
Priority: optional
SHA256: 9e4387b817f841a0a5ce067484e8464482336c43c14d673883791d2b73dd1401
Section: misc
Size: 18265582
```
**Kubelet package**
```
Package: kubelet
Version: 1.8.14-00
Installed-Size: 134991
Maintainer: Kubernetes Authors <kubernetes-dev+release@googlegroups.com>
Architecture: amd64
Depends: iptables (>= 1.4.21), kubernetes-cni (= 0.5.1), iproute2, socat, util-linux, mount, ebtables, ethtool, init-system-helpers (>= 1.18~)
Description: Kubernetes Node Agent
 The node agent of Kubernetes, the container cluster manager
Homepage: https://kubernetes.io
Filename: pool/kubelet_1.8.14-00_amd64_b5f96759cc1c51138474a66738a94482428d90a0b3e553505d7dafe251503993.deb
Priority: optional
SHA256: b5f96759cc1c51138474a66738a94482428d90a0b3e553505d7dafe251503993
Section: misc
Size: 19283054

Package: kubelet
Version: 1.8.15-00
Installed-Size: 135752
Maintainer: Kubernetes Authors <kubernetes-dev+release@googlegroups.com>
Architecture: amd64
Depends: iptables (>= 1.4.21), kubernetes-cni (= 0.5.1), iproute2, socat, util-linux, mount, ebtables, ethtool, init-system-helpers (>= 1.18~)
Description: Kubernetes Node Agent
 The node agent of Kubernetes, the container cluster manager
Homepage: https://kubernetes.io
Filename: pool/kubelet_1.8.15-00_amd64_dd4034732b629067c07cf989c642a7a612afd727fdb15b3a4fc9b3bb94c8122d.deb
Priority: optional
SHA256: dd4034732b629067c07cf989c642a7a612afd727fdb15b3a4fc9b3bb94c8122d
Section: misc
Size: 19354960
```

> partially true and no idea why this bug exists, but from the maintainer's perspective you have to understand that this saves us time, time that we do not have because we are working on 1.12 and fixing issues in the support skew as well.

If there would be a workaround for this issue - okay.
But kubeadm `v1.8.15` got released completely broken and unusable in this repository.

This Issue is related to https://github.com/kubernetes/kubeadm/issues/1038. Maybe it can be easily fixed together?
I'm happy to issue a PR you point me to the relevant code :)

**Comment by neolit123** [comment] 2018-08-08 15:08
i don't think there is an active 1.8.x branch manager to merge your PR for this old version.
an upgrade would be advised instead.
