### ISSUE TITLE
kubeadm doesn't add the correct user to kubelet.conf

### ISSUE THREAD

**Issue by jaxxstorm** [kubernetes/kubeadm#589] opened 2017-12-06 23:03 UTC
BUG REPORT

## Versions

**kubeadm version**: 1.8.4

**Environment**:
- **Kubernetes version** : 1.8.4
- **Cloud provider or hardware configuration**: ANY
- **OS** (e.g. from /etc/os-release): CentOS 7.3
- **Kernel** (e.g. `uname -a`): 3.10.0-514.16.1.el7.x86_64

## What happened?

I ran kubeadm join like so:

```
kubeadm join --token <token> <dns_name_name>:6443 --skip-preflight-checks --node-name ip-10-70-0-39.us-west-2.compute.internal
```

I ran into #411 first, but then I noticed once anonymous auth was turned on, I got kubelet errors saying it couldn't list the resources it needs to. The kubelet.conf in `/etc/kubernetes` looks like this:

```
users:
- name: kubelet-csr
  user:
    client-certificate-data: <base64 enc data>
    client-key-data: <base64 enc data>
```

This seems incorrect to me, and is causing the issues. If you check the cert generated by kubeadm, it's generated a node with the correct ou:

```
[root@ip-10-70-0-39 pki]# openssl x509 -in kubelet-client.crt -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            72:58:c5:5e:44:0e:0c:38:27:9e:53:8f:bc:60:92:52:5d:0b:9f:c9
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=kubernetes
        Validity
            Not Before: Dec  6 19:00:00 2017 GMT
            Not After : Dec  6 19:00:00 2018 GMT
        Subject: O=system:nodes, CN=system:node:ip-10-70-0-39.us-west-2.compute.internal
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:72:1a:ef:60:46:2f:82:71:c6:71:d5:8a:e0:50:
                    c4:60:e3:c9:b3:bb:8f:08:8e:28:fe:19:a8:82:06:
                    24:7e:15:26:22:d7:b0:0e:58:51:c8:9f:9e:26:91:
                    cc:c1:d2:2c:fc:c2:ad:72:8a:db:58:95:df:b2:a1:
                    58:55:be:d3:29
                ASN1 OID: prime256v1
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier:
                07:85:33:4E:C3:D7:84:D0:E1:3B:48:3D:6F:B3:4A:0D:91:B3:61:A0
    Signature Algorithm: sha256WithRSAEncryption
         <REDACTED>
<REDACTED>
```

I modified the user object to look like this:

## What you expected to happen?

I changed the kubelet.conf to look like this

```
users:
- name: system:node:ip-10-70-0-39.us-west-2.compute.internal
  user:
    client-certificate: /var/lib/kubelet/pki/kubelet-client.crt
    client-key: /var/lib/kubelet/pki/kubelet-client.key
```

And everything worked as expected, so I suspect that all that needs to happen is the kubeadm needs to generate the correct `kubelet.conf`

## How to reproduce it (as minimally and precisely as possible)?

The weird thing is, every time I've run `kubeadm join` it seems to generate something different. But in a nutshell:

- run `kubeadm join` on an cluster that has been `kubeadm init` created
- modify the `kube-apiserver.yaml` to enable `--anonymous-auth=false`
- restart kubelet
- observe errors
- fix the `kubelet.conf` as above

/cc @jpweber

**Comment by bart0sh** [comment] 2018-10-05 10:37
I faced another issue trying to reproduce this bug with kubeadm 1.12. I setup 2 nodes('master' and 'worker') cluster using kubeadm, added --anonymous-auth=false to the kube-apiserver.yaml and kubelet started producing errors like these on master:
```
Oct 05 11:37:13 master kubelet[3907]: E1005 11:37:13.263608    3907 reflector.go:134] object-"kube-system"/"kube-proxy-token-6pwh4": Failed to list *v1.Secret: secrets "kube-proxy-token-6pwh4" is forbidden: User "system:node:master" cannot list resource "secrets" in API group "" in the namespace "kube-system"

Oct 05 11:37:13 master kubelet[3907]: E1005 11:37:13.270164    3907 reflector.go:134] object-"kube-system"/"kube-proxy": Failed to list *v1.ConfigMap: configmaps "kube-proxy" is forbidden: User "system:node:master" cannot list resource "configmaps" in API group "" in the namespace "kube-system"

Oct 05 11:37:13 master kubelet[3907]: E1005 11:37:13.275853    3907 reflector.go:134] object-"kube-system"/"coredns-token-g7f9h": Failed to list *v1.Secret: secrets "coredns-token-g7f9h" is forbidden: User "system:node:master" cannot list resource "secrets" in API group "" in the namespace "kube-system"

Oct 05 11:37:13 master kubelet[3907]: E1005 11:37:13.278543    3907 reflector.go:134] object-"kube-system"/"coredns": Failed to list *v1.ConfigMap: configmaps "coredns" is forbidden: User "system:node:master" cannot list resource "configmaps" in API group "" in the namespace "kube-system"

Oct 05 11:37:13 master kubelet[3907]: E1005 11:37:13.295826    3907 reflector.go:134] object-"kube-system"/"weave-net-token-kg929": Failed to list *v1.Secret: secrets "weave-net-token-kg929" is forbidden: User "system:node:master" cannot list resource "secrets" in API group "" in the namespace "kube-system"
```

and similar messages on the worker node:
```
Oct 05 11:56:20 worker kubelet[28650]: E1005 11:56:20.172755   28650 reflector.go:134] object-"kube-system"/"weave-net-token-kg929": Failed to list *v1.Secret: secrets "weave-net-token-kg929" is forbidden: User "system:node:worker" cannot list resource "secrets" in API group "" in the namespace "kube-system"

Oct 05 11:56:20 worker kubelet[28650]: E1005 11:56:20.183005   28650 reflector.go:134] object-"kube-system"/"kube-proxy-token-6pwh4": Failed to list *v1.Secret: secrets "kube-proxy-token-6pwh4" is forbidden: User "system:node:worker" cannot list resource "secrets" in API group "" in the namespace "kube-system"

Oct 05 11:56:20 worker kubelet[28650]: E1005 11:56:20.192893   28650 reflector.go:134] object-"kube-system"/"kube-proxy": Failed to list *v1.ConfigMap: configmaps "kube-proxy" is forbidden: User "system:node:worker" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
```

I've also noticed that username is system:node:master in /etc/kubernetes/kubelet.conf on master, but on the worker node it's 'default-auth'. However, kubelet used correct username system:node:<host> on both nodes as can be seen in the above error messages.

These are my observations so far:
- kubelet uses correct user system:node:<host> to access api server. It takes it from user certificate CN and not using name from config for this purpose.
- disabling anonymous auth broke access to secrets and configmaps the same way on master and worker nodes

So, I couldn't reproduce this bug with kubeadm and kubelet 1.12, but discovered more severe one.

BTW, to reproduce broken access issue only master node is enough. As soon as api server starts with --anonymous-auth=false kubelet starts to put errors like above into its log.

@liggitt, @kad, @neolit123, @timothysc Any ideas?

**Comment by neolit123** [comment] 2018-10-11 13:56
hm, i guess this needs invetigation:
> disabling anonymous auth broke access to secrets and configmaps the same way on master and worker nodes

i can try reproducing later today or tomorrow, but i'm going to have limited time due to travelling.
what we can do about this issue is close it and log a new one if the others are OK with that?

**Comment by bart0sh** [comment] 2018-10-11 21:46
I'm ok with it.

**Comment by neolit123** [comment] 2018-10-15 11:52
ok, let's open a new one.

**Closed by neolit123** 2018-10-15 11:52 UTC
Labels: help wanted, kind/bug, priority/backlog
