### ISSUE TITLE
i am unable to get  all my pods in running state

### ISSUE THREAD

**Issue by MohanNagendraKumar** [kubernetes/kubeadm#1179] opened 2018-10-19 10:38 UTC
## Is this a request for help?

If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.

If no, delete this section and continue on.

## What keywords did you search in kubeadm issues before filing this one?

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

**Comment by MohanNagendraKumar** [comment] 2018-10-19 10:41
[root@cssosbe03-b02-master ~]# kubectl get pod --all-namespaces
NAMESPACE     NAME                                           READY   STATUS              RESTARTS   AGE
kube-system   coredns-576cbf47c7-562c9                       0/1     ContainerCreating   0          3d5h
kube-system   coredns-576cbf47c7-g659k                       0/1     ContainerCreating   0          3d5h
kube-system   etcd-cssosbe03-b02-master                      1/1     Running             10         3d4h
kube-system   kube-apiserver-cssosbe03-b02-master            1/1     Running             8          3d4h
kube-system   kube-controller-manager-cssosbe03-b02-master   1/1     Running             9          3d4h
kube-system   kube-flannel-ds-amd64-9fbxx                    0/1     CrashLoopBackOff    445        8d
kube-system   kube-flannel-ds-amd64-pr7ct                    0/1     CrashLoopBackOff    253        7d5h
kube-system   kube-proxy-2gg4t                               1/1     Running             7          8d
kube-system   kube-proxy-qtz2v                               1/1     Running             7          7d5h
kube-system   kube-scheduler-cssosbe03-b02-master            1/1     Running             9          3d4h

**Comment by neolit123** [comment] 2018-10-19 10:46
try weave instead of flannel as CNI plugin.
also please provide more details about your setup - k8s version, OS, architecture etc.
thanks.

/priority awaiting-more-evidence

**Comment by MohanNagendraKumar** [comment] 2018-10-19 10:55
[root@cssosbe03-b02-master ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

Kubernetes v1.12.1

**Comment by MohanNagendraKumar** [comment] 2018-10-19 11:02
Environment(kubectl version)
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Kernel :  (eg:uname -a)
Linux cssosbe03-b02-master 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by neolit123** [comment] 2018-10-19 11:07
what is your command line to install the flannel CNI?

also please try weavenet as already mentioned.
thanks.

**Comment by MohanNagendraKumar** [comment] 2018-10-19 11:11
kubectl apply -f 
 https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

**Comment by neolit123** [comment] 2018-10-19 12:39
what is the state of your pods after using:
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml

```
kubectl get pods -n kube-ssytem
```

also some questions:
- in the case of flannel did you pass -pod-network-cidr=10.244.0.0/16 to kubeadm?
- did you try weavenet.

**Comment by MohanNagendraKumar** [comment] 2018-10-19 12:43
after using 
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml

kube-system   coredns-576cbf47c7-7sxxp                       0/1     ContainerCreating   0          17m
kube-system   coredns-576cbf47c7-jgbxt                       0/1     ContainerCreating   0          17m
kube-system   etcd-cssosbe03-b02-master                      1/1     Running             0          16m
kube-system   kube-apiserver-cssosbe03-b02-master            1/1     Running             0          16m
kube-system   kube-controller-manager-cssosbe03-b02-master   1/1     Running             0          16m
kube-system   kube-flannel-ds-amd64-69q79                    0/1     CrashLoopBackOff    7          15m
kube-system   kube-flannel-ds-amd64-fznwk                    0/1     CrashLoopBackOff    7          14m
kube-system   kube-proxy-8b92q                               1/1     Running             0          17m
kube-system   kube-proxy-mxfvr                               1/1     Running             0          14m
kube-system   kube-scheduler-cssosbe03-b02-master            1/1     Running             0          16m



yes i passed pod-network-cidr=10.244.0.0/16 to kubeadm

**Comment by neolit123** [comment] 2018-10-19 12:46
i'm going to ask you again to try weavenet instead of flannel....

**Comment by MohanNagendraKumar** [comment] 2018-10-19 12:47
kk i will go with weave network

**Comment by kumarganesh2814** [comment] 2018-10-23 20:39
Hi,
I had similar Issue got it resolved by using weave network. Also one thing to keep in mind dont join the nodes untill coredns pods comes up. i.e. After Cluster creation immediately create network add on such weave. 
Best Regards
Ganesh Kumar

**Comment by neolit123** [comment] 2018-10-23 20:43
@kumarganesh2814 thanks for letting us know!
@MohanNagendraKumar did you resolve your issue?

**Closed** 2018-10-26 20:17 UTC
Labels: priority/awaiting-more-evidence

**Comment by fabiand** [comment] 2018-11-01 21:09
I encountered this as well, and I actually think this is some issue somewhere.

IIUIC then we have the following situation:

- coredns does not come up, because networking is not configured (will be done by flannel)
- flannel does not come up because it can't pull images, because DNS is broken

It turns out that kubeadm or some component changes iptables and DNS does not work afterwards anymore.

I saw this with kubeadm version 1.12.2

100% reproducer with kubeadm and flannel.

**Comment by fabiand** [comment] 2018-11-01 21:11
It's pretty much this configuration:

```
…

Chain KUBE-SERVICES (1 references)
    pkts      bytes target     prot opt in     out     source               destination         
       2      180 REJECT     udp  --  *      *       0.0.0.0/0            10.96.0.10           /* kube-system/kube-dns:dns has no endpoints */ udp dpt:53 reject-with icmp-port-unreachable
       0        0 REJECT     tcp  --  *      *       0.0.0.0/0            10.96.0.10           /* kube-system/kube-dns:dns-tcp has no endpoints */ tcp dpt:53 reject-with icmp-port-unreachable
       0        0 REJECT     tcp  --  *      *       0.0.0.0/0            10.108.159.44        /* kube-system/kubevirt-prometheus-metrics:metrics has no endpoints */ tcp dpt:443 reject-with icmp-port-unreachable
       0        0 REJECT     tcp  --  *      *       0.0.0.0/0            10.97.52.184         /* kube-system/virt-api: has no endpoints */ tcp dpt:443 reject-with icmp-port-unreachable
[centos@kubenode-cluster-0 ~]$ cat /etc/resolv.conf 
; generated by /usr/sbin/dhclient-script
search default.svc.cluster.local. svc.cluster.local. cluster.local.
nameserver 10.96.0.10
```

Thus `resolv.conf` points to 10.96.0.10, but the first rule in the KUBE-SERVICES chain is rejecting these requests.

**Comment by neolit123** [comment] 2018-11-01 21:15
@fabiand 
please try weavenet as CNI plugin, to eliminate the CNI plugin factor.

**Comment by fabiand** [comment] 2018-11-01 21:16
I was about to add this :)
I'm now trying weave - still I wonder why flannel shouldn't get fixed.

Is flannel getting deprecated?

**Comment by neolit123** [comment] 2018-11-01 21:17
it's just less maintained compared to weave.

**Comment by fabiand** [comment] 2018-11-01 21:20
It was so nice because so simple ... But understood. Maybe worth highlighting that in the docs?

**Comment by fabiand** [comment] 2018-11-01 21:30
So, I just finished, but have the same behavior, it looks like DNS requests are blocked by iptables, which prevents the weave image to be pulled.

I am not sure who does the iptables setup.

**Comment by fabiand** [comment] 2018-11-01 21:37
My flow is pretty much this:

```
# On centos7

KUBERNETES_VER=v1.11.4

PATH=$PATH:/usr/local/bin

# from https://kubernetes.io/docs/setup/independent/install-kubeadm/
yum install -y docker
systemctl enable docker && systemctl start docker

cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kube*
EOF

setenforce 0
yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
systemctl enable kubelet && systemctl start kubelet

cat <<EOF >  /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF
sysctl --system

kubeadm init --pod-network-cidr=10.244.0.0/16

mkdir -p ~/.kube
sudo cat /etc/kubernetes/admin.conf > ~/.kube/config

# Remove taints in order to allow setup on single master - and then scale up
sudo kubectl taint nodes --all node-role.kubernetes.io/master-
sudo kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml
## ALSO TRIED THIS WITH WEAVE
```

The result is as described abvoe https://github.com/kubernetes/kubeadm/issues/1179#issuecomment-435188800.

**Comment by fabiand** [comment] 2018-11-01 21:46
Using

```
$ sudo iptables -I OUTPUT -j ACCEPT
```

fixes the issue (which confirms that it's a firewall issue. I just don't know why.

**Comment by neolit123** [comment] 2018-11-01 21:48
not sure either.
you also try kubedns, to confirm it's not coredns specific (unlikely?)

**Comment by fabiand** [comment] 2018-11-01 21:49
I will.

So, one note, I see the following iptables comment (also in the past further above):
```
/* kube-system/kube-dns:dns has no endpoints */ udp dpt:53 reject-with icmp-port-unreachable
```

To me this (`dns has no endpoints`) is a hint that it might be a bug. The logic is: As there is no DNS endpoint, we block all incoming/outgoing DNS traffic.

Just a geuss tho.
