### ISSUE TITLE
--service-cidr option should set DNS server IP

### ISSUE THREAD

**Issue by bronger** [kubernetes/kubeadm#83] opened 2016-12-05 13:25 UTC
According to http://kubernetes.io/docs/admin/kubeadm/, if you pass the `--service-cidr` option, “you will also need to update the `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` file to reflect this change else DNS will not function correctly”.  Indeed, my tests show that the DNS server IP in that file must be within the given service network.

I think `kubeadm` should patch the configuration file and reload/restart the service if `--service-cidr` is given.  The current approach is awkward and error-prone.

**Comment by pires** [comment] 2017-01-10 12:41
@luxas another use case for templates?

**Comment by luxas** [comment] 2017-01-10 12:46
@pires This is not related to using go templates for the kube-dns deployment, it's about configuring kubelet flags IIUC

We are totally aware of this and that's one of the reasons kubeadm is in alpha.
We're not gonna start patching service files on the host, that's a total no-no and will be completely unmaintainable if we would go down that road.

Instead we want to use Kubelet Dynamic Settings #28 that can do this for us. The problem is that the feature isn't done in the core and we're stalled by that unless we build a custom controller that configures the controllers.

Please read about Kubelet Dynamic Settings so you see what it can and will do.
I'm closing this as a dupe of #28

**Closed by luxas** 2017-01-10 12:46 UTC
