### ISSUE TITLE
why is podSubnet in the config? It doesn't do anything.

### ISSUE THREAD

**Issue by cbharris** [kubernetes/kubeadm#2009] opened 2020-01-30 17:20 UTC
I'm on Ubuntu 18.04 with the latest everything. I'm trying to get a pod network installed and it fails in maddening ways. If I try using Calico  and put podSubnet: "192.168.0.0/16" in my config, it completely ignores this value and will assign whatever it chooses when I run kubeadm init. I find that "kubectl -n kube-system get nodes" will give me this value it chose and it will ignore whatever I put in the config. On the other hand, if I omit this from the config, the get nodes command simply does not have podSubnet set anywhere in the output. It really acts like this:

podSubnet in config => it chooses something you didn't enter
no podSubnet in config => chooses nothing

Did someone actually "design" this this way? In either case, it results in my cluster being DOA and it sure looks like a bug to me.

**Comment by neolit123** [comment] 2020-01-30 18:14
/triage support

> why is podSubnet in the config? It doesn't do anything.

this seems like a problem in your setup. podSubnet does work which is confirmed by our e2e tests, which happen to also use Calico.

- can you share your kubeadm config file and `kubeadm init` output?
- what are your kubeadm version and kubernetes version?

did you try different CNI plugins before calico?
try deleting `/etc/cni/net.d/`, which can contain residual configuration from a different plugin causing conflicts.

**Comment by cbharris** [comment] 2020-01-30 18:27
Thanks for the reply. It may be a issue with my setup as you say, but the behavior does seem exactly like what I describe. Also yes, I tried flannel (failed with endless crashloopbackoff or just sat in pending forever, switched to calico for this reason). I'm on AWS and using new nodes each time, so there isn't an issue with residual anything, every boot is 100% clean. Here is my kubeadm.config:

apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
networking:
  podSubnet: "192.168.0.0/16"
apiServer:
  extraArgs:
    cloud-provider: "aws"
    enable-bootstrap-token-auth: "true"
controllerManager:
  extraArgs:
    cloud-provider: "aws"
    configure-cloud-routes: "false"
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
bootstrapTokens:
  - token: "TOKEN"
    ttl: "24h"
    usages:
      - authentication
      - signing
certificateKey: "CERT_KEY"
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: "aws"
    cgroup-driver: "systemd"
    resolv-conf: "/run/systemd/resolve/resolv.conf"
localAPIEndpoint:
  advertiseAddress: "LOAD_BALANCER_DNS"
  bindPort: LOAD_BALANCER_PORT
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: "systemd"



Also, here is the output from kubeadm init:

[init] Using Kubernetes version: v1.17.2
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Generating "ca" certificate and key
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [ip-10-0-229-228.sa-east-1.compute.internal kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 10.0.229.228]
[certs] Generating "apiserver-kubelet-client" certificate and key
[certs] Generating "front-proxy-ca" certificate and key
[certs] Generating "front-proxy-client" certificate and key
[certs] Generating "etcd/ca" certificate and key
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [ip-10-0-229-228.sa-east-1.compute.internal localhost] and IPs [10.0.229.228 127.0.0.1 ::1]
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [ip-10-0-229-228.sa-east-1.compute.internal localhost] and IPs [10.0.229.228 127.0.0.1 ::1]
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
[certs] Generating "sa" key and public key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[apiclient] All control plane components are healthy after 17.502294 seconds
[upload-config] Storing the configuration used in ConfigMap "kubeadm-config" in the "kube-system" Namespace
[kubelet] Creating a ConfigMap "kubelet-config-1.17" in namespace kube-system with the configuration for the kubelets in the cluster
[upload-certs] Storing the certificates in Secret "kubeadm-certs" in the "kube-system" Namespace
[upload-certs] Using certificate key:
7481933a869e4574c1dee07ead81d744cb8b99dd96140c185192c874b036facc
[mark-control-plane] Marking the node ip-10-0-229-228.sa-east-1.compute.internal as control-plane by adding the label "node-role.kubernetes.io/master=''"
[mark-control-plane] Marking the node ip-10-0-229-228.sa-east-1.compute.internal as control-plane by adding the taints [node-role.kubernetes.io/master:NoSchedule]
[bootstrap-token] Using token: kl6ol7.f65kvz6j63gazlpq
[bootstrap-token] Configuring bootstrap tokens, cluster-info ConfigMap, RBAC Roles
[bootstrap-token] configured RBAC rules to allow Node Bootstrap tokens to post CSRs in order for nodes to get long term certificate credentials
[bootstrap-token] configured RBAC rules to allow the csrapprover controller automatically approve CSRs from a Node Bootstrap Token
[bootstrap-token] configured RBAC rules to allow certificate rotation for all node client certificates in the cluster
[bootstrap-token] Creating the "cluster-info" ConfigMap in the "kube-public" namespace
[kubelet-finalize] Updating "/etc/kubernetes/kubelet.conf" to point to a rotatable kubelet client certificate and key
[addons] Applied essential addon: CoreDNS
[addons] Applied essential addon: kube-proxy

Your Kubernetes control-plane has initialized successfully!

To start using your cluster, you need to run the following as a regular user:

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  https://kubernetes.io/docs/concepts/cluster-administration/addons/

Then you can join any number of worker nodes by running the following on each as root:

kubeadm join 10.0.229.228:6443 --token kl6ol7.f65kvz6j63gazlpq \
    --discovery-token-ca-cert-hash sha256:4992b5dbe4dac11876822fd38d8a2f0f22af99e70db7d3a9b71c9b7e62913261 


If I remove the lines: 

networking:
  podSubnet: "192.168.0.0/16"

from my kubeadm.config file, I simply don't get a podSubnet in the get nodes command, as described. If I leave it in there, I get this in the spec section:

"podCIDR": "192.168.0.0/24",
                "podCIDRs": [
                    "192.168.0.0/24"
                ],

Also, I tried doing cloud-provider=external as described here: https://github.com/kubernetes/cloud-provider-aws#readme but switched to setting this to aws as external seemed to do nothing and left my nodes in unscheduleable state. Many thanks for any sense you can make of this.

**Comment by neolit123** [comment] 2020-01-30 19:31
> cloud-provider: "aws"

please note that the kubeadm maintainers do not give support cloud provider setups, so you are on your own in terms of issues with the `--cloud-provider=aws` flag specifically, passed to the different components. if you find a bug related to that you must log a kubernetes/kubernetes repository issue.

> Also, my kubernetes and kubeadm are 1.17.0, I'm getting them from here: https://dl.k8s.io/v1.17.0/kubernetes-server-linux-amd64.tar.gz

the kubeadm output says that your are using 1.17.2?

> [init] Using Kubernetes version: v1.17.2

my recommendation is to download kubeadm and kubelet 1.17.2.
and ping the version in the ClusterConfiguration:
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.17.2
```

there were some CIDs bugs in the .0 and .1 releases.

> from my kubeadm.config file, I simply don't get a podSubnet in the get nodes command, as described. If I leave it in there, I get this in the spec section:

the kubeadm field podSubnet might be a bit misleading, because this is bound to the kube-controller-manager:

> --cluster-cidr string
>CIDR Range for Pods in cluster. Requires --allocate-node-cidrs to be true


kubeadm passes `192.168.0.0/16` directly to the kube-controller-manager as `--cluster-cidr`.
it also passes `-node-cidr-mask-size=24` and `--allocate-node-cidrs=true`, to it.

> --node-cidr-mask-size int32
> Mask size for node cidr in cluster. Default is 24 for IPv4 and 64 for IPv6.

so the important part here is that Node CIDR != Pod CIDR

the Node CIDR will be formed by `CLUSTER_CIDR_IP+NODE_CIDR_MASK_SIZE`.

if can pass `--node-cidr-mask-size` like so:
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.17.2
networking:
  podSubnet: "192.168.0.0/16"
controllerManager:
  extraArgs:
    "node-cidr-mask-size": "16"
```

in terms of do CNI plugins really need the `podSubnet`? yes, some claim to need it (e.g. Flannel, Calico, Cillium), some do not (WeaveNet). kubeadm allows you to configure this.

hope this gives some context.
i do not see a bug for kubeadm here, thus closing.

**Closed by neolit123** 2020-01-30 19:31 UTC
Labels: triage/support
