### ISSUE TITLE
How to monitor certificate expiration

### ISSUE THREAD

**Issue by wangycc** [kubernetes/kubeadm#2306] opened 2020-09-28 02:38 UTC
## Is this a request for help?
yes
## What keywords did you search in kubeadm issues before filing this one?
monitor cert

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`): v1.15.3

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.15.3
- **Cloud provider or hardware configuration**: 32C64G
- **OS** (e.g. from /etc/os-release): CentOS Linux release 7.6.1810 (Core)
- **Kernel** (e.g. `uname -a`): 4.19.8-1.el7.elrepo.x86_64
- **Others**:

## What happened?

The validity period of the certificate issued by kubeadm is only 1 year.I want to monitor the expiration time of all certificates through prometheus (including admin.conf/apiserver/apiserver-kubelet-client/controller-manager.conf, etc.) so that I can renew them in time before they expire

## What you expected to happen?

 I did not find any relevant monitoring indicators

**Comment by fabriziopandini** [comment] 2020-09-28 09:31
/triage support
@wangycc kubeadm implements the `kubeadm alpha certs check-expiration` command to help you in this task.

I don't have a valuable suggestion on how to make this info flow into Prometheus starting from the kubeadm CLI output, but this is an interesting use case for the kubeam operator we are currently discussing

**Comment by neolit123** [comment] 2020-09-28 10:22
To monitor the state from the cluster you can implement a container that
runs kubeadm with the above command and writes the data in a cluster
object. You can then read that data with any k8s client.

Hope that helps. Closing as not a bug / feature.

/close

**Closed** 2020-09-28 10:22 UTC
Labels: triage/support

**Comment by neolit123** [comment] 2020-09-28 10:24
But yes this seems like something the kubeadm operator can support. Please
find the issue "kubeadm operator" in this repo and add your use case there.
