### ISSUE TITLE
BUG REPORT: kubeadm upgrade apply fails when targeting the same version

### ISSUE THREAD

**Issue by maxime1907** [kubernetes/kubeadm#2823] opened 2023-02-13 17:12 UTC
## What keywords did you search in kubeadm issues before filing this one?

kubeadm upgrade apply same version

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): v1.25.6

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.25.6
- **Cloud provider or hardware configuration**: OpenStack (OVH Cloud) b2-60
- **OS** (e.g. from /etc/os-release): Flatcar Container Linux by Kinvolk v3374.2.3
- **Kernel** (e.g. `uname -a`): 5.15.86-flatcar
- **Container runtime (CRI)** (e.g. containerd, cri-o): containerd v1.6.16
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): Calico v3.24.5
- **Others**:

## What happened?

`kubeadm upgrade apply` with the same target version fails if there is a temporary file in the manifest folder located under `/etc/kubernetes/manifests`

## What you expected to happen?

Working as expected without waiting to timeout for a pod hash change that never happens.

## How to reproduce it (as minimally and precisely as possible)?

Edit `/etc/kubernetes/kubeadm-config.yaml` and add an entry under `controllerManager.extraArgs` (`allocate-node-cidrs: "true"` for example)
Make a manual backup (copy) of `/etc/kubernetes/manifests/kube-controller-manager.yaml` to `/etc/kubernetes/manifests/kube-controller-manager.yaml.bak`
Run this command:
```
timeout -k 600s 600s kubeadm upgrade apply -y v1.25.6 --certificate-renewal=true --config=/etc/kubernetes/kubeadm-config.yaml --ignore-preflight-errors=all --allow-experimental-upgrades --etcd-upgrade=false --force
```

## Anything else we need to know?

I have described how kubeadm handles the situation described in `How to reproduce it` by looking at the code:
1. It compares `/etc/kubernetes/manifests/kube-controller-manager.yaml` and `/etc/kubernetes/tmp/kubeadm-upgraded-manifests/kube-controller-manager.yaml`
2. Detects a change, so it moves `/etc/kubernetes/manifests/kube-controller-manager.yaml` to `/etc/kubernetes/tmp/kubeadm-backup-manifests` and moves `/etc/kubernetes/tmp/kubeadm-upgraded-manifests/kube-controller-manager.yaml` to `/etc/kubernetes/manifests/kube-controller-manager.yaml`
3. Then it waits for kubelet to restart the pod with the values of `/etc/kubernetes/manifests/kube-controller-manager.yaml`
4. Kubelet then proceeds to parse the manifests directory and updates the pod with `/etc/kubernetes/manifests/kube-controller-manager.yaml.bak` instead of `/etc/kubernetes/manifests/kube-controller-manager.yaml` because it parses this folder alphabetically with a simple glob `*`
4. Nothing has changed regarding pod specs and it keeps the same hash
5. kubeadm hangs until it times out after 5 minutes and fails

## Parts of the code involved
- https://github.com/kubernetes/kubernetes/blob/5d9d06aa4749ef9ad73f94fef0ef2e56719f9190/cmd/kubeadm/app/phases/upgrade/staticpods.go#L253
- https://github.com/kubernetes/kubernetes/blob/5d9d06aa4749ef9ad73f94fef0ef2e56719f9190/pkg/kubelet/config/file.go#L162

## Misc
I have opened a PR to fix this behavior in kubelet but i have been told to create an issue here instead:
- https://github.com/kubernetes/kubernetes/pull/115653

**Comment by chendave** [comment] 2023-02-14 09:11
The issue is not clearly described, AFAIK, kubeadm compare with the `/etc/kubernetes/tmp/kubeadm-upgraded-manifests` with `/etc/kubernetes/kube-controller-manager.yaml`, 

The path is not customizable, so I don't know how `/etc/kubernetes/kube-controller-manager.yaml` is involved in the upgrade.

Also, I don't know what's the `/etc/kubernetes/manifests/kube-controller-manager.yaml.bak` matters here, since the manifest is backed up to `/etc/kubernetes/tmp/kubeadm-backup-manifests` instead of the file as `/etc/kubernetes/manifests/kube-controller-manager.yaml.bak`.

Are you sure you are using kubeadm for cluster setup?

**Comment by maxime1907** [comment] 2023-02-14 09:59
> The issue is not clearly described, AFAIK, kubeadm compare with the `/etc/kubernetes/tmp/kubeadm-upgraded-manifests/kube-controller-manager.yaml` with `/etc/kubernetes/kube-controller-manager.yaml`,
> 
> The path is not customizable, so I don't know how `/etc/kubernetes/kube-controller-manager.yaml` is involved in the upgrade.
> 
> Also, I don't know what's the `/etc/kubernetes/manifests/kube-controller-manager.yaml.bak` matters here, since the manifest is backed up to `/etc/kubernetes/tmp/kubeadm-backup-manifests` dir instead of the file as `/etc/kubernetes/manifests/kube-controller-manager.yaml.bak`.
> 
> Are you sure you are using kubeadm for cluster setup?

Sorry if my issue was not well described, i have edited it to be as clear as possible this time! :slightly_smiling_face:

**Comment by chendave** [comment] 2023-02-14 10:16
much better! @maxime1907  thanks for the update.

so this is the culprit,

> Kubelet then proceeds to parse the manifests directory and updates the pod with /etc/kubernetes/manifests/kube-controller-manager.yaml.bak instead of /etc/kubernetes/manifests/kube-controller-manager.yaml because it parses this folder alphabetically with a simple glob *

I am not sure this is something that should be fixed in the kubeadm, since it's a common logic for how kubelet handle with the static pods.

pls note that kubeadm doesn't create the *.bak file. @liggitt 's comment to file an issue in this repo has the prerequisite that kubeadm create this *.bak file in the /etc/kubernetes/manifests directory, but this is not true.

Base on that, I don't think this could be addressed by kubeadm itself.

I checked the history discuss around this issue, and I agree this a technical debt, but the fix might break some potential users.

cc @pacoxu who involved in the early discussion, also cc approvers @neolit123 @SataQiu for awareness.

**Comment by liggitt** [comment] 2023-02-14 14:55
> @liggitt 's comment to file an issue in this repo has the prerequisite that kubeadm create this *.bak file in the /etc/kubernetes/manifests directory, but this is not true.

Right, I couldn't find any evidence of that either.

It's confusing that the steps to reproduce this issue include "Make a manual backup (copy) of /etc/kubernetes/manifests/kube-controller-manager.yaml to /etc/kubernetes/manifests/kube-controller-manager.yaml.bak"

That manual creation of a .bak file is the cause of the problem... not the `kubeadm upgrade apply` invocation

**Comment by SataQiu** [comment] 2023-02-16 10:18
Hi @maxime1907 Please DO NOT make a manual backup (copy) of `/etc/kubernetes/manifests/kube-controller-manager.yaml` to the same folder(`/etc/kubernetes/manifests`), you should back it up to a different folder.

/close

**Closed by SataQiu** 2023-02-16 10:18 UTC

**Comment by maxime1907** [comment] 2023-02-16 10:44
@SataQiu

Thanks for the answer, is this specified somewhere into the documentation?

**Comment by pacoxu** [comment] 2023-02-23 09:53
> It's confusing that the steps to reproduce this issue include "Make a manual backup (copy) of /etc/kubernetes/manifests/kube-controller-manager.yaml to /etc/kubernetes/manifests/kube-controller-manager.yaml.bak"

@liggitt we have met the problem before as well and I prefer to add some warning logs to kubelet so that users can easily be aware of this. Do you agree?

**Comment by liggitt** [comment] 2023-02-23 14:52
I don't think kubelet logs are very visible... cc @smarterclayton @bobbypage for ideas on surfacing problems with static pods in general (since they're looking at improving kubelet reactions to manifest misconfigurations like duplicate uids)

**Comment by SataQiu** [comment] 2023-02-23 15:06
> Thanks for the answer, is this specified somewhere into the documentation?

@maxime1907 

FYI: https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/#static-pod-creation
>Manifests are standard Pod definitions in JSON or YAML format in a specific directory. Use the staticPodPath: <the directory> field in the [kubelet configuration file](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/), which periodically scans the directory and creates/deletes static Pods as YAML/JSON files appear/disappear there. Note that the kubelet will ignore files starting with dots when scanning the specified directory.

**Comment by pacoxu** [comment] 2023-02-24 01:28
> I don't think kubelet logs are very visible

A warning event for the dup pod would be visible, but I am not sure if that is a valid event as it is from another manifest file.
