### ISSUE TITLE
New discovery flags do not allow for using pre-defined discovery token

### ISSUE THREAD

**Issue by dgoodwin** [kubernetes/kubeadm#95] opened 2016-12-19 19:45 UTC
As of https://github.com/kubernetes/kubernetes/pull/36462 the command to init a master is now: `kubeadm init --discovery token://` (probably will be assumed to be default soon)

To use a pre-defined token, I assumed something like:

kubeadm init --discovery token://4dd7dd.d2cf98cffb289dfa

However this appears to interpret  4dd7dd.d2cf98cffb289dfa as an address, which causes a token to be generated for you, and a very invalid command to be printed at the end of your init: `kubeadm join --discovery token://772a72:66d34c451b41bc22@4dd7dd.d2cf98cffb289dfa`

I believe we'll need to resort to custom parsing in this scenario, likely a regex watching for this exact scenario where there are no addresses, but there is a token.

Additionally looking at the PR above, it looks like due to the use of golang's URL library we include tokens with ID:SECRET rather than ID.SECRET as we have been using thus far. This would need to be rectified as we don't want users to have to flip a character when using this in their automation tooling. 

Thoughts on which direction we should go here? (':' vs '.')

CC @mikedanese @luxas

**Comment by pires** [comment] 2017-01-04 12:55
Is `kubeadm init --discovery token://4dd7dd.d2cf98cffb289dfa` even a valid command, given there's no host and optional port?

**Comment by pires** [comment] 2017-01-04 13:17
I believe the easiest path is to replace `.` in favor of `:` as token separator.

**Comment by pires** [comment] 2017-01-04 13:25
Ah, I get it now. The problem is as you describe, [Go URL parsing will not find a `@` character and so return the token as part of the `host` fragment](https://github.com/golang/go/blob/master/src/net/url/url.go#L540-L545).

**Comment by pires** [comment] 2017-01-04 14:11
It seems `:` is already used as token separator for the discovery part and the previous behavior that belonged to `--token` flag is gone. However, docs don't mirror that change, yet.

**Comment by luxas** [comment] 2017-01-04 14:13
This is bleeding edge you know :)
We're not done with the implementation either, and haven't decided on `.` vs `:`

**Comment by pires** [comment] 2017-01-04 14:14
luxas I have a fix in place for this but it will depend on that call being made.

**Comment by luxas** [comment] 2017-01-04 14:28
personally I don't think it matters, but I guess : is easier to implement, so we can go with that if @jbeda and @mikedanese agree

**Comment by pires** [comment] 2017-01-04 14:30
I'll open the PR to get the changes reviewed then.

**Comment by mikedanese** [comment] 2017-01-04 17:27
I very much disagree with moving off of a valid RFC 3986 URL. This is what I had envisioned in the original design. With this design:
```
kubeadm init --discovery token://4dd7dd:d2cf98cffb289dfa@
```
works which means for initialize the discovery service with user 4dd7dd and secret d2cf98cffb289dfa. This gives an intuitive join URL:
```
kubeadm init --discovery token://4dd7dd:d2cf98cffb289dfa@10.0.22.22
```

**Comment by pires** [comment] 2017-01-04 17:34
@mikedanese according to my analysis, Go `url.Parse` will not take `kubeadm init --discovery token://4dd7dd:d2cf98cffb289dfa` as the userinfo fragment of the URL but as host:port pair, since there's no `@` separator.

**Comment by mikedanese** [comment] 2017-01-04 17:39
@pires notice the @ at the end of my init URL.

**Comment by mikedanese** [comment] 2017-01-04 17:42
When we make these API changes, we need to consider consistency across kubeadm discovery methods, the rest of k8s, and the rest of the world. When a user who is unfamiliar with k8s looks at
```
token://4dd7dd:d2cf98cffb289dfa@10.0.22.22
```
the intent and parts are obvious if they've encountered URLs before. Connect to 10.0.22.22 as user 4dd7dd with secret d2cf98cffb289df speaking the token protocol.

**Comment by pires** [comment] 2017-01-04 17:43
@mikedanese I did notice it. But I also noticed the lack of such a thing in the description of the issue. I haven't seen anywhere in the code, impl or tests, that `@` presence is mandatory.

Other than that, I agree with using a URL :)

**Comment by dgoodwin** [comment] 2017-01-04 18:04
If an @ is all we need to get through the parsing when initializing a master with pre-generated token, then this sounds perfectly good to me. Also switching to :, though from the sounds of it you likely already took care of that Mike.

**Comment by dgoodwin** [comment] 2017-01-04 19:01
Works for me.

**Comment by pires** [comment] 2017-01-04 19:15
Works for me as well and I can change my PR to follow that behavior. @mikedanese, your call!

**Comment by mikedanese** [comment] 2017-01-04 19:45
@luxas I'm ok with that. Thanks.

**Comment by pires** [comment] 2017-01-04 21:11
PR updated. PTAL

**Comment by pires** [comment] 2017-01-05 09:53
Fixed and merged.

**Closed by pires** 2017-01-05 09:53 UTC
