### ISSUE TITLE
Can be more than just the latest kubeadm kept in the rpm repo?

### ISSUE THREAD

**Issue by rmohr** [kubernetes/kubeadm#220] opened 2017-04-03 09:31 UTC
Since kubeadm is still not a production ready tool, it would be great if we could go back to a kubeadm version which we know to work for us. When something like https://github.com/kubernetes/kubeadm/issues/212 happens, downgrading is very useful.

In [kubevirt](https://github.com/kubevirt/kubevirt), we use kubeadm, to deploy kubernetes on our vagrant development- and CI-environment and it works great. I like using the latest version, and so also help finding possible new issues, but having the possibility to downgrade until something blocking is resolved, would be cool.

As far as I have seen, the old versions are still on the storage, they are just not referenced anymore. Could that be? We are using the CentoOS repo mentioned in the [kubeadm getting started guide](https://kubernetes.io/docs/getting-started-guides/kubeadm/).

**Comment by fabiand** [comment] 2017-04-03 12:41
We used the following explicit verion urls to fall-back to the working version:
```
yum install -y http://yum.kubernetes.io/pool/082436e6e6cad1852864438b8f98ee6fa3b86b597554720b631876db39b8ef04-kubeadm-1.6.0-0.alpha.0.2074.a092d8e0f95f52.x86_64.rpm \
    http://yum.kubernetes.io/pool/2e63c1f9436c6413a4ea0f45145b97c6dbf55e9bb2a251adc38db1292bbd6ed1-kubelet-1.5.4-0.x86_64.rpm \
    http://yum.kubernetes.io/pool/fd9b1e2215cab6da7adc6e87e2710b91ecfda3b617edfe7e71c92277301a63ab-kubectl-1.5.4-0.x86_64.rpm \
    http://yum.kubernetes.io/pool/0c923b191423caccc65c550ef07ce61b97f991ad54785dab70dc07a5763f4222-kubernetes-cni-0.3.0.1-0.07a8a2.x86_64.rpm
```
(From https://github.com/kubevirt/kubevirt/pull/179)

If the yum repository had contained these old versions, then it would have been much more easy to fallback.

**Comment by jbeda** [comment] 2017-04-06 17:09
Dupe of https://github.com/kubernetes/release/issues/234.  Hard to keep old versions but i'm documenting instructions here: https://github.com/kubernetes/kubernetes.github.io/issues/3127

**Closed by jbeda** 2017-04-06 17:09 UTC
