### ISSUE TITLE
Error: Couldn't parse external etcd version -- TLS issue

### ISSUE THREAD

**Issue by JPGrieb** [kubernetes/kubeadm#867] opened 2018-05-29 13:31 UTC
## Is this a request for help?

Yes

## What keywords did you search in kubeadm issues before filing this one?

"couldn't parse external etcd version"

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version**

kubeadm version: 1.10.3

**Environment**:
- **Kubernetes version** 1.10.3
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release):

NAME="Amazon Linux"
VERSION="2 (2017.12)"

- **Kernel** (e.g. `uname -a`):
Linux 4.14.26-54.32.amzn2.x86_64 #1 SMP Tue Mar 27 21:50:30 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## What happened?

Ran the command: sudo kubeadm init --config=/etc/kubernetes/k8sconfig.yaml

Contents of the Config File
```
Version: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
 advertiseAddress: 0.0.0.0
etcd:
 endpoints:
 - https://etcdFqdn.tr-fr-nonprod.aws-int.thomsonreuters.com
 caFile: "/certificates/CertificateAuthority.pem"
 certFile: "/certificates/certificate.pem"
 keyFile: "/certificates/certificate.key"
apiServerCertSANs:
 - a205094-int-kubernetes-ci.tr-fr-nonprod.aws-int.thomsonreuters.com
 - a205094-kubernetes-ci.tr-fr-nonprod.aws-int.thomsonreuters.com
networking:
 podSubnet: 192.168.0.0/16
```
## What you expected to happen?

Kubernetes would successfully initialize

## How to reproduce it (as minimally and precisely as possible)?

[ec2-user@server ~]$ sudo kubeadm init --config=/etc/kubernetes/k8sconfig.yaml
[init] Using Kubernetes version: v1.10.3
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks.
	[WARNING SystemVerification]: docker version is greater than the most recently validated version. Docker version: 17.06.2-ce. Max validated version: 17.03
	[WARNING FileExisting-tc]: tc not found in system path
	[WARNING FileExisting-crictl]: crictl not found in system path
Suggestion: go get github.com/kubernetes-incubator/cri-tools/cmd/crictl
[preflight] Some fatal errors occurred:
	[ERROR ExternalEtcdVersion]: couldn't parse external etcd version "": Version string empty
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`

## Anything else we need to know?

Tried adding the CertificateAuthority.pem to OS trusted certificates
Tried with caFile but no certFile and keyFile
Tried with no caFile, certFile, and keyFile

I can request the version with curl using -k and using the -cacert parameter

**Comment by neolit123** [comment] 2018-05-29 14:04
@JPGrieb @timothysc 
(i was about to close it. :))

this is a duplicate of:
https://github.com/kubernetes/kubeadm/issues/719

a possible fix was pushed here:
https://github.com/kubernetes/kubernetes/pull/60585

and should be available in 1.11.
right now it should report something like `server responded with non-successful status: xxxxxxx`
this might get added in 1.10.4, but i cannot confirm that for now.

**Comment by stealthybox** [comment] 2018-05-29 18:00
@neolit123 it was cherry-picked in https://github.com/kubernetes/kubernetes/pull/64048

**Comment by chuckha** [comment] 2018-05-31 14:09
I ran into this issue and it was because I used the wrong certs (user error, I swapped the cert/key files in my config). I'm happy closing this one with that cherry pick/PR.

Double checking the correct use of certs this is what I found and it looks good to me:

https://github.com/kubernetes/kubernetes/blob/release-1.10/cmd/kubeadm/app/preflight/checks.go#L917

https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/preflight/checks.go#L923

Feel free to close if you agree @stealthybox or @neolit123

**Comment by neolit123** [comment] 2018-05-31 14:19
thanks for confirming, @chuckha !

**Closed by neolit123** 2018-05-31 14:19 UTC
Labels: kind/bug, priority/important-soon
