### ISSUE TITLE
kubeadm upgrade plan ignores gai.conf ipv4 precedence for downloading version txt

### ISSUE THREAD

**Issue by gattytto** [kubernetes/kubeadm#2650] opened 2022-02-05 19:46 UTC
I am installing kubernetes ipv6-only in nodes that only have ipv4 access to internet, so I set gai.conf settings in each node to always try ipv4 first. So far it has worked with everything (crictl pull, apt update/get, etc) except kubeadm which is setup using [this](https://github.com/gattytto/lxd_kube) instructions.

```verilog
root@enormous-gobbler:~/kubeinlxd# kubeadm upgrade plan
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
[preflight] Running pre-flight checks.
[upgrade] Running cluster health checks
[upgrade] Fetching available versions to upgrade to
[upgrade/versions] Cluster version: v1.23.3
[upgrade/versions] kubeadm version: v1.23.3
W0205 16:36:49.331976 1446698 version.go:103] could not fetch a Kubernetes version from the internet: unable to get URL "https://dl.k8s.io/release/stable.txt": Get "https://dl.k8s.io/release/stable.txt": dial tcp [2600:1901:0:26f3::]:443: connect: no route to host
W0205 16:36:49.332019 1446698 version.go:104] falling back to the local client version: v1.23.3
[upgrade/versions] Target version: v1.23.3
W0205 16:36:54.864227 1446698 version.go:103] could not fetch a Kubernetes version from the internet: unable to get URL "https://dl.k8s.io/release/stable-1.23.txt": Get "https://storage.googleapis.com/kubernetes-release/release/stable-1.23.txt": dial tcp [2800:3f0:4002:811::2010]:443: connect: no route to host
W0205 16:36:54.864249 1446698 version.go:104] falling back to the local client version: v1.23.3
[upgrade/versions] Latest version in the v1.23 series: v1.23.3

root@enormous-gobbler:~/kubeinlxd# wget https://storage.googleapis.com/kubernetes-release/release/stable-1.23.txt
--2022-02-05 16:43:22--  https://storage.googleapis.com/kubernetes-release/release/stable-1.23.txt
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.79.176, 172.217.173.144, 142.250.79.80, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.79.176|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7 [text/plain]
Saving to: ‘stable-1.23.txt.1’

stable-1.23.txt.1            100%[==============================================>]       7  --.-KB/s    in 0s

2022-02-05 16:43:23 (10.3 MB/s) - ‘stable-1.23.txt.1’ saved [7/7]

root@enormous-gobbler:~/kubeinlxd# kubectl get all -A
NAMESPACE     NAME                                           READY   STATUS    RESTARTS      AGE
kube-system   pod/calico-node-2dlnk                          1/1     Running   4             4d19h
kube-system   pod/calico-node-4l9k6                          1/1     Running   5             4d20h
kube-system   pod/coredns-64897985d-4cczj                    1/1     Running   5             4d20h
kube-system   pod/coredns-64897985d-tqvw9                    1/1     Running   5             4d20h
kube-system   pod/etcd-enormous-gobbler                      1/1     Running   6             4d20h
kube-system   pod/kube-apiserver-enormous-gobbler            1/1     Running   7 (31h ago)   4d20h
kube-system   pod/kube-controller-manager-enormous-gobbler   1/1     Running   7 (32h ago)   4d20h
kube-system   pod/kube-proxy-6bvvl                           1/1     Running   5             4d20h
kube-system   pod/kube-proxy-kdthz                           1/1     Running   4             4d19h
kube-system   pod/kube-scheduler-enormous-gobbler            1/1     Running   7 (32h ago)   4d20h

NAMESPACE     NAME                 TYPE        CLUSTER-IP        EXTERNAL-IP   PORT(S)                  AGE
default       service/kubernetes   ClusterIP   1101:300:1:2::1   <none>        443/TCP                  4d20h
kube-system   service/kube-dns     ClusterIP   1101:300:1:2::a   <none>        53/UDP,53/TCP,9153/TCP   4d20h

NAMESPACE     NAME                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
kube-system   daemonset.apps/calico-node   2         2         2       2            2           kubernetes.io/os=linux   4d20h
kube-system   daemonset.apps/kube-proxy    2         2         2       2            2           kubernetes.io/os=linux   4d20h

NAMESPACE     NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/coredns   2/2     2            2           4d20h

NAMESPACE     NAME                                DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/coredns-64897985d   2         2         2       4d20h

```

**Comment by SataQiu** [comment] 2022-02-06 09:42
@gattytto 
Emm... It looks like the domain name was resolved to an IPv6 address wrongly.
Can you paste the output of command `nslookup dl.k8s.io` ?

**Comment by neolit123** [comment] 2022-02-08 16:37
the kubeadm version getter code is here:
https://github.com/kubernetes/kubernetes/blob/f95c70080f21fe9aa6f14b72b75078d79ef68614/cmd/kubeadm/app/util/version.go#L187-L188

it sets these defaults:
https://github.com/kubernetes/kubernetes/blob/45f77ca4bab08da88bdda267be2157dc10bc64ac/staging/src/k8s.io/apimachinery/pkg/util/net/http.go#L110-L128

https://github.com/kubernetes/kubernetes/blob/45f77ca4bab08da88bdda267be2157dc10bc64ac/staging/src/k8s.io/apimachinery/pkg/util/net/http.go#L399

@gattytto 
could it be a problem related to *PROXY env var settings on your host?
are you setting them?

also try `go run test.go` of this small program on the same host:

```
package main

import (
	"fmt"
	"net/http"
)

func main() {
	client := &http.Client{}
	resp, err := client.Get("https://dl.k8s.io/release/stable.txt")
	if err != nil {
		fmt.Println("error", err)
	} else {
		fmt.Println("OK")
	}
}
```

>  So far it has worked with everything (crictl pull, apt update/get, etc)

i don't think any of these tools use the go HTTP client.

**Comment by gattytto** [comment] 2022-02-10 15:36
hello thank you for the responses here's some more logs from the master node ct:
```verilog
root@enormous-gobbler:~# resolvectl status
Global
       Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub

Link 2 (enp5s0)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 1.1.1.1
       DNS Servers: 1.1.1.1 2001:----:----:----::a
        DNS Domain: -------------

Link 3 (cali8d974766d23)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 4 (calid77fd8668d8)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
root@enormous-gobbler:~# nslookup dl.k8s.io
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
dl.k8s.io       canonical name = redirect.k8s.io.
Name:   redirect.k8s.io
Address: 34.107.204.206
Name:   redirect.k8s.io
Address: 2600:1901:0:26f3::

root@enormous-gobbler:~# resolvectl query dl.k8s.io
dl.k8s.io: 34.107.204.206                      -- link: enp5s0
           2600:1901:0:26f3::                  -- link: enp5s0
           (redirect.k8s.io)

-- Information acquired via protocol DNS in 3.2ms.
-- Data is authenticated: no; Data was acquired via local or encrypted transport: no
-- Data from: cache

root@enormous-gobbler:~# go run test.go
OK

```

**Comment by gattytto** [comment] 2022-02-10 17:07
```verilog
root@enormous-gobbler:~/test# go run test.go
OK: &{Status:200 OK StatusCode:200 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Accept-Ranges:[bytes] Alt-Svc:[h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"] Cache-Control:[private, max-age=0, no-transform] Content-Length:[7] Content-Type:[text/plain] Date:[Thu, 10 Feb 2022 17:06:40 GMT] Etag:["d8b1c9a61b737d61715fcb8c28495dab"] Expires:[Thu, 10 Feb 2022 17:06:40 GMT] Last-Modified:[Wed, 26 Jan 2022 00:03:36 GMT] Server:[UploadServer] X-Goog-Generation:[1643155416708153] X-Goog-Hash:[crc32c=owIR3g== md5=2LHJphtzfWFxX8uMKEldqw==] X-Goog-Metageneration:[1] X-Goog-Storage-Class:[STANDARD] X-Goog-Stored-Content-Encoding:[identity] X-Goog-Stored-Content-Length:[7] X-Guploader-Uploadid:[ADPycdsAaxbgoqQHkfd6ISe4VF4xg8AS6R4Bqv7YB-XNK9kF1hvtSxY3fzqBDB4GAPJdeqGGqpFDy8X3rBnDFYhDfNeDRAhiwQ]] Body:0xc000434120 ContentLength:7 TransferEncoding:[] Close:false Uncompressed:false Trailer:map[] Request:0xc000070500 TLS:0xc0000d04d0}

```

**Comment by gattytto** [comment] 2022-02-10 17:19
```json
root@enormous-gobbler:~/test# go run test.go
OK: &
{Status:200 OK StatusCode:200 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Accept-Ranges:[bytes] Alt-Svc:[h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"] Cache-Control:[private, max-age=0, no-transform] Content-Length:[7] Content-Type:[text/plain] Date:[Thu, 10 Feb 2022 17:06:40 GMT] Etag:["d8b1c9a61b737d61715fcb8c28495dab"] Expires:[Thu, 10 Feb 2022 17:06:40 GMT] Last-Modified:[Wed, 26 Jan 2022 00:03:36 GMT] Server:[UploadServer] X-Goog-Generation:[1643155416708153] X-Goog-Hash:[crc32c=owIR3g== md5=2LHJphtzfWFxX8uMKEldqw==] X-Goog-Metageneration:[1] X-Goog-Storage-Class:[STANDARD] X-Goog-Stored-Content-Encoding:[identity] X-Goog-Stored-Content-Length:[7] X-Guploader-Uploadid:[ADPycdsAaxbgoqQHkfd6ISe4VF4xg8AS6R4Bqv7YB-XNK9kF1hvtSxY3fzqBDB4GAPJdeqGGqpFDy8X3rBnDFYhDfNeDRAhiwQ]] Body:0xc000434120 ContentLength:7 TransferEncoding:[] Close:false Uncompressed:false Trailer:map[] Request:0xc000070500 TLS:0xc0000d04d0}

```

**Comment by neolit123** [comment] 2022-02-10 17:22
the latest example program replicates what kubeadm's `version.go` does, so not sure why your `kubeadm upgrade plan...` is different.

https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/version.go

you could try cloning the kuberentes repo, modifying the kubeadm `version.go` file, building kubeadm with `make all WHAT=/cmd/kubeadm` and test the binary that will be placed in the `_output` directory.

i have no explanation why this happens.

**Comment by gattytto** [comment] 2022-02-10 17:22
also no proxy settings and this is in the /etc/gai.conf line that I add to work around the precedence of v4:
```bash
precedence ::ffff:0:0/96  100
```

**Comment by gattytto** [comment] 2022-02-10 17:37
thank you @neolit123 I will compile with debug options, is this update check running in a pod/container? because I am using calico that only hands out v6 to the pods/ct's so it could also be that

**Comment by neolit123** [comment] 2022-02-10 17:46
> thank you @neolit123 I will compile with debug options, is this update check running in a pod/container? because I am using calico that only hands out v6 to the pods/ct's so it could also be that

i don't see how calico can affect this.

but this function possibly can?
https://github.com/kubernetes/kubernetes/blob/45f77ca4bab08da88bdda267be2157dc10bc64ac/staging/src/k8s.io/apimachinery/pkg/util/net/http.go#L399

it has some IP parsing:
https://github.com/kubernetes/kubernetes/blob/45f77ca4bab08da88bdda267be2157dc10bc64ac/staging/src/k8s.io/apimachinery/pkg/util/net/http.go#L420

perhaps some state is stored in memory and the IPv6 behavior only happens when `kubeadm ...` commands are called.

to check if that is the case modify version.go to have just:
`client := &http.Client{Timeout: timeout}`

**Comment by neolit123** [comment] 2022-02-23 16:07
closing due to no reply. please reopen once you have more details.
we don't have ways to reproduce this using the `gai.conf` in question.

**Closed by neolit123** 2022-02-23 16:07 UTC
Labels: kind/support, priority/awaiting-more-evidence

**Comment by gattytto** [comment] 2022-03-13 17:53
hello @neolit123 thank you for the support it seems that I needed some more touching to my gai.conf to make this work, I did and now it does work. 
my issue was related to running the nodes inside LXD vm's that have the host as their dns resolver. Then kubeadm was looking for an ipv6 endpoint response for the k8s domains, I fixed it by setting up a jools 4in6 forwarder and bind9 on the host.
