### ISSUE TITLE
kubeadm join/init  [WARNING IsDockerSystemdCheck] , when Use containerd.

### ISSUE THREAD

**Issue by oldthreefeng** [kubernetes/kubeadm#2374] opened 2021-01-06 15:29 UTC
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):
```
$ kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:57:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

```
- **Cloud provider or hardware configuration**: 4C4G , vmware.
- **OS** (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- **Kernel** (e.g. `uname -a`):
```
$uname -a
Linux k8s-dev 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- **Others**:

## What happened?

 kubeadm init --config=/root/kubeadm-config.yaml   ok 
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.60.136
  bindPort: 6443
nodeRegistration:
  criSocket: /run/containerd/containerd.sock
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.20.0
controlPlaneEndpoint: apiserver.cluster.local:6443
imageRepository: k8s.gcr.io
networking:
  # dnsDomain: cluster.local
  podSubnet: 100.64.0.0/10
  serviceSubnet: 10.96.0.0/12
apiServer:
  certSANs:
  - 127.0.0.1
  - apiserver.cluster.local
  - 192.168.60.136
  - 10.103.97.2
  extraArgs:
    feature-gates: TTLAfterFinished=true
  extraVolumes:
  - name: localtime
    hostPath: /etc/localtime
    mountPath: /etc/localtime
    readOnly: true
    pathType: File
controllerManager:
  extraArgs:
    feature-gates: TTLAfterFinished=true
    experimental-cluster-signing-duration: 876000h
  extraVolumes:
  - hostPath: /etc/localtime
    mountPath: /etc/localtime
    name: localtime
    readOnly: true
    pathType: File
scheduler:
  extraArgs:
    feature-gates: TTLAfterFinished=true
  extraVolumes:
  - hostPath: /etc/localtime
    mountPath: /etc/localtime
    name: localtime
    readOnly: true
    pathType: File
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs
ipvs:
  excludeCIDRs:
  - 10.103.97.2/32
```

case one 

then doing join node section.  it  will  check IsDockerSystemdCheck (docker is running),  containerd is running. 
```
$ kubeadm join 10.103.97.2:6443 --token ncjyh8.hs4e5rjeh14t8q46 --discovery-token-ca-cert-hash sha256:ea4060a0ab5f8926d973d030929f67d8ec5b5abfc784146288e3827c4c63b4f3 -v 0
[preflight] Running pre-flight checks
     [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
     [WARNING FileExisting-socat]: socat not found in system path
[preflight] Reading configuration from the cluster...
...
```

case two . 
then doing join node section.  do nothing about docker .(docker is installed and not running).  containerd is running

```
$  kubeadm join 10.103.97.2:6443 --token sygqgo.icvtrnn4s4h0y5rv --discovery-token-ca-cert-hash sha256:eb39d8bfc2900e15ef93793796a5349beab2fbf9852aeda6c435e653d5eefede -v 0
[preflight] Running pre-flight checks
     [WARNING FileExisting-socat]: socat not found in system path
[preflight] Reading configuration from the cluster...
```
then install success. any of two case get this output.   CONTAINER-RUNTIME is containerd://1.3.9
```
$ kubectl get nodes -owide
NAME        STATUS   ROLES                  AGE   VERSION   INTERNAL-IP      EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION           CONTAINER-RUNTIME
k8s-dev     Ready    control-plane,master   29m   v1.20.0   192.168.60.136   <none>        CentOS Linux 7 (Core)   3.10.0-1160.el7.x86_64   containerd://1.3.9
k8s-node1   Ready    <none>                 29m   v1.20.0   192.168.60.138   <none>        CentOS Linux 7 (Core)   3.10.0-1160.el7.x86_64   containerd://1.3.9
```

## What you expected to happen?
when use other cri do check itself ; when double cri exsits,  do not default check docker(even if docker is running or not ) .  cause1.22+ docker is depreciation 
xref:  https://github.com/kubernetes/kubernetes/pull/94624
docs:
https://kubernetes.io/blog/2020/12/02/dockershim-faq/
https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/

## How to reproduce it (as minimally and precisely as possible)?

its esay to reproduce . 
## Anything else we need to know?
none

**Comment by neolit123** [comment] 2021-01-06 15:35
duplicate of https://github.com/kubernetes/kubeadm/issues/2364

**Closed by neolit123** 2021-01-06 15:35 UTC

**Comment by neolit123** [comment] 2021-01-08 12:25
@oldthreefeng ok, so this issue, is not a duplicate of https://github.com/kubernetes/kubeadm/issues/2364

we have plans to remove the cgroupdriver detection completely for docker:
https://github.com/kubernetes/kubeadm/issues/874

for now you can just ignore the warning.

**Comment by oldthreefeng** [comment] 2021-01-08 14:24
@neolit123  ok. thanks alot
