### ISSUE TITLE
Kubeadm enables Initializer admission controller by default

### ISSUE THREAD

**Issue by Dirbaio** [kubernetes/kubeadm#629] opened 2017-12-27 22:59 UTC
When deploying a 1.9 cluster, kubeadm adds `Initializers` to `--admission-control` by default, but doesn't enable its corresponding API `admissionregistration.k8s.io/v1alpha1` in `--runtime-config`. See [docs](https://kubernetes.io/docs/admin/extensible-admission-controllers/#enable-initializers-alpha-feature)

This causes 404s to be spammed constantly in the request audit logs.

Also this is an alpha feature, shouldn't it be disabled by default?

**Comment by tamalsaha** [comment] 2017-12-27 23:09
Kube 1.9 release notes say that this api is now beta. https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.9.md#api-machinery-1

Isn't the beta api enabled by default ?

**Comment by Dirbaio** [comment] 2017-12-27 23:17
Oh, you're right, it's enabled at version `v1beta1`.

I thought it was alpha because I'm seeing this every 1-2 seconds in the audit logs every few seconds. Note it's requesting `v1alpha1`...

```json
{
  "kind": "Event",
  "apiVersion": "audit.k8s.io/v1beta1",
  "metadata": {
    "creationTimestamp": "2017-12-27T22:36:57Z"
  },
  "level": "Metadata",
  "timestamp": "2017-12-27T22:36:57Z",
  "auditID": "ff68e757-a4fc-4b10-aa11-f7d2c1013a7c",
  "stage": "ResponseComplete",
  "requestURI": "/apis/admissionregistration.k8s.io/v1alpha1/initializerconfigurations",
  "verb": "list",
  "user": {
    "username": "system:apiserver",
    "uid": "6e56197a-0ef6-4c81-adc1-c57948e05227",
    "groups": [
      "system:masters"
    ]
  },
  "sourceIPs": [
    "127.0.0.1"
  ],
  "objectRef": {
    "resource": "initializerconfigurations",
    "apiGroup": "admissionregistration.k8s.io",
    "apiVersion": "v1alpha1"
  },
  "responseStatus": {
    "kind": "Status",
    "apiVersion": "v1",
    "metadata": {},
    "status": "Failure",
    "message": "the server could not find the requested resource",
    "reason": "NotFound",
    "details": {},
    "code": 404
  },
  "requestReceivedTimestamp": "2017-12-27T22:36:57.557150Z",
  "stageTimestamp": "2017-12-27T22:36:57.557352Z"
}
```

There's nothing in the apiserver error logs. Maybe it's an apiserver bug?

**Comment by tamalsaha** [comment] 2017-12-27 23:21
Do you have old `v1alpha1` objects left in your cluster? These seem to be called by api server itself.

**Comment by Dirbaio** [comment] 2017-12-27 23:56
I don't have the v1alpha1 api enabled, and I just deployed this cluster with 1.9, I didn't upgrade it from earlier k8s versions.

How do I check if I have any? `kubectl get initializerconfigurations` fails:
```
the server doesn't have a resource type "initializerconfigurations"
```

**Comment by tamalsaha** [comment] 2017-12-27 23:59
Sorry, I am not sure what the problem is. I suppose you could enable the v1alpha1 version using runtimeconfig flag and check.

**Comment by Dirbaio** [comment] 2017-12-28 00:11
Okay, did that and yep, there are no InitializerConfigurations.

Also, a quick look at the code of the `Initializers` admission controller shows it's still using `admissionregistration/v1alpha1`:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/admission/plugin/initialization/initialization.go

That's why it's trying to hit the v1alpha1 urls probably?

**Comment by Dirbaio** [comment] 2017-12-28 00:15
Also I can confirm that's the cause of the 404s. When enabling the v1alpha1 API, the audit log shows 200s. So it seems the Initializers admission controller does still need the v1alpha1 api.

**Comment by tamalsaha** [comment] 2017-12-28 00:17
Seems like this line:
https://github.com/kubernetes/kubernetes/blob/925c127ec6b946659ad0fd596fa959be43f0cc05/staging/src/k8s.io/apiserver/pkg/admission/plugin/initialization/initialization.go#L100

Please file a bug in main Kubernetes repo. 

@caesarxuchao, can you please confirm and can this be [fixed in 1.9.1](https://groups.google.com/forum/#!topic/kubernetes-dev/GAB8dzapP2c)?

cc: @mbohlool

**Comment by Dirbaio** [comment] 2017-12-28 00:24
This is not a bug in k8s. 

The release notes you linked refer to `MutatingWebhookConfiguration` and `ValidatingWebhookConfiguration`, which are now beta. But `InitializerConfiguration` and the `Initializers` admission are still alpha.

**Comment by tamalsaha** [comment] 2017-12-28 00:56
You are right, @Dirbaio ! I missed that from the release notes. 
https://github.com/kubernetes/api/commit/365ff2245a1fb7561d5a4f9e9a8eb21341c07b83

@luxas , it seems that the [default admission controller list](https://github.com/kubernetes/kubernetes/blob/v1.9.0/cmd/kubeadm/app/phases/controlplane/manifests.go#L47) does not match the ones in [documentation ](https://kubernetes.io/docs/admin/admission-controllers/#is-there-a-recommended-set-of-admission-controllers-to-use) . Is this intentional?

**Comment by tamalsaha** [comment] 2018-01-04 16:52
Files a separate issue for Webhooks https://github.com/kubernetes/kubeadm/issues/642

**Closed** 2018-01-18 07:50 UTC
