### ISSUE TITLE
kubeadm needs a setting to specify the livenessProbe: initialDelaySeconds timeout for slow masters

### ISSUE THREAD

**Issue by ghoben** [kubernetes/kubeadm#931] opened 2018-06-17 21:23 UTC
## What keywords did you search in kubeadm issues before filing this one?
livenessprobe, kubeadm,

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: FEATURE REQUEST

I was trying to setup a kubernetes master on a RaspberryPI 3. After completing the low fruit hurdle like cgroup settings, swap off, etc I was still failing with cryptic errors of not beeing able to connect to the apis-server due to TLS timeouts. Observing the logs of the apiserver I saw that it was always failing to sync and was shut down. It turned out that the health (livenessProbe timeout) was kicking in way to early. After increasing the manual initialDelaySeconds, the master was able to startup with no issues. This costed me many hours of investigation until I found out that this is simple. 

It would totally be helpful to consider the fact of the initialDelaySeconds timeout for the api-server on not powerful devices to be specified via kubeadm init. If that's not possible it would be great if we can somehow give the healtz check more timeout per default to complete. At least for the api-server

## Versions

**kubeadm version** (use `kubeadm version`):

kubeadm version: &version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/arm"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/arm"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/arm"}

- **Cloud provider or hardware configuration**: Raspberry PI 3
- **OS** (e.g. from /etc/os-release):
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
HYPRIOT_OS="HypriotOS/armhf"
HYPRIOT_OS_VERSION="v2.0.1"
HYPRIOT_DEVICE="Raspberry Pi"
HYPRIOT_IMAGE_VERSION="v1.9.0"
- **Kernel** (e.g. `uname -a`):
Linux gernot-xxx-white 4.14.34-hypriotos-v7+ #1 SMP Sun Apr 22 14:57:31 UTC 2018 armv7l GNU/Linux
- **Others**:

## Anything else we need to know?
Changing the livenessProbe: initialDelaySeconds to 60s give the raspberry PI a chance to startup.

**Comment by neolit123** [comment] 2018-06-18 16:50
duplicate of https://github.com/kubernetes/kubeadm/issues/413

**Closed by neolit123** 2018-06-18 16:50 UTC
