### ISSUE TITLE
Pods are not getting cleaned in CRI-O after running kubeadm reset.

### ISSUE THREAD

**Issue by yadavkkumar** [kubernetes/kubeadm#932] opened 2018-06-18 10:14 UTC
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## What happened?
Kubeadm is not able to remove CRI-O pods after running `kubeadm reset`. 
```
[reset] Cleaning up running containers using crictl with socket /var/run/dockershim.sock
[reset] Failed to list running pods using crictl. Trying using docker instead.
```

## What you expected to happen?
Kubeadm reset command should remove all the pods running in CRI-O.

## Versions

**kubeadm version** (use `kubeadm version`):
```
kubeadm version: &version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- **Kernel** (e.g. `uname -a`):
```
Linux tcs07 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 6_64 x86_64 GNU/Linux
```

- **Others**:
```
crictl version
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.11.0-dev
RuntimeApiVersion:  v1alpha1
```

## How to reproduce it (as minimally and precisely as possible)?
Follow the documentation to use [CRI-O](https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#enable-full-debug) and kubeadm 1.10 
After that run `kubectl reset` 

## Anything else we need to know?
Manually deleting the pods using command `crictl stopp` and `crictl rmp`  throws the following error as the containers doesn't exist for the respective pods.
```
FATA[0003] removing the pod sandbox "0e92bc6230132" failed: rpc error: code = Unknown desc = failed to delete container k8s_sidecar_kube-dns-86f4d74b45-m8j65_kube-system_2ee9d374-72bf-11e8-9f37-8851fb5bd321_0 in pod sandbox 0e92bc6230132e219cf6281cc83bb9a64bbeb509f5453664f04c3f2d21eaf7c1: `/usr/bin/kata-runtime delete --force 00affa7ac08dc095d33eb5dcea82d524eb8e6615cf5f1129bfc333bf1674b6f2` failed: Container ID (00affa7ac08dc095d33eb5dcea82d524eb8e6615cf5f1129bfc333bf1674b6f2) does not exist
```
`crictl pods` shows the state `NotReady` for the pods. And there are no running containers in CRI-O 
 
Output of `crictl pods`
```
POD ID              CREATED             STATE               NAME                              NAMESPACE           ATTEMPT
809ccd63d3077       2 minutes ago       Ready               kube-controller-manager-tcs07     kube-system         1
424c3c84018fe       2 minutes ago       Ready               kube-apiserver-tcs07              kube-system         1
a20d407419f27       2 minutes ago       Ready               etcd-tcs07                        kube-system         1
d1a74574fcee6       2 minutes ago       Ready               kube-scheduler-tcs07              kube-system         1
0e92bc6230132       3 hours ago         NotReady            kube-dns-86f4d74b45-m8j65         kube-system         0
c4f5206f13167       3 hours ago         NotReady            weave-net-9btcs                   kube-system         0
ad7e3b1294842       3 hours ago         NotReady            kube-proxy-jcx8f                  kube-system         0
0919b6c873299       3 hours ago         NotReady            etcd-tcs07                        kube-system         0
0d7e3244dc47d       3 hours ago         NotReady            kube-controller-manager-tcs07     kube-system         0
3e9fd59293f25       3 hours ago         NotReady            kube-scheduler-tcs07              kube-system         0
e65d6434816a6       4 days ago          NotReady            kube-dns-86f4d74b45-fl2wv         kube-system         0
b5c5a6a528b66       4 days ago          NotReady            php-apache-8699449574-sjqht       default             2
5b21bedec56c3       4 days ago          NotReady            php-apache-8699449574-sjqht       default             0
7ad55bd09c86e       4 days ago          NotReady            php-apache-8699449574-l7bt2       default             0
5e8e20d630fee       4 days ago          NotReady            metrics-server-6fbfb84cdd-6nf7z   kube-system         0
cf979e1d7130a       5 days ago          NotReady            kube-dns-86f4d74b45-5mfj6         kube-system         0
```
Sometimes there are same set of pods running like two `kube-dns` pods running and showing the status `Ready` at the same time

**Comment by bart0sh** [comment] 2018-06-18 10:45
> /usr/bin/kata-runtime delete --force 00affa7ac08dc095d33eb5dcea82d524eb8e6615cf5f1129bfc333bf1674b6f2` failed: Container ID (00affa7ac08dc095d33eb5dcea82d524eb8e6615cf5f1129bfc333bf1674b6f2) does not exist

You seem to use kata containers, right? Could it be that CRI-O pods are not mapped 1:1 into kata containers?

**Comment by neolit123** [comment] 2018-06-18 16:16
@bart0sh 

> You seem to use kata containers, right? Could it be that CRI-O pods are not mapped 1:1 into kata containers?

possibly, yes. i wouldn't qualify this as a kubeadm bug.

**Comment by bart0sh** [comment] 2018-06-19 12:03
@yadavkkumar ok, let's do it step by step. First let's check why kubeadm fails to list pods. Can you run this command and show the output here:

```
sudo kubeadm reset -v
```

**Comment by bart0sh** [comment] 2018-06-19 12:08
Just to check my other suspicion can you show the output of these 3 commands:
```
sudo crictl -r /var/run/dockershim.sock pods -q
```

```
sudo crictl -r unix:///var/run/dockershim.sock pods -q
```

and 

```
sudo kubeadm reset --cri-socket unix:///var/run/dockershim.sock -v
```

I suspect that this issue is the same as [this one](https://github.com/kubernetes/kubeadm/issues/926)

**Comment by yadavkkumar** [comment] 2018-06-20 12:20
@bart0sh 
Following are the output
`sudo crictl -r /var/run/dockershim.sock pods -q`
```
W0620 17:22:51.800339   10476 util_unix.go:75] Using "/var/run/dockershim.sock" as endpoint is deprecated, please consider using full url format "unix:///var/run/dockershim.sock".
2018/06/20 17:22:51 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix /var/run/dockershim.sock: connect: no such file or directory"; Reconnecting to {/var/run/dockershim.sock <nil>}
FATA[0000] listing pod sandboxes failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable 
```

`sudo crictl -r unix:///var/run/dockershim.sock pods -q`
```
2018/06/20 17:23:40 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix /var/run/dockershim.sock: connect: no such file or directory"; Reconnecting to {/var/run/dockershim.sock <nil>}
FATA[0000] listing pod sandboxes failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable 
```
`sudo kubeadm reset --cri-socket unix:///var/run/dockershim.sock -v1`
```
Error: unknown shorthand flag: 'v' in -v1
Usage:
  kubeadm reset [flags]

Flags:
      --cert-dir string                   The path to the directory where the certificates are stored. If specified, clean this directory. (default "/etc/kubernetes/pki")
      --cri-socket string                 The path to the CRI socket to use with crictl when cleaning up containers. (default "/var/run/dockershim.sock")
  -h, --help                              help for reset
      --ignore-preflight-errors strings   A list of checks whose errors will be shown as warnings. Example: 'IsPrivilegedUser,Swap'. Value 'all' ignores errors from all checks.

error: unknown shorthand flag: 'v' in -v1
```
`sudo kubeadm reset --cri-socket unix:///var/run/dockershim.sock` 
gives same error.
`Failed to list running containers`
```
[preflight] Running pre-flight checks.
[reset] Stopping the kubelet service.
[reset] Unmounting mounted directories in "/var/lib/kubelet"
[reset] Removing kubernetes-managed containers.
[reset] Cleaning up running containers using crictl with socket unix:///var/run/dockershim.sock
[reset] Failed to list running pods using crictl. Trying using docker instead.
[reset] Deleting contents of stateful directories: [/var/lib/kubelet /etc/cni/net.d /var/lib/dockershim /var/run/kubernetes /var/lib/etcd]
[reset] Deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
[reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/bootstrap-kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]
```

For kubeadm init i am using the following command
`sudo kubeadm init --skip-preflight-checks --cri-socket /var/run/crio/crio.sock --pod-network-cidr=10.244.0.0/16`

And the output of reset command is
`sudo kubeadm reset --skip-preflight-checks --cri-socket /var/run/crio/crio.sock`
```
Flag --skip-preflight-checks has been deprecated, it is now equivalent to --ignore-preflight-errors=all
[preflight] Running pre-flight checks.
[reset] Stopping the kubelet service.
[reset] Unmounting mounted directories in "/var/lib/kubelet"
[reset] Removing kubernetes-managed containers.
[reset] Cleaning up running containers using crictl with socket /var/run/crio/crio.sock
[reset] Failed to list running pods using crictl. Trying using docker instead.
[reset] Deleting contents of stateful directories: [/var/lib/kubelet /etc/cni/net.d /var/lib/dockershim /var/run/kubernetes /var/lib/etcd]
[reset] Deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
[reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/bootstrap-kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]
```

**Comment by bart0sh** [comment] 2018-06-20 12:29
ah, ok. Sorry, didn't notice that you're using non-default cri socket
Please, provide output of these commands:
```
sudo crictl -r /var/run/crio/crio.sock pods -q
sudo crictl -r unix:///var/run/crio/crio.sock pods -q
```

**Comment by yadavkkumar** [comment] 2018-06-21 05:46
@bart0sh 
Following are the output
`sudo crictl -r /var/run/crio/crio.sock pods -q`
```
W0621 11:12:37.282863   18541 util_unix.go:75] Using "/var/run/crio/crio.sock" as endpoint is deprecated, please consider using full url format "unix:///var/run/crio/crio.sock".
0b7724c051404ebea040882dd12cd850bd719dd982f984ec7e199244f6d299e5
75441ff45210911360bb8abde3995ea5ebf3ba43058f91bdf25f8e00d6196d33
c62c47e51301c4531b1e7478f3d6426fd163dd0ca7b3dc6453eec0457aaea58d
6df96e6bea98128f41a9b771b606fe94bc7af204276bc830cc734f4894844554
ae3227a3a6a53dfee9c60b580158bbc0a910ba51a71bd5c213cd87940564948d
ab8dee40d099e1fb9a97a9ee7f7f10b35b8760583adaff70293a93b26a92f78e
d05036a51b5395515032676ad4301a9fdc880df55367da8dbd0f0e59f2cf022e
ceaf1ece03a8d9227d5e626825a74ec181d22464ce4528e5924cedc089b14fcb
02b74836f51dfd1dd9723b687024d851213bfaa597d1a977241907bca6650b53
52de58abbea59d17188c1a2607bb4dcd7becaf1e7df36c56ff039d9fa90b641e
7f072b9eb7769cf434b690352452434bca06956bca9ce9e647cc12e813bc1047
9dd9a6c2472a8304ac3fa068c2deb25b81eee7e0128ea945d0f7c09dac844030
1904954b02f29cc5695a0f31835cbfbb773480de4fd3203930948d298224602a
0a50342c7169eea3e80fde668f21aea52063879f2ae88f1c42b273a44e483b74
941ecb99a6952c85be60d7309bccec474d1d93f4156500190ce550394fd193dc
bb9ed8d6c849739fc4cb5c53776b31da1d79f5f815952e6a1bf1644aa937f033
6a7b680cefcfce84bbc995847a273fc8990117d8147c5afe7f2c17369eae1e32
0e92bc6230132e219cf6281cc83bb9a64bbeb509f5453664f04c3f2d21eaf7c1
e65d6434816a67e9021910f481399f7ff2b2aaad6ddc43a83b9f0ed910d0bb6d
b5c5a6a528b6647ce48ab41018b0ce75e592aa9d10167604b91dcd7351c15f0b
5b21bedec56c3949e839c4b41ee7a4be16819164747c131ad02d1c2cdc39c048
7ad55bd09c86e4d6bf21d8fa053ab675686b91161bca7985f3bda7c9ce397054
5e8e20d630fee728cf292eb6e9215d423f3ea8e0f4b5660b26441528eb0c5b93
cf979e1d7130a8eb7900476f130b73d9ac3a537f5d51b347cb156458bc44a7a2
```

Other one
`sudo crictl -r unix:///var/run/crio/crio.sock pods -q`
```
0b7724c051404ebea040882dd12cd850bd719dd982f984ec7e199244f6d299e5
75441ff45210911360bb8abde3995ea5ebf3ba43058f91bdf25f8e00d6196d33
c62c47e51301c4531b1e7478f3d6426fd163dd0ca7b3dc6453eec0457aaea58d
6df96e6bea98128f41a9b771b606fe94bc7af204276bc830cc734f4894844554
ae3227a3a6a53dfee9c60b580158bbc0a910ba51a71bd5c213cd87940564948d
ab8dee40d099e1fb9a97a9ee7f7f10b35b8760583adaff70293a93b26a92f78e
d05036a51b5395515032676ad4301a9fdc880df55367da8dbd0f0e59f2cf022e
ceaf1ece03a8d9227d5e626825a74ec181d22464ce4528e5924cedc089b14fcb
02b74836f51dfd1dd9723b687024d851213bfaa597d1a977241907bca6650b53
52de58abbea59d17188c1a2607bb4dcd7becaf1e7df36c56ff039d9fa90b641e
7f072b9eb7769cf434b690352452434bca06956bca9ce9e647cc12e813bc1047
9dd9a6c2472a8304ac3fa068c2deb25b81eee7e0128ea945d0f7c09dac844030
1904954b02f29cc5695a0f31835cbfbb773480de4fd3203930948d298224602a
0a50342c7169eea3e80fde668f21aea52063879f2ae88f1c42b273a44e483b74
941ecb99a6952c85be60d7309bccec474d1d93f4156500190ce550394fd193dc
bb9ed8d6c849739fc4cb5c53776b31da1d79f5f815952e6a1bf1644aa937f033
6a7b680cefcfce84bbc995847a273fc8990117d8147c5afe7f2c17369eae1e32
0e92bc6230132e219cf6281cc83bb9a64bbeb509f5453664f04c3f2d21eaf7c1
e65d6434816a67e9021910f481399f7ff2b2aaad6ddc43a83b9f0ed910d0bb6d
b5c5a6a528b6647ce48ab41018b0ce75e592aa9d10167604b91dcd7351c15f0b
5b21bedec56c3949e839c4b41ee7a4be16819164747c131ad02d1c2cdc39c048
7ad55bd09c86e4d6bf21d8fa053ab675686b91161bca7985f3bda7c9ce397054
5e8e20d630fee728cf292eb6e9215d423f3ea8e0f4b5660b26441528eb0c5b93
cf979e1d7130a8eb7900476f130b73d9ac3a537f5d51b347cb156458bc44a7a2

```

**Comment by bartosh** [comment] 2018-06-21 09:03
Interesting. Can you show return code of the first command? that's the command kubeadm fails to run, but you seem to be able to run it just fine.

Can you also run this command and show the output here:

```
sudo kubeadm reset --cri-socket unix:///var/run/crio/crio.sock
```

**Comment by yadavkkumar** [comment] 2018-06-21 09:52
@bart0sh 
This `kubeadm reset` is throwing same error (Failed to list running pods using crictl.).
`sudo kubeadm reset --cri-socket unix:///var/run/crio/crio.sock`
```
[preflight] Running pre-flight checks.
[reset] Stopping the kubelet service.
[reset] Unmounting mounted directories in "/var/lib/kubelet"
[reset] Removing kubernetes-managed containers.
[reset] Cleaning up running containers using crictl with socket unix:///var/run/crio/crio.sock
[reset] Failed to list running pods using crictl. Trying using docker instead.
[reset] Deleting contents of stateful directories: [/var/lib/kubelet /etc/cni/net.d /var/lib/dockershim /var/run/kubernetes /var/lib/etcd]
[reset] Deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
[reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/bootstrap-kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]

```
Sorry i didn't get this

> Interesting. Can you show return code of the first command? that's the command kubeadm fails to run, but you seem to be able to run it just fine.

**Comment by bartosh** [comment] 2018-06-21 11:06
I figured out what is it. You're using kubeadm 1.0.0. CRI related code in 'kubeadm reset' is absolutely broken there by [this change ](https://github.com/kubernetes/kubernetes/pull/58802). Can you try to install kubeadm 1.0.3 and run this command?

```
sudo kubeadm reset --cri-socket unix:///var/run/crio/crio.sock
```

**Comment by bart0sh** [comment] 2018-06-21 11:21
sorry, I mean kubeadm 1.10.0 and 1.10.3

**Comment by yadavkkumar** [comment] 2018-06-22 09:02
@bart0sh 
Thanks for the solution, i have upgraded my kubeadm to 1.10.4
and tried `sudo kubeadm reset --cri-socket unix:///var/run/crio/crio.sock` it is working fine and gives the following output.
```
[preflight] Running pre-flight checks.
[reset] Stopping the kubelet service.
[reset] Unmounting mounted directories in "/var/lib/kubelet"
[reset] Removing kubernetes-managed containers.
[reset] Cleaning up running containers using crictl with socket unix:///var/run/crio/crio.sock
[reset] Listing running pods using crictl
[reset] Executing command /usr/local/bin/crictl -r unix:///var/run/crio/crio.sock pods --quiet
[reset] Executing command /usr/local/bin/crictl -r unix:///var/run/crio/crio.sock stopp 1d40bd4e72bb77fe2403d49d964520819f41010535b0517d07bdc1a03d6d94e1
2767e068b7026c0f7f3b10e8ef80cb11a1c7ed9ffa8ad070cad38918239fd962
381324766da5be760deeed98d395d3d79eda07cf7ed1475dd49dfb4766b75f08
549796ca245dab27871927d6f450e8673be8844defa77bc6eb2c703d111a5656
3b3985cb7116e7a3e463ed97ac74234feaa8257c9abbff435ae0728062dd5669
40319e4ae1aef0b083f21c07f8a4813f869c1272e692aa0957dc882eacc6d431
94d8aed34a3df2df6371d60bc834531acb4d3e6d14b8d1c09aac99668bc6f648
2b94602c8047ee2511126ef59cfcfc5569a67785b0627adc188a51d3d9a98175
70b2e0a02e407a4862fb1fe6af934eee3ee8b6a246ea7c3e6b182710098338a0
ceaf1ece03a8d9227d5e626825a74ec181d22464ce4528e5924cedc089b14fcb
02b74836f51dfd1dd9723b687024d851213bfaa597d1a977241907bca6650b53
52de58abbea59d17188c1a2607bb4dcd7becaf1e7df36c56ff039d9fa90b641e
7f072b9eb7769cf434b690352452434bca06956bca9ce9e647cc12e813bc1047
9dd9a6c2472a8304ac3fa068c2deb25b81eee7e0128ea945d0f7c09dac844030
1904954b02f29cc5695a0f31835cbfbb773480de4fd3203930948d298224602a
0a50342c7169eea3e80fde668f21aea52063879f2ae88f1c42b273a44e483b74
941ecb99a6952c85be60d7309bccec474d1d93f4156500190ce550394fd193dc
bb9ed8d6c849739fc4cb5c53776b31da1d79f5f815952e6a1bf1644aa937f033
6a7b680cefcfce84bbc995847a273fc8990117d8147c5afe7f2c17369eae1e32
0e92bc6230132e219cf6281cc83bb9a64bbeb509f5453664f04c3f2d21eaf7c1
e65d6434816a67e9021910f481399f7ff2b2aaad6ddc43a83b9f0ed910d0bb6d
b5c5a6a528b6647ce48ab41018b0ce75e592aa9d10167604b91dcd7351c15f0b
5b21bedec56c3949e839c4b41ee7a4be16819164747c131ad02d1c2cdc39c048
7ad55bd09c86e4d6bf21d8fa053ab675686b91161bca7985f3bda7c9ce397054
5e8e20d630fee728cf292eb6e9215d423f3ea8e0f4b5660b26441528eb0c5b93
cf979e1d7130a8eb7900476f130b73d9ac3a537f5d51b347cb156458bc44a7a2

[reset] executing command /usr/local/bin/crictl -r unix:///var/run/crio/crio.sock rmp 1d40bd4e72bb77fe2403d49d964520819f41010535b0517d07bdc1a03d6d94e1
2767e068b7026c0f7f3b10e8ef80cb11a1c7ed9ffa8ad070cad38918239fd962
381324766da5be760deeed98d395d3d79eda07cf7ed1475dd49dfb4766b75f08
549796ca245dab27871927d6f450e8673be8844defa77bc6eb2c703d111a5656
3b3985cb7116e7a3e463ed97ac74234feaa8257c9abbff435ae0728062dd5669
40319e4ae1aef0b083f21c07f8a4813f869c1272e692aa0957dc882eacc6d431
94d8aed34a3df2df6371d60bc834531acb4d3e6d14b8d1c09aac99668bc6f648
2b94602c8047ee2511126ef59cfcfc5569a67785b0627adc188a51d3d9a98175
70b2e0a02e407a4862fb1fe6af934eee3ee8b6a246ea7c3e6b182710098338a0
ceaf1ece03a8d9227d5e626825a74ec181d22464ce4528e5924cedc089b14fcb
02b74836f51dfd1dd9723b687024d851213bfaa597d1a977241907bca6650b53
52de58abbea59d17188c1a2607bb4dcd7becaf1e7df36c56ff039d9fa90b641e
7f072b9eb7769cf434b690352452434bca06956bca9ce9e647cc12e813bc1047
9dd9a6c2472a8304ac3fa068c2deb25b81eee7e0128ea945d0f7c09dac844030
1904954b02f29cc5695a0f31835cbfbb773480de4fd3203930948d298224602a
0a50342c7169eea3e80fde668f21aea52063879f2ae88f1c42b273a44e483b74
941ecb99a6952c85be60d7309bccec474d1d93f4156500190ce550394fd193dc
bb9ed8d6c849739fc4cb5c53776b31da1d79f5f815952e6a1bf1644aa937f033
6a7b680cefcfce84bbc995847a273fc8990117d8147c5afe7f2c17369eae1e32
0e92bc6230132e219cf6281cc83bb9a64bbeb509f5453664f04c3f2d21eaf7c1
e65d6434816a67e9021910f481399f7ff2b2aaad6ddc43a83b9f0ed910d0bb6d
b5c5a6a528b6647ce48ab41018b0ce75e592aa9d10167604b91dcd7351c15f0b
5b21bedec56c3949e839c4b41ee7a4be16819164747c131ad02d1c2cdc39c048
7ad55bd09c86e4d6bf21d8fa053ab675686b91161bca7985f3bda7c9ce397054
5e8e20d630fee728cf292eb6e9215d423f3ea8e0f4b5660b26441528eb0c5b93
cf979e1d7130a8eb7900476f130b73d9ac3a537f5d51b347cb156458bc44a7a2

[reset] No etcd manifest found in "/etc/kubernetes/manifests/etcd.yaml". Assuming external etcd.
[reset] Deleting contents of stateful directories: [/var/lib/kubelet /etc/cni/net.d /var/lib/dockershim /var/run/kubernetes]
[reset] Deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
[reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/bootstrap-kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]

```

Now the problem is, in output it says that it has stopped and removed all the pods but when i run `sudo crictl pods` and `sudo crictl ps` commands all the pods are still there with state as `NotReady`

Deleting these pods with 
`sudo /usr/local/bin/crictl -r /var/run/crio/crio.sock rmp cf979e1d7130a` and `sudo crictl rmp cf979e1d7130a` gives the following error.
```
W0622 14:25:04.845343   11303 util_unix.go:75] Using "/var/run/crio/crio.sock" as endpoint is deprecated, please consider using full url format "unix:///var/run/crio/crio.sock".
FATA[0000] removing the pod sandbox "cf979e1d7130a" failed: rpc error: code = Unknown desc = failed to delete container k8s_sidecar_kube-dns-86f4d74b45-5mfj6_kube-system_ad9765f2-6ec7-11e8-a3e6-8851fb5bd321_0 in pod sandbox cf979e1d7130a8eb7900476f130b73d9ac3a537f5d51b347cb156458bc44a7a2: `/usr/bin/kata-runtime delete --force 1fdf1ccc6ea85ab0feebd4e208898c874cc9b29731517d90c11d4994e5bf7019` failed: Container ID (1fdf1ccc6ea85ab0feebd4e208898c874cc9b29731517d90c11d4994e5bf7019) does not exist
  (exit status 1) 
```

Now the question is if kubeadm reset is not able to reset whole cluster then why it showing that all the pods are stopped and removed.
Why deleting the pods is not possible if the the container is created in kata-runtime, why it always says that container doesn't exits with this ID.

**Comment by bart0sh** [comment] 2018-06-22 10:33
@yadavkkumar Now the question is if kubeadm reset is not able to reset whole cluster then why it showing that all the pods are stopped and removed.

kubeadm runs ```crioctl stopp``` and ```crioctl rmp``` for every found pod and checks return codes of both commands. If any of command exits with error kubeadm shows error message too. Now the question is what's wrong in this logic from your point of view? How kubeadm should know that something went wrong if above commands succeed?

> Why deleting the pods is not possible if the the container is created in kata-runtime, why it always says that container doesn't exits with this ID.

This is definitely question for runtime developers, isn't it? kubeadm has nothing to do with how runtime stops and removes pods. It's a job of runtime.

PS: You can try [this fix](https://github.com/kubernetes/kubernetes/commit/25436cdc6a86b9fed05aa100980a4b51243f2e5a) It might help to go a bit further with this. Unfortunately it's not included in 1.10.* releases, so you can either wait for 1.11 to come out, build it yourself or use 1.11 rc.

**Comment by bart0sh** [comment] 2018-07-06 08:33
@timothysc I think this issue can be closed. It's not related to kubeadm.

**Comment by shenshouer** [comment] 2018-07-16 07:30
The same with me!

```
# kubeadm reset --cri-socket=/run/containerd/containerd.sock -v1
[reset] WARNING: changes made to this host by 'kubeadm init' or 'kubeadm join' will be reverted.
[reset] are you sure you want to proceed? [y/N]: y
[preflight] running pre-flight checks
I0716 15:28:34.071476  187408 reset.go:127] [reset] getting init system
[reset] stopping the kubelet service
[reset] unmounting mounted directories in "/var/lib/kubelet"
I0716 15:28:34.074897  187408 reset.go:144] [reset] executing command "awk '$2 ~ path {print $2}' path=/var/lib/kubelet /proc/mounts | xargs -r umount"
[reset] removing kubernetes-managed containers
[reset] cleaning up running containers using crictl with socket /run/containerd/containerd.sock
I0716 15:28:34.080816  187408 reset.go:208] [reset] listing running pods using crictl
I0716 15:28:34.080826  187408 reset.go:211] [reset] Executing command /usr/local/bin/crictl -r /run/containerd/containerd.sock pods --quiet
I0716 15:28:34.098412  187408 reset.go:219] [reset] Stopping and removing running containers using crictl
I0716 15:28:34.098445  187408 reset.go:225] [reset] Executing command /usr/local/bin/crictl -r /run/containerd/containerd.sock stopp W0716
[reset] failed to stop the running containers using crictl: exit status 1. Trying to use docker insteadI0716 15:28:34.116660  187408 checks.go:138] validating if the service is enabled and active
[reset] docker doesn't seem to be running. Skipping the removal of running Kubernetes containers
I0716 15:28:34.125352  187408 reset.go:161] [reset] checking for etcd manifest
[reset] no etcd manifest found in "/etc/kubernetes/manifests/etcd.yaml". Assuming external etcd
[reset] deleting contents of stateful directories: [/var/lib/kubelet /etc/cni/net.d /var/lib/dockershim /var/run/kubernetes]
I0716 15:28:34.125388  187408 reset.go:172] [reset] deleting content of /var/lib/kubelet
I0716 15:28:34.125429  187408 reset.go:172] [reset] deleting content of /etc/cni/net.d
I0716 15:28:34.125438  187408 reset.go:172] [reset] deleting content of /var/lib/dockershim
I0716 15:28:34.125470  187408 reset.go:172] [reset] deleting content of /var/run/kubernetes
I0716 15:28:34.125487  187408 reset.go:177] [reset] removing contents from the config and pki directories
[reset] deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
[reset] deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/bootstrap-kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]

# /usr/local/bin/crictl -r /run/containerd/containerd.sock pods --quiet
W0716 15:28:50.851776  187464 util_unix.go:75] Using "/run/containerd/containerd.sock" as endpoint is deprecated, please consider using full url format "unix:///run/containerd/containerd.sock".
459818ad19fa5bfe5e445ee972e023a7783d4098d2e24f744eb813b8d9801e24
97f239e951706c1b6f2234409e6020fd375cfeabe4280a6478fd56c953445c19
880b7122e888810429ed3b20d0760d12c1efeca016a704fd822eea3d35e65450
7d54fd33a1dd249f12a47f84d5710960e9702d738200fac4d312ab310cdad055
857f247b6297837957fd2cd38673809eb54892db4a7d35db25564c1e9155badf
```

**Comment by shenshouer** [comment] 2018-07-16 07:37
Worked find when  I used `kubeadm reset --cri-socket=unix:///run/containerd/containerd.sock -v1` , and all pod had deleted

**Comment by bart0sh** [comment] 2018-07-16 07:37
@shenshouer can you try if this works for you?
```
kubeadm reset --cri-socket=unix:///run/containerd/containerd.sock -v1
```

**Comment by bart0sh** [comment] 2018-10-10 13:57
Closing. The issue was caused by incorrectly working crictl or kata runtime.
/close

**Closed by bart0sh** 2018-10-10 13:57 UTC
Labels: area/ecosystem, help wanted, kind/bug, priority/awaiting-more-evidence, sig/node, state/needs-more-information
